#!/usr/bin/env node
// A surface's agent knows exactly what its page knows: this opens the built page in a headless browser, asks the page for the
// agent's instructions (the same function the page uses with Claude), and writes them to cloud/<surface>/context.js, which the
// server function imports. Run it after the catalog or the site's facts change (npm run cloud:context), then publish.
//   node cloud/context.mjs edencosmetic [--expr "advPrompt(true)"]
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { startServer } from '../.claude/skills/ailgen-studio/scripts/seo-serve.mjs';
import { loadPlaywright } from '../.claude/skills/ailgen-studio/scripts/lib.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const args = process.argv.slice(2), name = args.find(a => !a.startsWith('--')) || 'edencosmetic';
const expr = args.includes('--expr') ? args[args.indexOf('--expr') + 1] : 'advPrompt(true)';
const cfg = JSON.parse(fs.readFileSync(path.join(ROOT, 'surfaces.json'), 'utf8'));
const s = cfg.surfaces.find(x => x.name === name);
if (!s) { console.error('no surface ' + name + ' in surfaces.json'); process.exit(2); }

const srv = await startServer({ dir: path.join(ROOT, s.dir) });
const pw = loadPlaywright(), browser = await pw.chromium.launch();
try {
  const page = await browser.newPage();
  await page.route(/^https?:\/\/(?!127\.0\.0\.1|localhost)/, r => r.abort());   // the page's own facts only, nothing from outside
  await page.goto(srv.url + '/', { waitUntil: 'domcontentloaded' });
  await page.waitForFunction(e => { try { return typeof (0, eval)(e) === 'string'; } catch { return false; } }, expr.replace(/\(.*\)$/, '.toString()'), { timeout: 20000 });
  const system = await page.evaluate(e => (0, eval)(e), expr);
  if (typeof system !== 'string' || system.length < 200) throw new Error('the page gave no instructions (' + expr + ')');
  const file = path.join(ROOT, 'cloud', name, 'context.js');
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, `// Generated by cloud/context.mjs from ${s.dir}/index.html (${expr}) on ${new Date().toISOString().slice(0, 10)}. Do not edit: rebuild.\nexport const SYSTEM = ${JSON.stringify(system)};\n`);
  console.log(`  ${path.relative(ROOT, file)}: ${system.length} characters, ${system.split('\n').length} lines`);
} finally { await browser.close(); srv.close?.(); }
