#!/usr/bin/env node
// AILGEN Lab · the director's handbook: reference 18 of the ailgen-studio skill, generated from lab/arsenal.json so the shortlists,
// the stars and the junk pool in the skill never drift from the lab. The prose (how to direct) lives here; the tables are built.
//   node cloud/lab/arsenal/handbook.mjs      → .claude/skills/ailgen-studio/references/18-arsenal.md
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../..');
const A = JSON.parse(fs.readFileSync(path.join(ROOT, 'lab/arsenal.json'), 'utf8')), M = A.models, c = A.count;
const usd = v => v == null ? '?' : v === 0 ? 'free' : '$' + (v >= 1 ? v.toFixed(2) : v >= 0.01 ? v.toFixed(3) : v.toPrecision(2));
const star = n => n == null ? '·' : n ? '★'.repeat(n) : '-';
const metric = a => { const q = a.measured || {}; return q.aa ? `AA ${q.aa.index}` : q.cw ? `EQ ${q.cw.elo}` : q.t2i ? `T2I #${q.t2i.rank}` : q.edit ? `edit #${q.edit.rank}` : q.t2v ? `T2V #${q.t2v.rank}` : q.i2v ? `I2V #${q.i2v.rank}` : q.vedit ? `v-edit #${q.vedit.rank}` : q.tts ? `TTS #${q.tts.rank}` : q.stt ? `WER ${q.stt.wer}%` : q.music ? 'music arena' : ''; };
const SECT = { text: 'Text', image: 'Image', video: 'Video', voice: 'Voice', listen: 'Listening', music: 'Music', utility: 'Helpers' };
const JOBEN = { think: 'hard thinking: strategy, analysis', write: 'creative writing: script, story, voice-led copy', 'copy-he': 'Hebrew web and ad copy', 'plan-json': 'flow planning: structured JSON for the next steps', long: 'very long input', code: 'code and sites', agent: 'agents with tools', research: 'research with web search', see: 'reading images, packaging, documents', bulk: 'cheap volume: classify, extract, summarise', judge: 'judging an output against the brief', loose: 'mature writing, the most open filter',
  hero: 'photoreal hero image', edit: 'edit by instruction, keep subject from a reference', type: 'text inside the image', vector: 'logo, icon, SVG', mockup: 'flat, predictable mockup', style: 'art direction, style references', draft: 'cheap fast drafts', upscale: 'upscale', tryon: 'virtual try-on',
  film: 'cinematic shot from text', i2v: 'animate a still', refs: 'consistency from several references', sound: 'video with native sound', extend: 'extend a clip, first/last frame', avatar: 'talking head from a portrait',
  'voice-he': 'Hebrew narration', 'voice-en': 'English narration', acting: 'acted, emotional voice', cheap: 'cheap', 'stt-he': 'Hebrew transcription', 'stt-en': 'English transcription', speakers: 'speaker separation', score: 'instrumental score', song: 'song with lyrics',
  embed: 'search by meaning', rerank: 'rerank results', guard: 'safety check of a text', inpaint: 'mask inpainting',
  'image:loose': 'mature imagery, the most open filter', 'video:loose': 'mature video, the most open filter', 'video:edit': 'edit an existing video',
  'video:draft': 'cheap fast video drafts', 'video:upscale': 'upscale a video', 'voice:long': 'long, steady narration', 'voice:cheap': 'cheap voice', 'listen:cheap': 'cheap transcription' };

let md = `# 18 · The arsenal: which engine, for which job, and why

<!-- generated by cloud/lab/arsenal/handbook.mjs from lab/arsenal.json (${A.built.slice(0, 10)}); edit the knowledge, not this file -->

The lab can call ${c.total} models. The arsenal profiles every one of them and throws the dead weight into a **junk pool**:
${c.keep} stay in the arsenal (${c.keptByException} of them by an explicit exception), ${c.junk} are junk (${Object.entries(c.byRule).map(([r, n]) => `${r} ${n}`).join(', ')}).
Every profile carries the model's lineage, its power and its weakness in numbers, Hebrew support, tips, orchestration gotchas, the
independent measurements and the sources, and a filter-strictness rating: **★★★ = the least filtered** we found, no star = strict.
Researched ${A.researched}. The owner sees the same data in the lab's "ארסנל" tab and on every card of the paid catalog.

| Where | What |
|---|---|
| \`cloud/lab/arsenal/knowledge/*.mjs\` | the curated profiles, one entry per model, every claim with a source (Hebrew) |
| \`cloud/lab/arsenal/facts.json\` | what Cloudflare publishes: description, context, schema fields, media inputs, filter controls (\`facts.mjs\`) |
| \`cloud/lab/arsenal/sources/\` | snapshots of Artificial Analysis (LLM index, image/video/voice/music arenas, STT error rate), SpeechMap, EQ-Bench (\`sources.mjs\`) |
| \`cloud/lab/arsenal/measured.json\` | the lab's own calibration labels (\`calibrate.mjs\`) |
| \`lab/arsenal.json\` | everything joined, with the stars and a ranked shortlist per job (\`build.mjs\`, which fails on any broken reference) |

## How the director picks (do this every time)

1. **Name the job, not the model.** \`node cloud/lab/unified.mjs pick <job>\` prints the ranked shortlist (\`--free\`, \`--loose\`, \`--sector\`).
   The ranking is by an independent measurement for that job (below), not by brand.
2. **Read the profile of the top two.** \`node cloud/lab/unified.mjs profile <id>\`: the weakness and the gotchas decide more often than the rank.
3. **Hebrew is a hard gate.** Voice: only models whose profile says Hebrew (Inworld TTS-2, Eleven v3, OpenAI TTS). Listening: AssemblyAI
   Universal-3.5 Pro, GPT-4o Transcribe, Whisper Turbo. Text inside images is never reliable in Hebrew: set Hebrew type in code, over the image.
4. **Mature but legitimate work goes to the stars first** (a crime scene, an R-rated battle, a horror poster, satire): \`pick loose --sector …\`.
   The stars are about legitimate creative work; the law and each maker's terms still apply, and nothing here is a way around a filter.
5. **Draft cheap, finish expensive.** Every visual sector has a draft row; the hero model runs once, on the approved draft.
6. **A junk model runs only by name and with \`--junk\`.** The CLI refuses it otherwise and names the replacement; a flow that uses one prints a warning.
7. **Price per typical job is in every row.** Text: 2,000 tokens in and 1,000 out. Image: 1024². Video: 5 s at 720p. Voice: 1,000 characters.
   Listening: 10 minutes. A model without a published price (Seedance 2.5, Gemini Omni) runs only with \`--max-usd\`.

## The stars (filter strictness)

${A.stars.scale.map(s => `- **${s.n ? '★'.repeat(s.n) : 'no star'}**: ${s.text}`).join('\n')}

How a star is earned: text by SpeechMap's share of full answers to controversial-speech requests (90%+ ★★★, 75%+ ★★, 60%+ ★) and the
lab's calibration (eight identical requests: noir murder scene, R-rated battle, crude roast, fade-to-black romance, locksport, Tiananmen,
satire of a head of state, one Hebrew line); images and video by a switch in the model's own schema (\`disable_safety_checker\`,
\`safety_tolerance\` at its most permissive) or the lab's image calibration. A documented maker policy corrects downward. Confidence:
high = measured or a schema switch; medium = SpeechMap or a documented policy; low = reports.

`;
for (const [sec, title] of Object.entries(SECT)) {
  const kept = Object.values(M).filter(m => m.verdict === 'keep' && (sec === 'utility' ? ['embed', 'classify', 'vision', 'translate', 'other'].includes(m.sector) : m.sector === sec));
  const lo = kept.filter(m => m.stars?.n >= 1).sort((a, b) => b.stars.n - a.stars.n);
  if (lo.length) md += `**${title}, least filtered first:** ${lo.map(m => `\`${m.id}\` ${star(m.stars.n)}`).join(' · ')}\n\n`;
}
md += `## The shortlist per job

Columns: the first three picks (stars · tier · typical price · the measurement that ranks them), then the best free pick when there is one.
Rankings: text by the Artificial Analysis Intelligence Index (writing by EQ-Bench creative-writing Elo), images and video by the Artificial
Analysis arenas (blind human votes), voice by the TTS arena, listening by word error rate, cheap/draft jobs by price.

`;
for (const [sec, title] of Object.entries(SECT)) {
  const jobs = Object.values(A.jobs).filter(j => j.sector === sec && j.models.length);
  if (!jobs.length) continue;
  md += `### ${title}\n\n| Job | 1 | 2 | 3 | Free |\n|---|---|---|---|---|\n`;
  for (const j of jobs) {
    const cell = id => { const a = M[id]; return a ? `\`${id}\` ${star(a.stars?.n)} ${a.paid ? a.tier : 'free'} ${usd(a.price?.usd)} ${metric(a)}`.trim() : ''; };
    const paid = j.models.filter(id => M[id].paid), free = j.models.find(id => !M[id].paid);
    const top = (paid.length ? paid : j.models).slice(0, 3);
    md += `| ${JOBEN[sec + ':' + j.job] || JOBEN[j.job] || j.job} | ${[0, 1, 2].map(i => top[i] ? cell(top[i]) : '').join(' | ')} | ${free ? cell(free) : ''} |\n`;
  }
  md += '\n';
}
const gotchas = Object.values(M).filter(m => m.verdict === 'keep' && m.gotchas.length);
md += `## Orchestration gotchas (from the profiles; Hebrew as written there)

${gotchas.map(m => `- \`${m.id}\`: ${m.gotchas.join(' · ')}`).join('\n')}

## The junk pool

${Object.entries(A.rules).filter(([k]) => /^R/.test(k)).map(([k, r]) => `- **${k} · ${r.name}**: ${r.text}`).join('\n')}
- **K · ${A.rules.K.name}**: ${A.rules.K.text}

| Model | Rule | Use instead |
|---|---|---|
${Object.values(M).filter(m => m.verdict === 'junk').sort((a, b) => a.sector.localeCompare(b.sector) || a.rule.localeCompare(b.rule) || a.id.localeCompare(b.id)).map(m => `| \`${m.id}\` | ${m.rule} | ${m.instead.map(i => '`' + i + '`').join(', ') || '(none needed)'} |`).join('\n')}

Kept by exception (K): ${Object.values(M).filter(m => m.keepBy === 'K').map(m => '`' + m.id + '`').join(', ')}.

## What the catalog does not have yet (seen on the boards, 2026-10-01)

GPT-6.1 Sol, Claude Sonnet 5.5, Gemini 4 Argon, DeepSeek V4.1 Flash, Muse Spark 1.3 (text); MAI-Image-2.6 (image); Eleven v4, Gemini 3.8
Flash TTS, Qwen-Audio-3.1-TTS (voice); Scribe v2, MAI-Transcribe-2 (listening); Suno v6, Mureka V9.5, Lyria 3.5, Eleven Music v2.5,
MiniMax Music 3.0 (music). When Cloudflare adds one, \`catalog-paid.mjs\` picks it up and \`build.mjs\` fails until it has a profile.

## Keeping it true

\`\`\`bash
node cloud/lab/catalog-paid.mjs --refresh      # Cloudflare's catalog and prices
node cloud/lab/arsenal/facts.mjs --refresh     # every model page and schema
node cloud/lab/arsenal/sources.mjs             # the independent boards (one request each)
node cloud/lab/arsenal/calibrate.mjs --free    # the filter calibration, inside the free allocation (plan printed first)
node cloud/lab/arsenal/build.mjs               # join, check, write lab/arsenal.json
node cloud/lab/arsenal/handbook.mjs            # this file
\`\`\`

Paid calibration, when credits exist: \`node cloud/lab/arsenal/calibrate.mjs --lab --models a,b --yes\` (through the lab's budget and
ledger), then read every answer and write its label into \`measured.json\`. A keyword guess never sets a star; a person or the agent
reading the answer does.
`;
const out = path.join(ROOT, '.claude/skills/ailgen-studio/references/18-arsenal.md');
fs.writeFileSync(out, md);
console.log(`→ ${path.relative(ROOT, out)} (${md.split('\n').length} lines)`);
