#!/usr/bin/env node
// Builds edencosmetic/src/2a-sprite.html: the inline SVG sprite (24 icons with the curl in the accent colour, the symbol, the full logo)
// and edencosmetic/src/3b-lotti.js data (the mascot grid) from brand/ and mascot/.
import { fileURLToPath } from 'url';
import fs from 'fs';
import path from 'path';
const HERE = path.dirname(fileURLToPath(import.meta.url)), PROJ = path.join(HERE, '..'), SITE = path.join(PROJ, '..', '..', 'edencosmetic');
const icons = JSON.parse(fs.readFileSync(path.join(PROJ, 'brand/icons.json'), 'utf8'));
const parts = JSON.parse(fs.readFileSync(path.join(PROJ, 'brand/symbol-parts.json'), 'utf8'));
const full = fs.readFileSync(path.join(PROJ, 'brand/logo-full.svg'), 'utf8');
const fullD = full.match(/ d="([^"]+)"/)[1], fullVb = full.match(/viewBox="([^"]+)"/)[1];
const all = parts.parts.ring + parts.parts.mono + parts.parts.lotus;
const syms = Object.entries(icons).map(([n, v]) => `<symbol id="i-${n}" viewBox="0 0 24 24" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.6"><path d="${v.ink}" stroke="currentColor"/><path d="${v.curl}" style="stroke:var(--accent)"/></symbol>`).join('\n');
const sprite = `<svg width="0" height="0" style="position:absolute" aria-hidden="true" focusable="false">
<defs>
<symbol id="sym-eden" viewBox="${parts.viewBox.join(' ')}"><path fill="currentColor" fill-rule="evenodd" d="${all}"/></symbol>
<symbol id="sym-mono" viewBox="${parts.viewBox.join(' ')}"><path fill="currentColor" fill-rule="evenodd" d="${parts.parts.mono}"/></symbol>
<symbol id="sym-lotus-shade" viewBox="426 102 68 60"><path fill="currentColor" d="${parts.parts.lotus}"/></symbol>
<symbol id="sym-logo" viewBox="${fullVb}"><path fill="currentColor" fill-rule="evenodd" d="${fullD}"/></symbol>
${syms}
</defs>
</svg>
`;
fs.writeFileSync(path.join(SITE, 'src/2a-sprite.html'), sprite);
// the loader and the hero use the parts directly
fs.writeFileSync(path.join(SITE, 'src/3b-brand.js'), `/* generated by projects/edencosmetic/site-src/make-sprite.mjs from brand/symbol-parts.json and mascot/mascot.json */\nconst SYM=${JSON.stringify({ vb: parts.viewBox, ring: parts.parts.ring, mono: parts.parts.mono, lotus: parts.parts.lotus })};\nconst LOTTI=${JSON.stringify(JSON.parse(fs.readFileSync(path.join(PROJ, 'mascot/mascot.json'), 'utf8')))};\n`);
console.log('sprite', fs.statSync(path.join(SITE, 'src/2a-sprite.html')).size, 'bytes;', Object.keys(icons).length, 'icons');
