<script>
/* ---------- the full creation flow (the real Talor Karadi case) ---------- */
const SB={"name": "סבבי", "grid": ["........................", ".......HHHHHHHHHH.......", "......hhhhhHHhhhhh......", ".....hhhhhhHHhhhhhh.....", "...hhhhhhhhhhhhhhhhhh...", ".....gGGGGG..bbbbbb.....", "....ggGGGGG.bbbbbbbb....", "...gggGGGGGbbbbbbbbbb...", "...ggggGGG.bbbbbBBBBB...", "..gggggGGKKKKKKBBBBBBB..", "..gggggGKKKKKKKKBBBBBB..", "...gggggKKKKKKKKBBBBBB..", ".B..gggKKKKKKKKKK..BBBB.", ".BB..ggKKKKKKKKKKgg..BB.", ".BBBB..KKKKKKKKKKggg..B.", "..BBBBBBKKKKKKKKggggg...", "..BBBBBBKKKKKKKKGggggg..", "..BBBBBBBKKKKKKGGggggg..", "...BBBBBbbbbb.GGGgggg...", "...bbbbbbbbbbGGGGGggg...", "....bbbbbbbb.GGGGGgg....", ".....bbbbbb..GGGGGg.....", "......bbbb..GGGGGg......", "........KK.GGGKK........", "........KK....KK........", ".......hhh....hhh......."], "colors": {"K": "#0B1B2E", "g": "#9ACB63", "G": "#2E8B3E", "b": "#7FBEE6", "B": "#2560A8", "h": "#C9F03A", "H": "#A8CC1E", "r": "#FF5A4E", "w": "#FFFFFF"}, "faces": {"idle": [[9, 11, 2, 2, "h"], [13, 11, 2, 2, "h"], [10, 15, 4, 1, "h"]], "blink": [[9, 12, 2, 1, "h"], [13, 12, 2, 1, "h"], [10, 15, 4, 1, "h"]], "look": [[8, 11, 2, 2, "h"], [12, 11, 2, 2, "h"], [10, 15, 3, 1, "h"]], "happy": [[8, 12, 1, 1, "h"], [9, 11, 2, 1, "h"], [11, 12, 1, 1, "h"], [12, 12, 1, 1, "h"], [13, 11, 2, 1, "h"], [15, 12, 1, 1, "h"], [9, 14, 6, 1, "h"], [10, 15, 4, 1, "h"]], "think": [[9, 10, 2, 1, "h"], [13, 10, 2, 1, "h"], [9, 15, 1, 1, "h"], [11, 15, 1, 1, "h"], [13, 15, 1, 1, "h"]], "sleep": [[9, 12, 2, 1, "h"], [13, 12, 2, 1, "h"], [11, 15, 2, 1, "h"]], "surprised": [[9, 10, 2, 3, "h"], [13, 10, 2, 3, "h"], [11, 14, 2, 2, "h"]], "love": [[8, 11, 1, 1, "r"], [10, 11, 1, 1, "r"], [8, 12, 3, 1, "r"], [9, 13, 1, 1, "r"], [13, 11, 1, 1, "r"], [15, 11, 1, 1, "r"], [13, 12, 3, 1, "r"], [14, 13, 1, 1, "r"], [10, 15, 4, 1, "h"]]}, "cell": 11, "hub": [11.5, 13.0, 4.9]};
const AIL_CASE='https://claude.ai/artifact/KEyTNCaGtF4GhgHZDLPwNk#case-talor'; /* the case in the AILGEN portfolio */
const TK_LIVE='https://claude.ai/artifact/7aj1NcY14KNP9ygLgadNYL'; /* the live preview of the Talor Karadi site */
function sbSVG(face='idle',spinning=false){ const px=(x,y,c,w=1,h=1)=>`<rect x="${x}" y="${y}" width="${w}" height="${h}" fill="${c}"/>`;
 let s=''; SB.grid.forEach((row,y)=>[...row].forEach((ch,x)=>{ if(ch!=='.')s+=px(x,y,SB.colors[ch]); }));
 s+=(SB.faces[face]||[]).map(([x,y,w,h,k])=>px(x,y,SB.colors[k],w,h)).join('');
 return `<svg viewBox="-1 -2 26 30" aria-hidden="true">${s}</svg>`; }
const FLOW=[
 ['01','הקלט: קישור אחד','https://talorkaradi.co.il/','אתר וורדפרס ואלמנטור של קבוצה שעוסקת במיחזור פסולת בניין, הריסות, בטון, הנדסה ומיגון. זה כל מה שהסטודיו קיבל.',
  ()=>`<figure><img src="img/tk-old.webp" alt="האתר הקיים" loading="lazy"><figcaption><span>האתר הקיים, צילום מסך של הסורק</span><span class="lbl">מהשטח</span></figcaption></figure>`,1,'2:40 קריאת מצב'],
 ['02','איסוף: כל האתר, בנימוס','30 עמודים · 82 תמונות · 5 סרטונים','הסורק קרא כל עמוד, הוריד תמונות וסרטונים, אסף טלפונים וכתובות, וזיהה צבעים ופונטים. כל מספר נכנס לדף עובדות עם העמוד שממנו הגיע.',
  ()=>`<div class="facts"><div><b>מעל 90%</b> מהפסולת שמגיעה ממוחזרת<small>/sevices/recycling-plants/</small></div><div><b>1,000+</b> מכולות, כ-40 משאיות, אחת תמורת אחת<small>/sevices/waste-disposal/</small></div><div><b>25–30 ט׳</b> פסולת לכל 100 מ"ר בבנייה רגילה<small>מאמר: חישוב כמויות פסולת בניין</small></div><div><b>"יוצאת מהאתר בחלק ממיגונית"</b> המשפט שהפך לקונספט<small>/south/</small></div></div>`,1,'3:01 סריקה · 7:12 כולל קריאה'],
 ['03','DNA: הלוגו מוביל הכול','לפני ואחרי','הסמל היה תמונה מטושטשת של 249 פיקסלים. הסטודיו שרטט אותו מחדש בווקטור מתמונה של 1983 פיקסלים, וגילה בו את הקונספט: ארבעה להבים הם ארבעה שלבים במעגל. הפלטה נבדקה לניגודיות, והפונטים נבחרו לעברית.',
  ()=>`<figure><img src="img/tk-logo-old.png" alt="הלוגו הקיים, רסטר מטושטש" loading="lazy" style="image-rendering:pixelated;background:#fff;padding:18px"><figcaption><span>לפני: 249×60 פיקסלים</span></figcaption></figure><figure><div style="background:#0B1B2E;padding:22px;display:grid;place-items:center"><img src="img/tk-symbol.svg" alt="הסמל בווקטור" style="width:120px;background:none"></div><figcaption><span>אחרי: ווקטור, 4 להבים = 4 שלבים</span></figcaption></figure><figure><div class="pal">${['#0B1B2E','#F4F5F0','#1E7A38','#9ACB63','#2560A8','#C9F03A'].map(c=>`<span style="background:${c}"></span>`).join('')}</div><figcaption><span>פלטה: כל הזוגות AA ומעלה · Rubik + IBM Plex Mono</span></figcaption></figure>`,3,'2:36'],
 ['04','הדמות: סבבי','נולד מארבעת הלהבים','הגוף שלו הוא המעגל של הלוגו, הפנים על הרכזת, וכובע מגן בצבע זוהר. השם מחבר "סבב" ו"סבבה". שמונה מצבים, נימוסים קבועים (עד 6 טיפים בביקור, שקט לשבוע), והוא מסתובב כשמחשבים את מאזן הפסולת. אותה רשת פיקסלים באתר ובסרטון.',
  ()=>`<figure><div class="sbx">${sbSVG('happy')}</div><figcaption><span>סבבי</span><span class="lbl demo">דמות</span></figcaption></figure><figure><div class="sbstates">${[['idle','רגיל'],['look','מסתכל'],['think','חושב'],['sleep','ישן'],['surprised','מופתע'],['happy','שמח'],['love','אוהב'],['blink','ממצמץ']].map(([f,n])=>`<div>${sbSVG(f)}<span>${n}</span></div>`).join('')}</div><figcaption><span>8 מצבים</span></figcaption></figure>`,2,'v2'],
 ['05','האתר: המעגל, כתוב בקוד','כניסה מהלוגו · 9 שירותים · מרכז בקרה','הלהבים ננעלים לסמל בכניסה, והסמל בנוי מארבעה צילומי שטח. "המעגל" האינטראקטיבי, מפת 5 מתקנים, פרויקטים מהיוטיוב שלהם, מוקד דיגיטלי שעונה רק מהעובדות, ומרכז בקרה לבעלים.',
  ()=>`<figure><img src="img/tk-site.webp" alt="האתר החדש, מסך הפתיחה" loading="lazy"><figcaption><span>האתר החדש, דסקטופ</span><span class="lbl">צילום מסך</span></figcaption></figure><figure><img src="img/tk-circle.webp" alt="המעגל האינטראקטיבי" loading="lazy"><figcaption><span>המעגל: 4 שלבים, 90%+</span></figcaption></figure>`,2,'16:18'],
 ['06','כלי ההוכחה: מאזן פסולת','השאלה הראשונה של כל קבלן','כמה פסולת להצהיר בהיתר, כדי לא להיתקע בטופס 4? סוג הפרויקט והשטח, והכלי מחשב טווח, כמות להצהרה ורצועת ±15%, לפי הנוסחאות מהמדריך של הקבוצה, כתעודת שקילה. כל חישוב נשלח כפנייה עם המפרט.',
  ()=>`<figure><img src="img/tk-calc.webp" alt="מאזן הפסולת" loading="lazy"><figcaption><span>דסקטופ</span></figcaption></figure><figure><img src="img/tk-mcalc.webp" alt="מאזן הפסולת בנייד" loading="lazy" style="max-height:420px;object-fit:cover;object-position:top"><figcaption><span>נייד</span></figcaption></figure>`,2,''],
 ['07','הסרטון: סצנת חתימה','29 שניות · 9:16 ו-4:5 · פסקול מקורי','צילום אמיתי של הריסה מתפרק לאלפי חלקיקים, נשאב למערבולת של ארבעת הלהבים, הופך לחומר נקי, מתגבש למיגונית, ונסגר ללוגו. סבבי פותח ("רגע. זה לא פסולת.") ומסיים. כל מעבר הוא הלהבים מסתובבים.',
  ()=>`<figure><video controls playsinline preload="none" poster="img/tk-film-poster.jpg" src="img/tk-film.mp4" style="aspect-ratio:9/16;max-height:640px;margin-inline:auto"></video><figcaption><span>הסרטון, 9:16</span><span class="lbl">מהשטח + קוד</span></figcaption></figure><figure><div class="story" style="grid-template-columns:repeat(3,1fr);padding:10px;background:#0B1B2E">${['tk-m1','tk-m2','tk-m3','tk-m4','tk-m5','tk-m6'].map((f,i)=>`<div style="background:#0B1B2E url(img/${f}.webp) center/cover"><small style="background:rgba(7,11,46,.7);padding:2px 4px;border-radius:4px;color:#fff">${['פסולת','חלקיקים','מערבולת','חומר נקי','מיגונית','לוגו'][i]}</small></div>`).join('')}</div><figcaption><span>סצנת החתימה, פריים אחרי פריים</span></figcaption></figure>`,2,'2:24 תסריט · רינדור ברקע'],
 ['08','הקמפיין','3 סטילס · 3 טקסטים · 5 כותרות','A/B לשבוע הראשון: הסרטון מול "מעל 90%" מול "מאזן פסולת". קהל: קבלנים ויזמים בדרום ובמרכז, UTM מוכן, והערה ברורה: עד שהאתר החדש באוויר, המודעות מפנות למוקד.',
  ()=>['ad-feed','ad-square','ad-story'].map((f,i)=>`<figure><img src="img/tk-${f}.webp" alt="מודעה ${i+1}" loading="lazy"><figcaption><span>${['פיד 4:5','ריבוע 1:1','סטורי 9:16'][i]}</span></figcaption></figure>`).join(''),3,''],
 ['09','דומיין ומסירה','talorkaradi.co.il · קיים','הדומיין כבר שלהם. מחברים www ב-CNAME, מעבירים את הדומיין הראשי לשרתי השמות של ספק האחסון אחרי העתקת רשומות המייל, ו-HTTPS עולה לבד. לפני כן: קישור תצוגה לאישור, עם תווית "תצוגה מקדימה".',
  ()=>`<div class="facts"><div><b>www → CNAME</b> לפרויקט באחסון<small>DNS</small></div><div><b>@ → nameservers</b> אחרי העתקת MX ו-TXT<small>DNS</small></div><div><b>תצוגה מקדימה</b> קישור לאישור הלקוח<small id="tkLiveNote">בהמתנה לאישור</small></div></div>`,1,'']];
function renderFlow(){
 $('#fsteps').innerHTML=FLOW.map(([n,t,sub,p,vis,cols,tm])=>`<li class="fstep"><span class="dot">${n}</span><div><h3>${esc(t)}</h3><div class="tm"><span>${esc(sub)}</span>${tm?`<span>זמן: ${esc(tm)}</span>`:''}</div><p>${esc(p)}</p><div class="vis" style="--n:${cols}">${vis()}</div>${(n==='05'||n==='09')&&TK_LIVE?`<a class="btn go" href="${TK_LIVE}" target="_blank" rel="noopener">לאתר החי של טלאור כראדי ↗</a>`:''}</div></li>`).join('');
 const T=RUN.metrics&&RUN.metrics.tiles||[];
 $('#closed').innerHTML=[['9','שלבים, כל אחד עם שער בדיקה'],[T[2]?T[2][0].replace(/\D/g,''):'—','דקות עבודה, כל השרשרת (נמדד)'],[T[3]?T[3][0]:'—','עלות API, נמדדה'],['92 / 100','Lighthouse בנייד: ביצועים / נגישות']].map(([b,t])=>`<div><b>${esc(b)}</b><span>${esc(t)}</span></div>`).join('')
  +`<p class="cl">הפרויקט נסגר: האתר, סבבי, הסרטון והקמפיין מוכנים, והמקרה נכנס לתיק העבודות של AILGEN עם צילומי מסך אמיתיים.${AIL_CASE?` <a href="${AIL_CASE}" target="_blank" rel="noopener">לתיק הפרויקט ↗</a>`:''}</p>`;
 const r=$('#baR'), ba=$('#ba'); const upd=()=>ba.style.setProperty('--cut',r.value+'%'); r.addEventListener('input',upd); upd();
 if(TK_LIVE){const n=document.getElementById('tkLiveNote'); if(n)n.textContent='הקישור מוכן';}
}
</script>
