/* generated by projects/edencosmetic/site-src/make-data.mjs from edencosmetic/img/v/manifest.json (approved, reviewed images and videos only) */
const VISUAL={"images":{},"videos":{},"disclosure":null};
