<#
.SYNOPSIS
  Refresh the machine-generated state block in memory/SESSION.md and stamp the handoff.

.DESCRIPTION
  The block between the ailgen:auto markers is written by this script or by
  .opencode/plugin/memory.ts - never by hand. The script also refreshes the 'Last updated'
  line with the model stamp. Model resolution order: -Model, $env:AILGEN_MODEL, the [Model: ...]
  stamp of the last commit, then 'unknown'.
#>
[CmdletBinding()]
param([string]$Model, [switch]$Quiet)

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$start = "<!-- ailgen:auto:start -->"
$end = "<!-- ailgen:auto:end -->"

function Git-Out([string[]]$a) {
  Push-Location $root
  try { return ((& git @a 2>$null) | Out-String).Trim() } finally { Pop-Location }
}

if (-not $Model) { $Model = $env:AILGEN_MODEL }
if (-not $Model) {
  $last = Git-Out @("log", "-1", "--format=%s")
  if ($last -match "^\[Model: ([^\]]+)\]") { $Model = $Matches[1] }
}
if (-not $Model) { $Model = "unknown" }

$path = Join-Path $root "memory/SESSION.md"
if (-not (Test-Path -LiteralPath $path)) { throw "memory/SESSION.md not found; nothing to refresh" }
$raw = [System.IO.File]::ReadAllText($path, [System.Text.Encoding]::UTF8)

$head = Git-Out @("rev-parse", "--short", "HEAD"); if (-not $head) { $head = "no-commit" }
$branch = Git-Out @("rev-parse", "--abbrev-ref", "HEAD"); if (-not $branch) { $branch = "?" }
$porcelain = Git-Out @("status", "--porcelain=v1")
$lines = @($porcelain -split "`n" | Where-Object { $_.Trim().Length -gt 0 })
$shown = @($lines | Select-Object -First 20)
$extra = if ($lines.Count -gt $shown.Count) { " (+$($lines.Count - $shown.Count) more)" } else { "" }

$block = @(
  $start
  "<!-- generated by scripts/handoff.ps1 + .opencode/plugin/memory.ts - do not hand-edit inside these markers -->"
  ""
  "- refreshed: $([DateTime]::UtcNow.ToString('o'))"
  "- model: $Model"
  "- branch: $branch @ $head"
  "- working tree: $(if ($lines.Count -eq 0) { "clean" } else { "$($lines.Count) changed$extra" })"
  ""
  '```'
  $(if ($shown.Count) { $shown -join "`n" } else { "(clean)" })
  '```'
  $end
) -join "`n"

$i = $raw.IndexOf($start)
$j = $raw.IndexOf($end)
if ($i -ge 0 -and $j -gt $i) { $next = $raw.Substring(0, $i) + $block + $raw.Substring($j + $end.Length) }
else { $next = $raw.TrimEnd() + "`n`n" + $block + "`n" }

$stamp = [DateTime]::UtcNow.ToString("yyyy-MM-dd")
# No capture group here on purpose: a '$1' followed by digits (e.g. "$12026-09-28") is read by .NET as
# group 12026, silently dropping the prefix. That bug cost one handoff note its "Last updated:" line.
if ($next -match "(?m)^Last updated: [^\r\n]*") {
  $next = $next -replace "(?m)^Last updated: [^\r\n]*", "Last updated: $stamp | $Model"
}

$tmp = "$path.tmp-$PID"
[System.IO.File]::WriteAllText($tmp, $next, (New-Object System.Text.UTF8Encoding($false)))
Move-Item -LiteralPath $tmp -Destination $path -Force

if (-not $Quiet) {
  Write-Output "handoff refreshed: model=$Model branch=$branch@$head changed=$($lines.Count)"
  Write-Output "next: write the Goal reached / Current state / Exact next command / Open questions sections above the markers, then commit with the same [Model: $Model] stamp."
}
