// AILGEN Lab · the arsenal's curated knowledge, part 5: voice (text to speech), listening (speech to text) and music.
// refs: tts = Artificial Analysis TTS arena, stt = its word-error-rate table, music = its music arenas.
// Tiers: voice by arena Elo (top 1150+, mid 1080-1150, low under); listening by word error rate (top 3% or less, mid 3-5%, low above);
// music by arena. Hebrew support is the first question for every voice job in this studio, so each entry states it with its source.

export const AUDIO = {
  /* ---------------- voice ---------------- */
  'inworld/tts-2': { fam: 'inworld', tier: 'top', released: '2026-08-31',
    lineage: 'TTS-1 → TTS-1.5 (הוצא משימוש) → Realtime TTS-2.', power: 'הקול הכי טוב בקטלוג (1247 בארנה, מעל Eleven v3 ב-75 נקודות) ב-25$ למיליון תווים, רבע מ-ElevenLabs. עברית היא שפת ייצור (GA). היגוי בשפה טבעית: [whisper], [say excitedly]. 100ms עד הצליל הראשון.',
    weak: 'חדש; פחות קולות מוכנים מ-ElevenLabs.', jobs: ['voice-he', 'voice-en', 'acting', 'cheap'],
    tips: ['ברירת המחדל לקריינות בעברית בזרימה.', 'תגיות היגוי בתוך הטקסט במקום הוראות נפרדות.'], hebrew: 'כן: אחת מ-15 שפות הייצור (he).',
    refs: { tts: 'Realtime TTS-2' }, sources: ['inworld-models', 'inworld-langs', 'aa-tts'] },
  'elevenlabs/eleven-v3': { fam: 'elevenlabs', tier: 'top', released: '2026-02-02',
    lineage: 'Multilingual v2 (2023) → v3 (2026). כבר יצא Eleven v4 (90+ שפות, 10,000 תווים), עוד לא בקטלוג.', power: 'הכי רגשי של ElevenLabs: 74 שפות כולל עברית, תגיות רגש ([laughs], [whispers]), דיאלוג טבעי. 1172 בארנה.',
    weak: 'עד 5,000 תווים לבקשה; דורש יותר הנדסת פרומפט; פי ארבעה מ-Inworld TTS-2 שטוב ממנו בארנה. ElevenLabs כבר מסמנת אותו "דור קודם".',
    jobs: ['voice-he', 'acting'], tips: ['כשצריך קול מספרייה של ElevenLabs או שיבוט קול.', 'לפצל טקסט ארוך לקטעים של עד 5,000 תווים.'],
    hebrew: 'כן (אחת מ-74 השפות).', refs: { tts: 'Eleven v3' }, sources: ['elevenlabs-models', 'aa-tts'] },
  'google/gemini-3.1-flash-tts': { fam: 'google', tier: 'top', released: '2026-04-15',
    lineage: 'Gemini 2.5 Flash TTS → 3.1 Flash TTS. כבר יצא 3.8 Flash TTS (1272 בארנה), עוד לא בקטלוג.', power: '1205 בארנה; 70+ שפות; 30+ קולות; שליטה בסגנון בשפה טבעית; כמה דוברים.',
    weak: 'דיווח באג רשמי: לפרומפט עברי חוזר HTTP 200 עם שמע ריק (finishReason OTHER). מחיר לפי טוקנים.', jobs: ['voice-en', 'acting'],
    tips: ['לעברית לבדוק שהקובץ לא ריק לפני שממשיכים בזרימה.'], gotchas: ['שמע ריק בעברית: בדיקת אורך על הפלט.'],
    hebrew: 'ברשימה, עם באג מדווח של שמע ריק.', refs: { tts: 'Gemini 3.1 Flash TTS' }, sources: ['gemini-tts-he', 'aa-tts'] },
  'minimax/speech-2.8-hd': { fam: 'minimax', tier: 'top', released: '2026-02-14',
    lineage: 'Speech-02 → 2.6 → 2.8.', power: '1170 בארנה; 32 שפות; שיבוט קול ורגש.', weak: 'עברית לא ברשימה; 100$ למיליון תווים.',
    jobs: ['voice-en', 'acting'], hebrew: 'לא ברשימת השפות.', refs: { tts: 'Speech 2.8 HD' }, sources: ['minimax-speech', 'aa-tts'] },
  'minimax/speech-2.8-turbo': { fam: 'minimax', tier: 'mid', released: '2026-02-14',
    lineage: 'Speech 2.8 מהיר.', power: '1152 בארנה ב-60$ למיליון.', weak: 'עברית לא ברשימה.', jobs: ['voice-en'], hebrew: 'לא ברשימת השפות.', refs: { tts: 'Speech 2.8 Turbo' }, sources: ['aa-tts'] },
  'xai/grok-tts': { fam: 'xai', tier: 'mid', released: '2026-03-16',
    lineage: 'Grok TTS.', power: '1132 בארנה ב-15$ למיליון; 5 קולות; תגיות [laugh], [sigh], [whisper], <emphasis>, <slow>, <pause>.', weak: '20+ שפות בלי רשימה מפורסמת.',
    jobs: ['voice-en', 'cheap', 'acting'], hebrew: 'לא ידוע (הרשימה לא פורסמה).', refs: { tts: 'SpaceXAI TTS' }, sources: ['xai-voice', 'aa-tts'] },
  'openai/tts-1-hd': { fam: 'openai', tier: 'mid', released: '2023-11-06',
    lineage: 'TTS-1 HD (2023).', power: '1102 בארנה; קורא כל שפה ש-Whisper מכיר, כולל עברית; 30$ למיליון.', weak: 'ישן; בעברית מבטא זר.',
    jobs: ['voice-he', 'voice-en'], tips: ['גיבוי לעברית כש-Inworld או Eleven v3 לא זמינים.'], hebrew: 'כן, עם מבטא.', refs: { tts: 'TTS-1 HD' }, sources: ['aa-tts'] },
  'openai/tts-1': { fam: 'openai', tier: 'mid', released: '2023-11-06',
    lineage: 'TTS-1 (2023).', power: 'זול (15$ למיליון) עם 1089 בארנה; עברית.', weak: 'ישן; מבטא זר בעברית.', jobs: ['cheap', 'voice-he'], hebrew: 'כן, עם מבטא.', refs: { tts: 'TTS-1' }, sources: ['aa-tts'] },
  'elevenlabs/eleven-multilingual-v2': { fam: 'elevenlabs', tier: 'mid', released: '2023-08-22', keepBy: 'K',
    lineage: 'Multilingual v2 (2023).', power: 'הכי יציב ועקבי לקריינות ארוכה (עד 10,000 תווים), מנרמל מספרים טוב יותר; ElevenLabs ממליצה עליו לסרטי תדמית ולמידה.',
    weak: 'אין עברית (29 שפות). v3 טוב ממנו ב-80 נקודות באותו מחיר.', jobs: ['long', 'voice-en'], tips: ['רק לקריינות ארוכה באנגלית שחייבת להישמע אחידה מתחילה ועד סוף.'],
    hebrew: 'לא (29 שפות).', refs: { tts: 'Multilingual v2' }, sources: ['elevenlabs-models', 'aa-tts'] },
  'elevenlabs/eleven-flash-v2-5': { fam: 'elevenlabs', tier: 'low', released: '2024-12-18',
    lineage: 'Flash v2.5.', power: 'המהיר ביותר (75ms), עד 40,000 תווים בבקשה, חצי מחיר.', weak: 'אין עברית (32 שפות); 1076 בארנה.',
    jobs: ['cheap', 'voice-en'], hebrew: 'לא (32 שפות).', refs: { tts: 'Flash v2.5' }, sources: ['elevenlabs-models', 'aa-tts'] },
  'elevenlabs/eleven-turbo-v2-5': { fam: 'elevenlabs', junk: 'R1', instead: ['elevenlabs/eleven-flash-v2-5'], released: '2024-07-19',
    why: 'ElevenLabs עצמה: "We recommend using the Flash models over Turbo models in all use cases". אותו מחיר, אותן שפות (בלי עברית). בארנה הוא גבוה ב-20 נקודות, בתוך הרעש.', refs: { tts: 'Turbo v2.5' }, sources: ['elevenlabs-models', 'aa-tts'] },
  'inworld/tts-1.5-max': { fam: 'inworld', junk: 'R1', instead: ['inworld/tts-2'], released: null,
    why: 'Inworld הוציאה את TTS-1.5 משימוש ("לא מומלץ לפרויקטים חדשים; בקשות מנותבות אוטומטית לדגמים חדשים"). TTS-2 גם זול ממנו (25$ מול 35$ למיליון).', sources: ['inworld-models'] },
  'inworld/tts-1.5-mini': { fam: 'inworld', junk: 'R1', instead: ['inworld/tts-2', 'xai/grok-tts', 'openai/tts-1'], released: null,
    why: 'Inworld הוציאה את TTS-1.5 משימוש והבקשות מנותבות לדגמים אחרים; לקול זול ב-15$ למיליון יש Grok TTS ו-TTS-1 עם התנהגות ידועה.', sources: ['inworld-models'] },

  /* ---------------- listening ---------------- */
  'assemblyai/universal-3.5-pro': { fam: 'assemblyai', tier: 'top', released: null,
    lineage: 'Universal-2 → 3 Pro (3.1% WER) → 3.5 Pro.', power: 'עברית מקומית (18 שפות), מעבר שפה באמצע משפט (עברית-אנגלית), הפרדת הדוברים המדויקת ביותר של AssemblyAI, הנחיה בהקשר ומילות מפתח. 0.0035$ לדקה.',
    weak: 'הפרדת דוברים, מילות מפתח ומצב רפואי בתשלום נוסף לדקה.', jobs: ['stt-he', 'stt-en', 'speakers'],
    tips: ['לראיון בעברית עם מונחים באנגלית: בלי הגדרת שפה, הוא מזהה לבד.', 'keyterms לשמות מותג ומוצרים.'], hebrew: 'כן (מקומית, אחת מ-18).',
    refs: { stt: 'Universal-3 Pro' }, sources: ['assembly-u35', 'aa-stt'] },
  'xai/grok-stt': { fam: 'xai', tier: 'mid', released: null,
    lineage: 'Grok STT.', power: 'הזול בתשלום (0.0017$ לדקה), חותמות זמן למילה, הפרדת דוברים, ריבוי ערוצים, מילות מפתח. AA מודד את Grok Voice Transcribe ב-2.3% (גרסה 2.0) ו-4.0% (1.0).',
    weak: '25 שפות בלי רשימה מפורסמת; לא ידוע איזו גרסה מאחורי השם.', jobs: ['stt-en', 'cheap', 'speakers'],
    hebrew: 'לא ידוע.', refs: {}, sources: ['xai-voice', 'aa-stt'] },
  'openai/gpt-4o-transcribe': { fam: 'openai', tier: 'mid', released: '2025-03-20',
    lineage: 'Whisper → GPT-4o Transcribe.', power: '4.0% WER; עברית; עמיד לרעש.', weak: 'הכי יקר (0.006$ לדקה); בלי הפרדת דוברים.',
    jobs: ['stt-he', 'stt-en'], hebrew: 'כן.', refs: { stt: 'GPT-4o Transcribe' }, sources: ['aa-stt'] },
  'assemblyai/universal-3-pro': { fam: 'assemblyai', junk: 'R1', instead: ['assemblyai/universal-3.5-pro'], released: null,
    why: 'Universal-3.5 Pro באותו מחיר לדקה, עם עברית מקומית, מעבר שפה והפרדת דוברים מדויקת יותר.', refs: { stt: 'Universal-3 Pro' }, sources: ['assembly-u35'] },
  'xai/grok-voice': { fam: 'xai', junk: 'R3', instead: ['xai/grok-stt', 'xai/grok-tts'], released: null,
    why: 'שיחה קולית חיה ב-WebSocket בלבד; המעבדה מריצה בקשה אחת ותשובה אחת. לתמלול Grok STT, לקול Grok TTS.', sources: ['cf'] },

  /* ---------------- music ---------------- */
  'elevenlabs/music-v2': { fam: 'elevenlabs', tier: 'top', released: '2026-05-27',
    lineage: 'Eleven Music (אוגוסט 2025) → v2 (מאי 2026). כבר יצא v2.5, עוד לא בקטלוג.', power: 'שירים ופסקולים עד 10 דקות, החלפת סגנון באמצע השיר, בלוקים (פתיחה, בית, פזמון, גשר, סיום), 59 שפות שירה, נתונים מורשים לשימוש מסחרי. 0.0025$ לשנייה.',
    weak: 'בארנה רק 1001-1010, הרבה מתחת ל-Suno ו-Mureka (שלא בקטלוג). בתוכניות Self-Serve אסור לסרטים וטלוויזיה.', jobs: ['score', 'song'],
    tips: ['composition plan במקום פרומפט אחד לפסקול שמתאים לשוטים.'], hebrew: 'לא ברשימה המוצהרת.', refs: { music: 'Eleven Music v2' }, sources: ['eleven-music', 'aa-music'] },
  'minimax/music-2.6': { fam: 'minimax', tier: 'mid', released: '2026-04-10',
    lineage: 'Music 2.5+ → 2.6. כבר יצא 3.0, עוד לא בקטלוג.', power: 'שיר מלא עם שירה ותזמור עד כ-6 דקות, BPM וסולם מדויקים, תגיות מבנה, מילים או בלי. 0.15$ לשיר.',
    weak: 'בארנה 1001-1002.', jobs: ['song', 'score'], tips: ['כשהקצב חייב להתאים לעריכה (BPM ידוע).'], hebrew: 'לא מוצהר.', refs: { music: 'MiniMax Music 2.6' }, sources: ['minimax-music', 'aa-music'] },

  /* ---------------- free (Workers AI) ---------------- */
  '@cf/openai/whisper-large-v3-turbo': { fam: 'openai-open', tier: 'free', released: '2024-05-22',
    lineage: 'Whisper large-v3 מזוקק.', power: 'תמלול עברית חינם (0.0005$ לדקה מעבר למכסה), 4.6% WER, מהיר.', weak: 'בלי הפרדת דוברים.',
    jobs: ['stt-he', 'stt-en', 'cheap'], hebrew: 'כן.', refs: { stt: 'Whisper Large v3 Turbo' }, sources: ['aa-stt', 'wai-pricing'] },
  '@cf/deepgram/nova-3': { fam: 'deepgram', tier: 'free', released: '2025-06-05',
    lineage: 'Nova-2 → Nova-3.', power: 'מהיר מאוד (מהיר פי 569 מזמן אמת), 5.2% WER.', weak: 'פי עשרה מ-Whisper Turbo במכסה.',
    jobs: ['stt-en'], hebrew: 'לא נבדקה.', refs: { stt: 'Nova-3' }, sources: ['aa-stt', 'wai-pricing'] },
  '@cf/deepgram/aura-2-en': { fam: 'deepgram', tier: 'free', released: '2025-10-09',
    lineage: 'Aura-1 → Aura-2.', power: 'קול אנגלי טבעי עם קצב והקשר; חינם במכסה.', weak: '2,727 נוירונים לאלף תווים: כמה פסקאות ביום.', jobs: ['voice-en'], hebrew: 'לא.', refs: {}, sources: ['wai-pricing'] },
  '@cf/deepgram/aura-2-es': { fam: 'deepgram', tier: 'free', released: '2025-10-09',
    lineage: 'Aura-2 ספרדית.', power: 'קול ספרדי.', weak: 'שפה אחת.', jobs: ['voice-en'], hebrew: 'לא.', refs: {}, sources: ['wai-pricing'] },
  '@cf/deepgram/aura-1': { fam: 'deepgram', tier: 'free', released: '2025-08-27',
    lineage: 'Aura-1.', power: 'חצי ממחיר Aura-2 במכסה.', weak: 'איכות נמוכה מ-Aura-2.', jobs: ['cheap'], hebrew: 'לא.', refs: {}, sources: ['wai-pricing'] },
  '@cf/myshell-ai/melotts': { fam: 'misc', tier: 'free', released: '2024-07-19',
    lineage: 'MeloTTS (MyShell).', power: 'הקול הכי זול בקטלוג (19 נוירונים לדקת שמע); אנגלית, ספרדית, צרפתית, סינית, יפנית, קוריאנית.', weak: 'איכות בסיסית; בלי עברית.',
    jobs: ['cheap'], hebrew: 'לא.', refs: {}, sources: ['wai-pricing'] },
  '@cf/openai/whisper': { fam: 'openai-open', junk: 'R2', instead: ['@cf/openai/whisper-large-v3-turbo'], released: '2023-09-25',
    why: 'Whisper Turbo מדויק ממנו בהרבה, בתוספת של 0.00006$ לדקה.', sources: ['wai-pricing', 'aa-stt'] },
  '@cf/openai/whisper-tiny-en': { fam: 'openai-open', junk: 'R2', instead: ['@cf/openai/whisper-large-v3-turbo'], released: '2024-04-22',
    why: 'הקטן ביותר, אנגלית בלבד; Whisper Turbo מתמלל גם עברית ובדיוק גבוה בהרבה.', sources: ['cf'] },
  '@cf/deepgram/flux': { fam: 'deepgram', junk: 'R3', instead: ['@cf/deepgram/nova-3'], released: '2025-09-29',
    why: 'תמלול לסוכני קול בזמן אמת דרך WebSocket בלבד.', sources: ['cf'] },
  '@cf/pipecat-ai/smart-turn-v2': { fam: 'misc', junk: 'R4', instead: [], released: '2025-08-04',
    why: 'מזהה מתי דובר סיים לדבר בשיחה חיה עם סוכן קול; אין משימה כזו בסטודיו.', sources: ['cf'] },
};
