// AILGEN Lab · the arsenal's curated knowledge, part 1: the rules, the sources, the jobs and every maker.
// The per-model profiles are in text.mjs, image.mjs, video.mjs, audio.mjs and utility.mjs; build.mjs joins them with the machine-read
// facts (facts.json), the independent measurements (sources/*.json) and the lab's own calibration (measured.json) into lab/arsenal.json.
// Researched 2026-10-01. Every claim here names its source; a number without a source does not belong in this file.

export const RESEARCHED = '2026-10-01';

// where the numbers come from. Snapshots of the independent boards live in cloud/lab/arsenal/sources/ (only the rows the catalog uses).
export const SOURCES = {
  cf: { title: 'Cloudflare AI model catalog (each model page, its schema and price)', url: 'https://developers.cloudflare.com/ai/models/' },
  'aa-llm': { title: 'Artificial Analysis · LLM leaderboard (Intelligence Index v4.1, price, speed, hallucination)', url: 'https://artificialanalysis.ai/leaderboards/models' },
  'aa-t2i': { title: 'Artificial Analysis · text-to-image arena (Elo from blind human votes)', url: 'https://artificialanalysis.ai/image/leaderboard/text-to-image' },
  'aa-edit': { title: 'Artificial Analysis · image-editing arena', url: 'https://artificialanalysis.ai/image/leaderboard/editing' },
  'aa-t2v': { title: 'Artificial Analysis · text-to-video arena', url: 'https://artificialanalysis.ai/video/leaderboard/text-to-video' },
  'aa-i2v': { title: 'Artificial Analysis · image-to-video arena', url: 'https://artificialanalysis.ai/video/leaderboard/image-to-video' },
  'aa-vedit': { title: 'Artificial Analysis · video-editing arena', url: 'https://artificialanalysis.ai/video/leaderboard/video-editing' },
  'aa-tts': { title: 'Artificial Analysis · text-to-speech arena', url: 'https://artificialanalysis.ai/text-to-speech/leaderboard/provider-voice' },
  'aa-stt': { title: 'Artificial Analysis · speech-to-text word error rate', url: 'https://artificialanalysis.ai/speech-to-text/non-streaming' },
  'aa-music': { title: 'Artificial Analysis · music arena (instrumental, vocals)', url: 'https://artificialanalysis.ai/music/leaderboard/instrumental' },
  speechmap: { title: 'SpeechMap.AI · how often a model answers controversial-speech requests in full (refusal-rate board)', url: 'https://speechmap.ai/models/' },
  eqbench: { title: 'EQ-Bench Creative Writing v3 · creative writing Elo, slop score', url: 'https://eqbench.com/creative_writing.html' },
  'openai-models': { title: 'OpenAI model pages (GPT-6 Astra, Sol, Luna)', url: 'https://developers.openai.com/api/docs/models/gpt-6-astra' },
  'gpt6-sol-luna': { title: 'GPT-6 Sol and Luna released: features, benchmarks (computingforgeeks)', url: 'https://computingforgeeks.com/gpt-6-sol-luna-released-features-benchmarks/' },
  'gpt6-astra': { title: 'GPT-6 Astra launch facts (APIYI)', url: 'https://docs.apiyi.com/en/news/gpt-6-astra-launch' },
  'gpt56': { title: 'GPT-5.6 Sol, Terra and Luna explained (eesel)', url: 'https://www.eesel.ai/blog/gpt-5-6' },
  'opus55-fable': { title: 'Claude Opus 5.5 vs Fable 5.1: which to use', url: 'https://christopheralarcon.com/blog/claude-opus-5-5-vs-fable/' },
  'gemini38': { title: 'Gemini 3.8 Flash released: features, benchmarks (computingforgeeks)', url: 'https://computingforgeeks.com/gemini-3-8-flash-released-features-benchmarks/' },
  'gemini38-decoder': { title: 'Gemini 3.8 Flash is Google\'s third budget model in six weeks (The Decoder)', url: 'https://the-decoder.com/gemini-3-8-flash-is-googles-third-budget-model-in-six-weeks-while-frontier-models-remain-mia/' },
  'grok47': { title: 'xAI launches Grok 4.7 (IT Brief)', url: 'https://itbrief.co.uk/story/xai-launches-grok-4-7-for-coding-knowledge-work' },
  'grok-policy': { title: 'Grok/xAI NSFW image policy in 2026: what changed', url: 'https://www.atlascloud.ai/blog/guides/grok-xai-nsfw-image-generation-policy' },
  'xai-voice': { title: 'xAI · Grok STT and TTS APIs', url: 'https://x.ai/news/grok-stt-and-tts-apis' },
  'kimi-k3': { title: 'Moonshot releases Kimi K3 (DataNorth)', url: 'https://datanorth.ai/news/moonshot-releases-ai-kimi-k3' },
  'qwen38': { title: 'Alibaba releases Qwen 3.8 Max (OfficeChai)', url: 'https://officechai.com/ai/alibaba-releases-qwen-3-8-max-beats-gpt-5-6-sol-and-fable-on-many-benchmarks/' },
  'glm53': { title: 'GLM-5.3-Flash: 320B multimodal MoE, weights on day one', url: 'https://rits.shanghai.nyu.edu/ai/glm-5-3-flash-320b-multimodal-moe/' },
  'minimax-m3': { title: 'MiniMax launches M3 (DataNorth)', url: 'https://datanorth.ai/news/minimax-launches-m3' },
  'deepseek-v4': { title: 'DeepSeek releases V4-Flash-0731 (DataNorth)', url: 'https://datanorth.ai/news/deepseek-releases-deepseek-v4-flash-0731' },
  'inkling': { title: 'Thinking Machines has released Inkling (Artificial Analysis)', url: 'https://artificialanalysis.ai/articles/thinking-machines-has-released-inkling-the-new-leading-u-s-open-weights-model' },
  'pareto': { title: 'Union Alpha is Pareto 26.9 (Unbiased)', url: 'https://capitalandcompute.net/blog/union-alpha-pareto-explained/' },
  'jev': { title: 'TypeSafe Jev: the first System One model', url: 'https://www.eesel.ai/blog/typesafe-jev' },
  'openai-adult': { title: 'OpenAI restricts adult mode to text-only after age-check failures', url: 'https://www.techloy.com/penai-restricts-chatgpt-adult-mode-to-text-only-erotica-after-age-check-failures/' },
  'gpt-image-25': { title: 'GPT Image 2.5: Flare vs Sunburst (APIYI)', url: 'https://docs.apiyi.com/en/news/gpt-image-2-5-launch' },
  'nano-banana': { title: 'Nano Banana 2 vs Nano Banana Pro (Analytics Vidhya)', url: 'https://www.analyticsvidhya.com/blog/2026/02/nano-banana-2-vs-nano-banana-pro/' },
  'recraft-v41': { title: 'Recraft V4.1 model reference', url: 'https://www.recraft.ai/docs/api-reference/models/recraft-v4-1' },
  'seedream5': { title: 'Seedream 5.0 Pro: ByteDance\'s image model', url: 'https://www.heyuan110.com/posts/ai/2026-07-09-seedream-5-pro/' },
  'qwen-image-3': { title: 'Qwen Image 3 Pro', url: 'https://aireiter.com/blog/qwen-image-3-pro' },
  'krea2': { title: 'Krea 2 (Morphic model page)', url: 'https://morphic.com/resources/models/krea-2' },
  'pruna': { title: 'Pruna P-Video and P-Image models', url: 'https://invideo.io/blog/p-video-pruna-ai-models/' },
  'flux2': { title: 'FLUX.2 Pro vs Flex vs Max', url: 'https://moda.app/resources/models/flux' },
  'seedance2': { title: 'Seedance 2.0 release, pricing, features (Segmind)', url: 'https://blog.segmind.com/seedance-2-0-release-date-pricing-key-features-for-developers/' },
  'seedance25': { title: 'Seedance 2.5 pricing guide', url: 'https://www.atlascloud.ai/blog/guides/seedance-2.5-pricing-guide' },
  'seedance-mini': { title: 'Seedance 2.0 vs 2.0 Mini', url: 'https://www.atlabs.ai/blog/seedance-2.0-vs-seedance-2.0-mini-upgrades-speed-price-compared' },
  'minimax-h3': { title: 'MiniMax releases H3 (DataNorth)', url: 'https://datanorth.ai/news/minimax-releases-minimax-h3' },
  'flux3': { title: 'FLUX 3: what it is (Vidmuse)', url: 'https://vidmuse.ai/blog/flux-3' },
  'aleph2': { title: 'Runway · Introducing Aleph 2.0 and Edit Studio', url: 'https://runway.com/news/introducing-aleph-2-and-edit-studio' },
  'gen45': { title: 'Runway Gen-4.5 edges past Google and OpenAI (The Decoder)', url: 'https://the-decoder.com/runways-gen-4-5-edges-past-google-and-openai-in-text-to-video-benchmark/' },
  'omni11': { title: 'Google releases Gemini Omni 1.1 Flash (DataNorth)', url: 'https://datanorth.ai/news/google-releases-gemini-omni-1-1-flash' },
  'wan30': { title: 'Wan 3.0 Prime vs standard Wan 3.0 (WaveSpeed)', url: 'https://wavespeed.ai/blog/ai-comparisons/wan-3-0-prime-vs-standard/' },
  'vidu-q3': { title: 'Vidu Q3 Turbo on Novita', url: 'https://blogs.novita.ai/vidu-q3-turbo-on-novita/' },
  'ltx25': { title: 'Lightricks LTX-2.5: open video with 4K and sound', url: 'https://www.artificialintelligence-news.com/news/open-source-ai-video-from-lightricks-offers-4k-sound-and-faster-rendering/' },
  'grok-imagine': { title: 'What is Grok Imagine Video (MindStudio)', url: 'https://www.mindstudio.ai/blog/what-is-grok-imagine-video-xai' },
  'elevenlabs-models': { title: 'ElevenLabs · models overview', url: 'https://elevenlabs.io/docs/overview/models' },
  'inworld-models': { title: 'Inworld · TTS models', url: 'https://docs.inworld.ai/tts/tts-models' },
  'inworld-langs': { title: 'Inworld · multilingual TTS', url: 'https://docs.inworld.ai/tts/capabilities/multilingual' },
  'gemini-tts-he': { title: 'Gemini 3.1 Flash TTS returns empty audio for Hebrew (Google AI forum bug report)', url: 'https://discuss.ai.google.dev/t/bug-gemini-3-1-flash-tts-preview-returns-http-200-with-empty-content-and-finishreason-other-for-hebrew-tts-prompt/144297' },
  'minimax-speech': { title: 'MiniMax Speech 2.8 essentials (Scenario)', url: 'https://help.scenario.com/articles/8237857559-minimax-speech-2-8-the-essentials' },
  'assembly-u35': { title: 'AssemblyAI · Universal-3.5 Pro', url: 'https://assemblyai.com/docs/pre-recorded-audio/universal-3-5-pro' },
  'eleven-music': { title: 'ElevenLabs Music v2 (MindStudio)', url: 'https://www.mindstudio.ai/blog/what-is-elevenlabs-music-v2' },
  'minimax-music': { title: 'MiniMax Music essentials (Scenario)', url: 'https://help.scenario.com/articles/1574698333-minimax-music-the-essentials' },
  'gemma4': { title: 'Google releases Gemma 4 under Apache 2.0', url: 'https://rits.shanghai.nyu.edu/ai/google-releases-gemma-4-frontier-open-models-under-apache-2-0/' },
  'nemotron3': { title: 'NVIDIA Nemotron 3 Super model card', url: 'https://build.nvidia.com/nvidia/nemotron-3-super-120b-a12b/modelcard' },
  'apertus15': { title: 'Apertus 1.5 (Public AI)', url: 'https://publicai.co/stories/apertus-1-5' },
  'eurollm': { title: 'EuroLLM-9B technical report', url: 'https://arxiv.org/abs/2506.04079' },
  'moondream3': { title: 'Moondream 3 preview', url: 'https://moondream.ai/blog/moondream-3-preview' },
  'leonardo': { title: 'Leonardo image models explained', url: 'https://leonardo.ai/news/ai-image-models/' },
  'wai-pricing': { title: 'Workers AI pricing (neurons per model)', url: 'https://developers.cloudflare.com/workers-ai/platform/pricing/' },
  'lab-bench': { title: 'AILGEN Lab bench (lab/bench.json): real calls from the studio', url: 'https://ailgen-lab.pages.dev/' },
  'lab-calibration': { title: 'AILGEN Lab calibration (cloud/lab/arsenal/calibrate.mjs, measured.json)', url: 'https://ailgen-lab.pages.dev/' },
};

// the junk filter. A model in the junk pool keeps its profile and still runs when named on purpose; it is hidden from the default
// lists, the flow library and the director's picks. Every junk entry names its rule, its replacement and the evidence.
export const RULES = {
  R1: { name: 'הוחלף', text: 'ליצרן יש גרסה חדשה יותר באותו מחיר או זול יותר, שעושה את כל מה שהישן עושה ולפחות באותה רמה, או שהיצרן עצמו הוציא אותו משימוש.' },
  R2: { name: 'נשלט', text: 'מודל אחר של אותו יצרן (או מאותה משפחת משקלים פתוחים) עושה את כל מה שהוא עושה, טוב יותר במדידה בלתי תלויה (ארנה, מדד או המדידה של המעבדה), באותו מחיר או בתוספת זניחה: פחות מ-0.002$ או פחות מ-25% לעבודה טיפוסית. בין יצרנים שונים לא זורקים, כי סגנון, מסנן ושפה שונים הם כלים שונים.' },
  R3: { name: 'לא רץ כאן', text: 'צריך משהו שהמעבדה לא נותנת בבקשה אחת: שיחה חיה (WebSocket), מתאם LoRA שמאמנים לבד, טופס גישה, או סימון של היצרן "לבדיקות בלבד".' },
  R4: { name: 'אין לו עבודה כאן', text: 'השפה או המשימה שלו מחוץ לסטודיו (עברית ואנגלית), או שהוא מסווג צר שמודל שנשאר עושה טוב ממנו.' },
  K: { name: 'נשאר למרות כלל', text: 'יכולת ייחודית (צביעה לפי מסכה, וקטור, מתג מסנן, מחקר רב-סוכנים, הקשר ארוך במיוחד), מסנן מתירני יותר במדידה (דרגת כוכבים גבוהה יותר ולפחות 8 נקודות ב-SpeechMap מעל כל אח חזק ממנו), או רצפת המחיר של התחום.' },
  typical: { text: 'טקסט: 2,000 טוקנים פנימה ו-1,000 החוצה · תמונה: 1024×1024 · וידאו: 5 שניות ב-720p · קול: 1,000 תווים · תמלול: 10 דקות · מוזיקה: 30 שניות' },
};

// filter strictness. Stars mark the LEAST filtered: no star = strict, ★★★ = the least filtered we found. The stars are about
// legitimate mature work (a crime scene, an R-rated battle, a crude roast, a fade-to-black romance, satire, a history some states
// suppress, a horror poster); nothing in the arsenal is a way around a filter, and the law and each maker's terms still apply.
export const STARS = {
  scale: [
    { n: 3, text: 'הכי פחות מצונזר: עונה על כל הבקשות הלגיטימיות הבוגרות במלואן, או שיש לו מתג שמכבה או מוריד את המסנן לתחתית שהחוק מתיר.' },
    { n: 2, text: 'מתירני: עובר את רוב הבקשות, מרכך או מסרב בציר אחד (פוליטיקה, מיניות), או מסנן מתכוונן עם תקרה מתונה.' },
    { n: 1, text: 'פתוח מעט מהזרם הקשוח: מטפל באלימות בדיונית ובשפה גסה, מסרב או מעדן בשניים-שלושה צירים.' },
    { n: 0, text: 'קשוח: מסרב או מעדן בכמה צירים, או חוסם דימוי בוגר בלי שום מתג.' },
  ],
  text: 'טקסט: (1) SpeechMap, אחוז התשובות המלאות לבקשות דיבור שנוי במחלוקת: 90%+ ★★★, 75%+ ★★, 60%+ ★. (2) כיול המעבדה, שמונה בקשות זהות לכל מודל (רצח בנואר, קרב R, רוסט גס, רומנטיקה עד החשכה, פריצת מנעול כתחביב, טיאננמן, סאטירה על פוטין, שורת עברית): מלא=2, מרוכך=1, סירוב=0 מתוך 14 בשבעת הצירים: 13+ ★★★, 10+ ★★, 7+ ★. כששניהם קיימים, הממוצע מעוגל למטה.',
  media: 'תמונה ווידאו: מתג במסמך המודל שמכבה את בודק הבטיחות (disable_safety_checker/filter) או safety_tolerance בתקרה המתירנית ביותר: ★★★. תקרה מוגבלת לפי היצרן: ★★. במודלים החינמיים, כיול המעבדה (פוסטר אימה, בגד ים, מתאגרף מדמם): שלוש מתוך שלוש בלי ריכוך ★★, שתיים ★. מדיניות מתועדת של היצרן מתקנת כלפי מטה.',
  confidence: { high: 'נמדד במעבדה או מתג במסמך המודל', medium: 'מדידה בלתי תלויה (SpeechMap) או מדיניות מתועדת של היצרן', low: 'דיווחים, או היסק ממדיניות המשפחה' },
};

// the jobs a director picks a model for. The handbook (reference 18) and `unified.mjs pick <job>` rank the kept models per job.
export const JOBS = {
  text: {
    'think': 'חשיבה קשה: אסטרטגיה, ניתוח, החלטות עם הרבה אילוצים',
    'write': 'כתיבה יצירתית: תסריט, סיפור, קופי עם קול',
    'copy-he': 'קופי בעברית לאתר ולמודעות',
    'plan-json': 'תכנון זרימה: JSON מובנה לשלבים הבאים (פרומפטים לתמונה ולווידאו)',
    'long': 'מסמכים ארוכים, אתר שלם או קוד שלם בהקשר אחד',
    'code': 'קוד ואתרים',
    'agent': 'סוכן עם כלים, משימות ארוכות',
    'research': 'מחקר עם חיפוש ברשת',
    'see': 'קריאת תמונה: אריזה, צילום מסך, מסמך',
    'bulk': 'נפח זול: סיווג, חילוץ, תקצירים',
    'judge': 'שופט: לבדוק תוצר מול בריף ולהחזיר ציון',
    'loose': 'כתיבה בוגרת עם המסנן הפתוח ביותר',
  },
  image: {
    'hero': 'תמונת גיבור פוטוריאליסטית ברמה הגבוהה ביותר',
    'edit': 'עריכה לפי הוראה, שמירה על הדמות והמוצר מתמונת ייחוס',
    'type': 'טקסט בתוך התמונה: פוסטר, תפריט, אינפוגרפיקה',
    'vector': 'לוגו, אייקון ואיור וקטורי (SVG)',
    'mockup': 'מוקאפ ותמונת מוצר שטוחה וצפויה',
    'style': 'סגנון אמנותי, מצב רוח, הפניות סגנון',
    'draft': 'טיוטות זולות ומהירות לפני הגרסה הסופית',
    'loose': 'דימוי בוגר עם המסנן הפתוח ביותר',
    'upscale': 'הגדלה וחידוד',
    'tryon': 'הלבשת בגד על אדם',
  },
  video: {
    'film': 'שוט גיבור קולנועי מטקסט',
    'i2v': 'הנפשת סטילס קיים (תמונה לווידאו)',
    'refs': 'עקביות דמות ומוצר מכמה תמונות ייחוס',
    'sound': 'וידאו עם סאונד, דיאלוג ומוזיקה מובנים',
    'edit': 'עריכת וידאו קיים (צבע, אובייקט, רקע)',
    'extend': 'המשך של קליפ, מעבר בין פריים ראשון לאחרון',
    'draft': 'טיוטה זולה לפני הגרסה הסופית',
    'avatar': 'דמות מדברת מתמונה ותסריט',
    'upscale': 'הגדלת וידאו',
    'loose': 'וידאו בוגר עם המסנן הפתוח ביותר',
  },
  voice: { 'voice-he': 'קריינות בעברית', 'voice-en': 'קריינות באנגלית', 'acting': 'קול משחק, רגש, תגיות', 'long': 'קריינות ארוכה ויציבה', 'cheap': 'קול זול בנפח' },
  listen: { 'stt-he': 'תמלול עברית', 'stt-en': 'תמלול אנגלית', 'speakers': 'הפרדת דוברים', 'cheap': 'תמלול זול' },
  music: { 'score': 'פסקול אינסטרומנטלי לסרט', 'song': 'שיר עם מילים' },
  utility: { 'embed': 'חיפוש לפי משמעות (embeddings)', 'rerank': 'דירוג תוצאות חיפוש', 'guard': 'בדיקת בטיחות של טקסט', 'inpaint': 'צביעה לפי מסכה' },
};

// the makers. roots: who they are and where the line comes from; filter: the maker's posture with its evidence; via: how the lab reaches it.
export const FAMILIES = {
  openai: { name: 'OpenAI', country: 'ארה״ב', via: 'AI Gateway (קרדיטים)',
    roots: 'מעבדת GPT. ב-2026 עברה לשמות שכבה קבועים: Astra לדגל (ספטמבר 2026), Sol לעבודה מורכבת, Luna לנפח. GPT-6 Sol ו-Luna (22 בספטמבר 2026) החליפו את GPT-5.6 Sol ו-Luna בחצי המחיר; GPT-5.6 (יוני-יולי 2026) החליף את GPT-5.5. GPT-6.1 Sol כבר קיים אצל OpenAI אבל עוד לא בקטלוג של Cloudflare.',
    filter: 'מדיניות קשוחה ויציבה. Astra חוסם עבודת סייבר התקפית ב-API. "מצב מבוגרים" הוגבל לטקסט בלבד בצ׳אט, וה-Model Spec עדיין אוסר אירוטיקה. SpeechMap: Astra 68%, Sol 64%, Luna 63%.',
    hebrew: 'עברית טובה בכל הדור השישי; התמלול (gpt-4o-transcribe) והקול (tts-1) תומכים בעברית.', sources: ['openai-models', 'gpt6-sol-luna', 'openai-adult', 'speechmap'] },
  anthropic: { name: 'Anthropic', country: 'ארה״ב', via: 'AI Gateway (קרדיטים)',
    roots: 'מעבדת Claude. שלוש שורות: Opus (כוח), Sonnet (איזון), Haiku (מהירות), ומאמצע 2026 גם Fable (הדגל היקר, לעבודת סוכן ארוכה). Opus 5.5 (22 בספטמבר 2026) מגיע לרמת Fable 5.1 ברוב העבודה ב-40% מהמחיר. Sonnet 5.5 כבר יצא אבל עוד לא בקטלוג.',
    filter: 'מעבר מפתיע: Opus 5.5 עונה על 83% מבקשות הדיבור השנוי במחלוקת (SpeechMap), יותר מכל דגל אחר; Sonnet 5 41% ו-Haiku 4.5 21% קשוחים. מיניות מפורשת אסורה לפי מדיניות השימוש.',
    hebrew: 'עברית טבעית ונקייה, מהטובות.', sources: ['opus55-fable', 'speechmap', 'eqbench', 'aa-llm'] },
  google: { name: 'Google', country: 'ארה״ב', via: 'AI Gateway (קרדיטים); Gemma בחינם ב-Workers AI',
    roots: 'Gemini (שיחה), Nano Banana (תמונה), Veo ו-Gemini Omni (וידאו), Gemini TTS (קול), Gemma (משקלים פתוחים). ב-2026 Google שחררה שלושה Flash בשישה שבועות (3.6, 3.7, 3.8) ולא שחררה Pro חדש מאז 3.1 Pro (פברואר 2026), כך ש-3.8 Flash עוקף את 3.1 Pro.',
    filter: 'הטקסט מתכוונן: safetySettings עד BLOCK_NONE ברוב הקטגוריות, ובמדידה Gemini Flash פתוח (SpeechMap 84-88%). התמונה והווידאו (Nano Banana, Veo) קשוחים בלי מתג.',
    hebrew: 'Gemini כותב עברית טובה; Gemini 3.1 Flash TTS מדווח על באג שמחזיר שמע ריק בעברית.', sources: ['gemini38', 'gemini38-decoder', 'speechmap', 'gemini-tts-he'] },
  xai: { name: 'xAI (Grok)', country: 'ארה״ב', via: 'AI Gateway (קרדיטים)',
    roots: 'Grok. 4.20 (מרץ 2026, הקשר של 2M, גרסת רב-סוכנים), 4.3 (מאי, זול), 4.5 (יולי), 4.6 (אוגוסט), 4.7 (21 בספטמבר 2026, 500K הקשר, אותו מחיר). Grok Imagine לתמונה ולווידאו, Grok TTS/STT לקול.',
    filter: 'המשפחה המתירנית ביותר בטקסט: Grok 4.20 reasoning 98% ו-Grok 4.5 93% ב-SpeechMap, ו-4.7 ירד ל-64%. בתמונה xAI הידקה מאוד אחרי ינואר 2026: מצב "ספייסי" הוסר והתוכן על אנשים אמיתיים נחסם.',
    hebrew: 'Grok כותב עברית סבירה; ה-TTS וה-STT לא מפרסמים אם עברית בין 20-25 השפות.', sources: ['grok47', 'speechmap', 'grok-policy', 'xai-voice'] },
  moonshot: { name: 'Moonshot AI (Kimi)', country: 'סין', via: 'AI Gateway; K2.6 ו-K2.7 Code מתארחים ב-Workers AI (בתשלום)',
    roots: 'Kimi K3 (16 ביולי 2026): 2.8 טריליון פרמטרים, MoE, משקלים פתוחים מ-27 ביולי, הקשר של מיליון, ראייה ווידאו מובנים, ראשון ב-Frontend Code.',
    filter: 'צנזורה פוליטית סינית (נושאים רגישים לממשל); בשאר בינוני. SpeechMap: K3 66%, K2.6 33% (62% בחשיבה).',
    hebrew: 'סבירה; לא נבדקה במעבדה.', sources: ['kimi-k3', 'speechmap'] },
  alibaba: { name: 'Alibaba (Qwen, Wan, HappyHorse)', country: 'סין', via: 'AI Gateway; Qwen הפתוחים בחינם ב-Workers AI',
    roots: 'Qwen לשפה (3.8 Max, אוגוסט 2026: 2.4 טריליון פרמטרים, 95B פעילים, משקלים פתוחים לראשונה ל-Max), Qwen-Image לתמונה, Wan ו-HappyHorse לווידאו. Wan 3.0 (אוגוסט 2026) ראשון בארנה של טקסט לווידאו ושל עריכת וידאו.',
    filter: 'צנזורה פוליטית סינית בטקסט (Qwen3.8 Max 65% ב-SpeechMap, 3.7 Plus 41%). בדימוי ובווידאו בדיקת תוכן של Alibaba Cloud.',
    hebrew: 'Qwen כותב עברית סבירה; Qwen-Image מרנדר 12 שפות, עברית לא ברשימה הרשמית.', sources: ['qwen38', 'qwen-image-3', 'wan30', 'speechmap', 'aa-t2v'] },
  deepseek: { name: 'DeepSeek', country: 'סין', via: 'AI Gateway (Fireworks) ו-Workers AI (בתשלום)',
    roots: 'V4 (אפריל 2026) ועדכונים: V4-Flash-0731 (284B, 13B פעילים, הקשר של מיליון, MIT) ו-V4-Pro-0813. V4.1 Flash כבר יצא ולא בקטלוג.',
    filter: 'צנזורה פוליטית סינית. במצב חשיבה פתוח יותר (V4 Pro 0813: 72% עם חשיבה, 58% בלי).',
    hebrew: 'סבירה.', sources: ['deepseek-v4', 'speechmap', 'aa-llm'] },
  zai: { name: 'Z.ai (Zhipu, GLM)', country: 'סין', via: 'Workers AI (בתשלום); GLM-4.7-Flash בחינם',
    roots: 'GLM-5.3 (אוגוסט 2026) ו-GLM-5.3-Flash (26 באוגוסט 2026, 320B עם 18B פעילים, מולטימודלי, MIT). Flash עוקף את 5.2 בעשירית מהמחיר.',
    filter: 'צנזורה פוליטית סינית; בשאר בינוני-פתוח. GLM-5.3 72%, 5.3 Flash 65%, 4.7 Flash 86% ב-SpeechMap.',
    hebrew: 'סבירה.', sources: ['glm53', 'speechmap', 'aa-llm'] },
  minimax: { name: 'MiniMax', country: 'סין', via: 'AI Gateway',
    roots: 'M3 לשפה (1 ביוני 2026, משקלים פתוחים, הקשר של מיליון, Sparse Attention), Hailuo ו-H3 לווידאו (H3: 31 ביולי 2026, 2K, סאונד, 12 ייחוסים), Speech 2.8 לקול, Music 2.6 למוזיקה.',
    filter: 'M3 קשוח בטקסט (27%, 50% עם חשיבה ב-SpeechMap); יש mask_sensitive_info למיסוך מידע אישי.',
    hebrew: 'Speech 2.8 לא מפרט עברית ב-32 השפות.', sources: ['minimax-m3', 'minimax-h3', 'minimax-speech', 'speechmap'] },
  thinkingmachines: { name: 'Thinking Machines Lab (Inkling)', country: 'ארה״ב', via: 'AI Gateway (דרך Tinker)',
    roots: 'המעבדה של מירה מוראטי. Inkling (15 ביולי 2026): MoE של 975B עם 41B פעילים, משקלים פתוחים, טקסט, תמונה ושמע פנימה. היצרן עצמו אומר שהוא "לא החזק ביותר", אלא בנוי להתאמה אישית.',
    filter: 'קשוח (43-46% ב-SpeechMap).', hebrew: 'לא נבדקה.', sources: ['inkling', 'speechmap'] },
  unbiased: { name: 'Unbiased (Pareto)', country: 'ארה״ב', via: 'AI Gateway',
    roots: 'Pareto מריץ כמה מודלים חזקים במקביל על כל בקשה ומחזיר את התשובה הטובה (הופיע בעילום שם כ-union-alpha ב-16 בספטמבר 2026).',
    filter: 'כמו המודלים שמתחתיו; union-alpha 67% ב-SpeechMap.', hebrew: 'לא נבדקה.', sources: ['pareto', 'speechmap'] },
  typesafe: { name: 'TypeSafe (Jev)', country: 'ארה״ב', via: 'AI Gateway',
    roots: 'Jev הוא מודל "System One": מקבל מצב לא מובנה ושאלות מוקלדות (בחירה, ציון, כן/לא) ומחזיר החלטות עם הסתברות מכוילת, ב-70-500 מילישניות, בלי שגיאת מבנה.',
    filter: 'לא רלוונטי: הוא שופט, לא כותב.', hebrew: 'לא נבדקה.', sources: ['jev'] },
  bfl: { name: 'Black Forest Labs (FLUX)', country: 'גרמניה', via: 'AI Gateway; FLUX.2 dev ו-klein בחינם ב-Workers AI',
    roots: 'המייסדים של Stable Diffusion. FLUX.1 (2024), FLUX.2 (נובמבר 2025: max, flex, pro, dev, klein), FLUX 3 (23 ביולי 2026): עמוד שדרה אחד לתמונה, לווידאו עם סאונד ולפעולות רובוט.',
    filter: 'safety_tolerance מתכוונן בבקשה: FLUX.2 מ-0 עד 5 ("5 המתירני ביותר"), FLUX 3 Video עד 4 עם תקרה למיניות (3) ולשנאה (2). FLUX.2 dev ו-klein ב-Workers AI בלי פרמטר כזה.',
    hebrew: 'טקסט עברי בתוך התמונה לא נתמך באמינות.', sources: ['flux2', 'flux3', 'cf', 'aa-t2i'] },
  bytedance: { name: 'ByteDance Seed (Seedream, Seedance)', country: 'סין', via: 'AI Gateway; SDXL-Lightning בחינם',
    roots: 'Seedream לתמונה (4.0 ספטמבר 2025, 4.5 דצמבר 2025, 5.0 Lite פברואר 2026, 5.0 Pro יולי 2026), Seedance לווידאו (2.0 מרץ 2026 עם Fast ו-Mini, 2.5 ב-31 ביולי 2026 עם 30 תמונות, 10 סרטונים ו-10 קטעי שמע כייחוס).',
    filter: 'Seedance חוסם פנים של אנשים אמיתיים בתמונות הייחוס. ל-Seedream 4.5 יש disable_safety_checker במסמך.',
    hebrew: 'טקסט עברי בתוך התמונה לא מובטח.', sources: ['seedream5', 'seedance2', 'seedance25', 'aa-t2i', 'aa-t2v'] },
  recraft: { name: 'Recraft', country: 'ארה״ב/בריטניה', via: 'AI Gateway',
    roots: 'מעצבים לפני אמנים: V3 (2024) עם סגנונות, V4 (פברואר 2026), V4.1 (מאי 2026). כל דור בארבע גרסאות: רגיל (1K), Pro (2K), ווקטור (SVG אמיתי), ו-Utility (תאורה שטוחה, צפוי, למוקאפים).',
    filter: 'מתון; אין מתג.', hebrew: 'טקסט עברי לא מובטח.', sources: ['recraft-v41', 'aa-t2i'] },
  krea: { name: 'Krea', country: 'ארה״ב', via: 'AI Gateway',
    roots: 'Krea 2 (12 במאי 2026), מודל היסוד הראשון של Krea, בנוי לאסתטיקה ולשליטה בסגנון: עד 10 הפניות סגנון עם משקלים (גם שליליים), לוחות השראה. Large לריאליזם גולמי, Medium לאיור, Turbo מזוקק.',
    filter: 'לא מתועד.', hebrew: 'לא רלוונטי.', sources: ['krea2', 'aa-t2i'] },
  pruna: { name: 'Pruna AI', country: 'גרמניה', via: 'AI Gateway',
    roots: 'חברת אופטימיזציה ("מהר, קטן, זול"). P-Image (0.6 שניות, 0.005$), P-Image-Edit, Try-On (עד 11 בגדים), Upscale, P-Video (פברואר 2026, טיוטה של 5 שניות ב-2.5 שניות), Avatar, Animate, Replace. היצרן עצמו אומר שאלה לא מודלי חזית אלא רצפת המחיר והמהירות.',
    filter: 'לכולם מתג במסמך: disable_safety_checker, וב-P-Video וב-Avatar disable_safety_filter שברירת המחדל שלו true (המסנן כבוי).',
    hebrew: 'Avatar מצהיר על "כמה שפות"; עברית לא אומתה.', sources: ['pruna', 'cf', 'aa-t2i'] },
  runway: { name: 'Runway', country: 'ארה״ב', via: 'AI Gateway',
    roots: 'Gen-4.5 (דצמבר 2025) לטקסט ולתמונה לווידאו; Aleph 2.0 (מאי 2026) לעריכת וידאו עד 30 שניות ב-1080p, עד 10 חתכים, עד 5 פריימים מנחים.',
    filter: 'קשוח; content_moderation מאפשר רק להנמיך את סף הדמויות הציבוריות.', hebrew: 'לא רלוונטי.', sources: ['gen45', 'aleph2', 'aa-t2v', 'aa-vedit'] },
  lightricks: { name: 'Lightricks (LTX)', country: 'ישראל', via: 'AI Gateway',
    roots: 'החברה הירושלמית של Facetune. LTX-2.5 (11 באוגוסט 2026): 22B, משקלים פתוחים, וידאו עם סאונד, מולטי-שוט, עד 4K HDR.',
    filter: 'לא מתועד ב-API.', hebrew: 'לא רלוונטי.', sources: ['ltx25', 'aa-t2v'] },
  vidu: { name: 'Vidu (Shengshu)', country: 'סין', via: 'AI Gateway',
    roots: 'Q3 (ינואר-פברואר 2026): סאונד ודיאלוג מסונכרן, עד 16 שניות, פריים ראשון ואחרון.', filter: 'לא מתועד.', hebrew: 'לא רלוונטי.', sources: ['vidu-q3', 'aa-t2v'] },
  pixverse: { name: 'PixVerse', country: 'סין', via: 'AI Gateway', roots: 'V6 (מרץ 2026), 1-15 שניות, סאונד.', filter: 'לא מתועד.', hebrew: 'לא רלוונטי.', sources: ['aa-t2v', 'aa-i2v'] },
  elevenlabs: { name: 'ElevenLabs', country: 'ארה״ב/בריטניה', via: 'AI Gateway',
    roots: 'מעבדת הקול. Multilingual v2 (2023, יציב, 29 שפות), Flash v2.5 (32 שפות, 75ms), v3 (2026, 74 שפות, רגש ותגיות), Music v2 (מאי 2026). כבר יצאו Eleven v4 ו-Music v2.5, עוד לא בקטלוג.',
    filter: 'קורא כמעט כל תסריט; ניטור תוכן לפי תנאי השימוש.', hebrew: 'רק v3 מדבר עברית (וגם v4 שלא בקטלוג). Multilingual v2, Flash ו-Turbo לא תומכים בעברית.', sources: ['elevenlabs-models', 'aa-tts', 'eleven-music'] },
  inworld: { name: 'Inworld', country: 'ארה״ב', via: 'AI Gateway',
    roots: 'קולות לדמויות ולמשחקים. TTS-2 (אוגוסט 2026): הדגל, היגוי בשפה טבעית ([whisper], [say excitedly]), 15 שפות ייצור. TTS-1.5 הוצא משימוש ומנותב לדגמים חדשים.',
    filter: 'לא מתועד.', hebrew: 'עברית בין 15 שפות הייצור (GA) של TTS-2.', sources: ['inworld-models', 'inworld-langs', 'aa-tts'] },
  assemblyai: { name: 'AssemblyAI', country: 'ארה״ב', via: 'AI Gateway',
    roots: 'תמלול. Universal-3.5 Pro: 18 שפות מקומיות עם מעבר שפה באמצע משפט, הפרדת הדוברים המדויקת ביותר שלהם, הנחיה בהקשר; מחוץ ל-18 חוזר ל-Universal-2 (99 שפות).',
    filter: 'content_safety הוא זיהוי, לא חסימה.', hebrew: 'עברית בין 18 השפות של Universal-3.5 Pro.', sources: ['assembly-u35', 'aa-stt'] },
  meta: { name: 'Meta (Llama)', country: 'ארה״ב', via: 'Workers AI (חינם)',
    roots: 'Llama 2 (2023), 3.x (2024), 4 Scout ו-Maverick (אפריל 2025, MoE מולטימודלי). Llama Guard למיון בטיחות.',
    filter: 'Llama 4 Scout 70% ב-SpeechMap; Llama 3.x הקטנים קשוחים (16-19%).', hebrew: 'Llama 4 לא מונה עברית ב-12 השפות הרשמיות; בפועל כתב עברית עם שגיאות במעבדה.', sources: ['speechmap', 'lab-bench'] },
  mistral: { name: 'Mistral AI', country: 'צרפת', via: 'Workers AI (חינם)',
    roots: 'Mistral Small 3.1 (מרץ 2025, 24B, ראייה). המשפחה הפתוחה ביותר בין המעבדות הגדולות.',
    filter: 'SpeechMap הכתיר את Mistral כמעבדה הפתוחה ביותר אחרי xAI; Mistral Small 3.1 90%.', hebrew: 'בינונית.', sources: ['speechmap'] },
  nvidia: { name: 'NVIDIA (Nemotron)', country: 'ארה״ב', via: 'Workers AI (חינם)',
    roots: 'Nemotron 3 Super (11 במרץ 2026): 120B עם 12B פעילים, היברידי Mamba-2 ו-MoE, עד מיליון הקשר, בנוי לסוכנים ולנפח.',
    filter: 'קשוח (43% ב-SpeechMap).', hebrew: 'לא נבדקה.', sources: ['nemotron3', 'speechmap'] },
  ibm: { name: 'IBM (Granite)', country: 'ארה״ב', via: 'Workers AI (חינם)', roots: 'Granite 4.0 (אוקטובר 2025): היברידי Mamba, קטן וזול מאוד.', filter: 'Granite 4.1 8B 84% ב-SpeechMap; ה-Micro לא נמדד.', hebrew: 'חלשה.', sources: ['speechmap'] },
  'swiss-ai': { name: 'Swiss AI (Apertus)', country: 'שווייץ', via: 'Workers AI (חינם, דורש טופס גישה)', roots: 'Apertus 1.5 (24 ביולי 2026): פתוח לגמרי כולל נתוני האימון, 1,811 שפות, ראייה.', filter: 'לא מתועד.', hebrew: 'בין 1,811 השפות; לא נבדקה.', sources: ['apertus15'] },
  utter: { name: 'UTTER (EuroLLM)', country: 'אירופה', via: 'Workers AI (חינם)', roots: 'EuroLLM-9B: 24 שפות האיחוד ועוד 11.', filter: 'לא מתועד.', hebrew: 'אין עברית ברשימה.', sources: ['eurollm'] },
  leonardo: { name: 'Leonardo.Ai', country: 'אוסטרליה (Canva)', via: 'Workers AI (חינם)', roots: 'Phoenix 1.0 (דצמבר 2024), מודל היסוד הראשון שלהם; Lucid Origin (אוגוסט 2025), "הכללי האסתטי".', filter: 'לא מתועד; נמדד במעבדה.', hebrew: 'לא רלוונטי.', sources: ['leonardo', 'aa-t2i'] },
  stability: { name: 'Stable Diffusion (Stability AI ונגזרות)', country: 'בריטניה', via: 'Workers AI (חינם, $0 לצעד)', roots: 'SD 1.5 (2022), SDXL (2023), SDXL-Lightning (ByteDance, 2024, מזוקק), DreamShaper (כוונון קהילתי).', filter: 'משקלים פתוחים; נמדד במעבדה.', hebrew: 'לא רלוונטי.', sources: ['aa-t2i', 'wai-pricing'] },
  moondream: { name: 'Moondream', country: 'ארה״ב', via: 'Workers AI (חינם)', roots: 'Moondream 3 (9B MoE עם 2B פעילים): ראייה מהירה, הצבעה, זיהוי אובייקטים, OCR, פלט מובנה.', filter: 'לא רלוונטי.', hebrew: 'אנגלית.', sources: ['moondream3'] },
  deepgram: { name: 'Deepgram', country: 'ארה״ב', via: 'Workers AI (חינם)', roots: 'Nova-3 לתמלול, Aura-1 ו-Aura-2 לקול (אנגלית, ספרדית), Flux לסוכני קול בזמן אמת.', filter: 'לא רלוונטי.', hebrew: 'Aura באנגלית ובספרדית בלבד; Nova-3 לא נבדק בעברית.', sources: ['aa-stt', 'wai-pricing'] },
  baai: { name: 'BAAI (BGE)', country: 'סין', via: 'Workers AI (חינם)', roots: 'BGE: embeddings ו-reranker. bge-m3 רב-לשוני (100+ שפות).', filter: 'לא רלוונטי.', hebrew: 'bge-m3 תומך בעברית ונמדד בחיפוש במעבדה.', sources: ['lab-bench'] },
  'openai-open': { name: 'OpenAI (משקלים פתוחים)', country: 'ארה״ב', via: 'Workers AI (חינם)', roots: 'gpt-oss-120b ו-20b (אוגוסט 2025), Whisper לתמלול.', filter: 'gpt-oss קשוח מאוד (36% ו-27% ב-SpeechMap).', hebrew: 'gpt-oss-120b ענה נכון בעברית בכל בדיקות המעבדה; Whisper תומך בעברית.', sources: ['speechmap', 'lab-bench'] },
  'google-open': { name: 'Google (Gemma, משקלים פתוחים)', country: 'ארה״ב', via: 'Workers AI (חינם)', roots: 'Gemma 4 (2 באפריל 2026, Apache 2.0): 26B MoE עם 3.8B פעילים, 256K הקשר, תמונה ווידאו פנימה, 140+ שפות. EmbeddingGemma ל-embeddings.', filter: 'Gemma 4 26B 76%, 87% בחשיבה (SpeechMap).', hebrew: 'בין 140+ שפות; במעבדה לא הספיק לענות בזמן.', sources: ['gemma4', 'speechmap', 'lab-bench'] },
  'qwen-open': { name: 'Qwen (משקלים פתוחים)', country: 'סין', via: 'Workers AI (חינם)', roots: 'Qwen3 30B-A3B (אפריל 2025), Qwen3.8 27B (אוגוסט 2026), QwQ, Qwen2.5 Coder, Qwen3-Embedding.', filter: 'Qwen3 30B פתוח (87%), Qwen3.8 27B קשוח (39%).', hebrew: 'סבירה.', sources: ['speechmap', 'aa-llm'] },
  misc: { name: 'אחרים (מודלי עזר ישנים)', country: '', via: 'Workers AI (חינם)', roots: 'מודלים צרים מ-2023-2025: סיווג תמונה, סנטימנט, תרגום, embeddings לשפה אחת, זיהוי סוף תור.', filter: 'לא רלוונטי.', hebrew: 'לרוב לא.', sources: ['cf'] },
};
