// AILGEN Lab · the arsenal's curated knowledge, part 3: image models. refs: t2i / edit = the Artificial Analysis arena rows.
// Tiers for images: top = text-to-image arena Elo 1080+, mid = 1000-1080, low = under 1000 or a utility. Vectors have no arena: by size.
// filter: an explicit value overrides the automatic star (schema control or measurement); n null = no evidence yet.

export const IMAGE = {
  /* ---------------- OpenAI ---------------- */
  'openai/gpt-image-2.5-sunburst': { fam: 'openai', tier: 'top', released: '2026-09-08',
    lineage: 'GPT Image 1 (2025) → 1.5 → 2 (אפריל 2026) → 2.5 בשתי גרסאות: Sunburst לדיוק, Flare למהירות.',
    power: 'מספר 1 בעולם גם ביצירה (1197) וגם בעריכה (1182). הכי טוב בשמירת דמויות ומוצרים מתמונות ייחוס ובזיכרון של עריכות קודמות בשיחה; תאורה וטקסטורות טבעיות, פריסות מורכבות, רקע שקוף. שש דרגות איכות (low עד max).',
    weak: 'יקר (בערך 0.12-0.21$ לתמונה באיכות גבוהה) ואיטי מ-Flare. מדיניות OpenAI קשוחה.',
    jobs: ['hero', 'edit', 'type'], tips: ['quality high מספיק לרוב; max לתמונת הגיבור הסופית.', 'לעריכה רב-שלבית של אותה תמונה: Sunburst זוכר את העריכות הקודמות.'],
    gotchas: ['מחיר לפי טוקנים: המחיר הסופי ידוע רק אחרי הריצה.'], hebrew: 'טקסט עברי בתמונה לא מובטח; לבדוק כל אות.',
    filter: { n: 0, conf: 'medium', why: 'מדיניות התמונה של OpenAI קשוחה, ואין פרמטר moderation במסמך של Cloudflare.' },
    refs: { t2i: 'GPT Image 2.5 Sunburst (max)', edit: 'GPT Image 2.5 Sunburst (max)' }, sources: ['gpt-image-25', 'aa-t2i', 'aa-edit'] },
  'openai/gpt-image-2.5-flare': { fam: 'openai', tier: 'top', released: '2026-09-08',
    lineage: 'הגרסה המהירה של GPT Image 2.5.',
    power: 'מספר 2 בעולם ביצירה (1190), איכות גבוהה מ-GPT Image 2 בחצי מזמן ההמתנה (פי 2-4 מהר).',
    weak: 'בעריכה 20 נקודות מתחת ל-Sunburst. אותו מחיר כמו Sunburst.',
    jobs: ['hero', 'draft', 'type'], tips: ['לסבבי חזרה מהירים; Sunburst לגרסה הסופית ולעריכה רב-שלבית.'],
    hebrew: 'טקסט עברי לא מובטח.', filter: { n: 0, conf: 'medium', why: 'כמו Sunburst.' },
    refs: { t2i: 'GPT Image 2.5 Flare (max)', edit: 'GPT Image 2.5 Flare (max)' }, sources: ['gpt-image-25', 'aa-t2i'] },
  'openai/gpt-image-2': { fam: 'openai', junk: 'R1', instead: ['openai/gpt-image-2.5-flare', 'openai/gpt-image-2.5-sunburst'], released: '2026-04-21',
    why: '2.5 Flare ו-Sunburst באותו מחיר טוקנים, טובים ממנו (1190-1197 מול 1172), ומהירים ממנו. 2 נעצר בדרגת high.', refs: { t2i: 'GPT Image 2 (high)', edit: 'GPT Image 2 (high)' }, sources: ['gpt-image-25', 'aa-t2i'] },
  'openai/gpt-image-1.5': { fam: 'openai', junk: 'R1', instead: ['openai/gpt-image-2.5-flare'], released: '2025-12-16',
    why: 'יקר מ-2.5 Flare בפלט (32$ מול 30$ למיליון) וחלש ממנו ב-83 נקודות.', refs: { t2i: 'GPT Image 1.5 (high)', edit: 'GPT Image 1.5 (high)' }, sources: ['aa-t2i'] },

  /* ---------------- xAI ---------------- */
  'xai/grok-imagine-image-2.0': { fam: 'xai', tier: 'top', released: '2026-08-07',
    lineage: 'grok-imagine-image (ינואר 2026) → quality (מאי) → 2.0 (אוגוסט).',
    power: 'מספר 4 בעולם ביצירה (1155), מעל Nano Banana 2, ב-0.04$ לתמונה: הערך הטוב ביותר בצמרת.',
    weak: 'אחרי ינואר 2026 xAI חוסמת תוכן על אנשים אמיתיים והסירה את מצב הספייסי.',
    jobs: ['hero', 'edit', 'style'], tips: ['חלופה זולה פי שלושה ל-GPT Image לתמונת אווירה.'],
    hebrew: 'טקסט עברי לא מובטח.', filter: { n: 1, conf: 'low', why: 'xAI הייתה המתירנית בתמונה עד ינואר 2026 והידקה: בלי מצב ספייסי, בלי אנשים אמיתיים. עדיין פחות שמרנית מ-OpenAI ו-Google לפי הדיווחים.' },
    refs: { t2i: 'Grok Imagine Image 2.0', edit: 'Grok Imagine Image 2.0' }, sources: ['aa-t2i', 'grok-policy'] },
  'xai/grok-imagine-image': { fam: 'xai', tier: 'mid', released: '2026-01-28',
    lineage: 'הגרסה הראשונה של Grok Imagine Image.', power: 'הזול של xAI (0.02$), ובעריכה טוב במפתיע (1071, מעל Seedream 4.5 ו-Qwen 3 Pro).',
    weak: 'ביצירה 1019.', jobs: ['edit', 'draft'], hebrew: 'לא רלוונטי.',
    filter: { n: 1, conf: 'low', why: 'כמו Imagine 2.0.' }, refs: { t2i: 'grok-imagine-image', edit: 'grok-imagine-image' }, sources: ['aa-t2i', 'aa-edit'] },
  'xai/grok-imagine-image-quality': { fam: 'xai', junk: 'R2', instead: ['xai/grok-imagine-image-2.0'], released: '2026-05-06',
    why: 'Imagine 2.0 זול ממנו (0.04$ מול 0.05$) וטוב ממנו ב-110 נקודות ביצירה וב-22 בעריכה.', refs: { t2i: 'grok-imagine-image-quality', edit: 'grok-imagine-image-quality' }, sources: ['aa-t2i'] },

  /* ---------------- Google ---------------- */
  'google/nano-banana-2': { fam: 'google', tier: 'top', released: '2026-02-26',
    lineage: 'Nano Banana (Gemini 2.5 Flash Image, אוגוסט 2025) → Pro (Gemini 3 Pro Image, נובמבר 2025) → 2 (Gemini 3.1 Flash Image, פברואר 2026).',
    power: 'טוב מ-Nano Banana Pro בשתי הארנות (1125 ו-1108) בחצי המחיר, 4-6 שניות לתמונה, 512px עד 4K, טקסט קריא באינפוגרפיקות, עיגון בחיפוש בגוגל ובחיפוש תמונות.',
    weak: 'מדיניות התמונה של Google קשוחה (אנשים, אלימות).',
    jobs: ['hero', 'edit', 'type'], tips: ['google_search מאפשר לצייר דבר אמיתי ועדכני (מקום, אירוע) נכון.', 'עד 3 תמונות ייחוס בבקשה (במסמך של Cloudflare).'],
    hebrew: 'טקסט עברי לא מובטח.', filter: { n: 0, conf: 'medium', why: 'Google חוסמת דימוי בוגר ואין מתג במסמך.' },
    refs: { t2i: 'Nano Banana 2 (Gemini 3.1 Flash Image)', edit: 'Nano Banana 2 (Gemini 3.1 Flash Image)' }, sources: ['nano-banana', 'aa-t2i', 'aa-edit'] },
  'google/nano-banana-2-lite': { fam: 'google', tier: 'top', released: '2026-06-30',
    lineage: 'Gemini 3.1 Flash Lite Image.', power: '1096 ביצירה ב-0.039$: מעל Nano Banana Pro בשבע מחירו. המהיר של Google.',
    weak: 'בעריכה 1045.', jobs: ['draft', 'hero'], tips: ['טיוטות לפני Nano Banana 2 או GPT Image.'], hebrew: 'לא מובטח.',
    filter: { n: 0, conf: 'medium', why: 'כמו Nano Banana 2.' }, refs: { t2i: 'Nano Banana 2 Lite (Gemini 3.1 Flash Lite Image)', edit: 'Nano Banana 2 Lite (Gemini 3.1 Flash Lite Image)' }, sources: ['aa-t2i'] },
  'google/nano-banana-pro': { fam: 'google', junk: 'R1', instead: ['google/nano-banana-2'], released: '2025-11-20',
    why: 'Nano Banana 2 חדש ממנו, בחצי מחיר הפלט (60$ מול 120$ למיליון), טוב ממנו בשתי הארנות (1125 מול 1101, 1108 מול 1099), מהיר פי 2-3, ומוסיף עיגון בחיפוש. Google עצמה מעריכה את 2 ב-95% מאיכות ה-Pro.', refs: { t2i: 'Nano Banana Pro (Gemini 3 Pro Image)', edit: 'Nano Banana Pro (Gemini 3 Pro Image)' }, sources: ['nano-banana', 'aa-t2i', 'aa-edit'] },
  'google/nano-banana': { fam: 'google', junk: 'R1', instead: ['google/nano-banana-2-lite'], released: '2025-08-26',
    why: 'Nano Banana 2 Lite באותו מחיר (30$ למיליון פלט) וטוב ממנו ב-110 נקודות.', refs: { t2i: 'Nano Banana (Gemini 2.5 Flash Image)', edit: 'Nano Banana (Gemini 2.5 Flash Image)' }, sources: ['aa-t2i'] },

  /* ---------------- Alibaba ---------------- */
  'alibaba/qwen-image-3.0-pro': { fam: 'alibaba', tier: 'top', released: '2026-07-21',
    lineage: 'Qwen-Image (2025) → 2.0 → 3.0 Pro.', power: 'הטקסט בתוך תמונה הטוב ביותר בקטלוג: פרומפט של 4,500 טוקנים, טקסט קריא ב-10 פיקסלים כולל נוסחאות, 12 שפות ב-20+ גופנים. מצוין לעיתון, תפריט, אינפוגרפיקה, ממשק. 1089 ביצירה ב-0.04$.',
    weak: 'עברית לא ברשימת 12 השפות.', jobs: ['type', 'mockup', 'hero'], tips: ['לפוסטר עם הרבה טקסט באנגלית: לכתוב את הטקסט המדויק במרכאות בפרומפט.'],
    hebrew: 'לא ברשימה הרשמית; לבדוק.', filter: { n: 0, conf: 'low', why: 'בדיקת תוכן של Alibaba Cloud.' },
    refs: { t2i: 'Qwen-Image-3.0-Pro', edit: 'Qwen-Image-3.0-Pro' }, sources: ['qwen-image-3', 'aa-t2i'] },
  'alibaba/wan-2.6-image': { fam: 'alibaba', tier: 'mid', released: '2025-12-17',
    lineage: 'דור Wan 2.6.', power: '1026 ביצירה ו-1038 בעריכה ב-0.03$.', weak: 'Qwen-Image 3.0 Pro טוב ממנו בתוספת של 0.01$.',
    jobs: ['edit', 'draft'], hebrew: 'לא רלוונטי.', filter: { n: 0, conf: 'low', why: 'בדיקת תוכן של Alibaba Cloud.' },
    refs: { t2i: 'Wan 2.6 Image', edit: 'Wan 2.6 Image' }, sources: ['aa-t2i', 'aa-edit'] },

  /* ---------------- ByteDance ---------------- */
  'bytedance/seedream-5-pro': { fam: 'bytedance', tier: 'top', released: '2026-07-08',
    lineage: 'Seedream 3 → 4.0 → 4.5 → 5.0 Lite (פברואר 2026) → 5.0 Pro.', power: 'הכי חזק בעריכה מבין המודלים הזולים (1106, ליד Grok 2.0 ו-GPT Image 1.5), 1081 ביצירה, טיפוגרפיה מעודנת, 0.045$.',
    weak: 'תקרה של כ-4 מגה-פיקסל (2048×2048).', jobs: ['edit', 'hero', 'type'], hebrew: 'לא מובטח.',
    refs: { t2i: 'Seedream 5.0 Pro', edit: 'Seedream 5.0 Pro' }, sources: ['seedream5', 'aa-t2i', 'aa-edit'] },
  'bytedance/seedream-5-lite': { fam: 'bytedance', tier: 'mid', released: '2026-02-13',
    lineage: 'הגרסה המהירה של 5.0.', power: 'עריכה טובה (1058) ב-0.035$, עד 4K.', weak: 'ביצירה 1011, מתחת ל-Seedream 4.0 הזול ממנו.',
    jobs: ['edit'], tips: ['לעריכה בנפח; ליצירה Seedream 4.0.'], hebrew: 'לא מובטח.',
    refs: { t2i: 'Seedream 5.0 Lite', edit: 'Seedream 5.0 Lite' }, sources: ['seedream5', 'aa-edit'] },
  'bytedance/seedream-4.5': { fam: 'bytedance', tier: 'mid', released: '2025-12-05', keepBy: 'K',
    lineage: 'Seedream 4.5 (דצמבר 2025).', power: 'היחיד ממשפחת Seedream עם disable_safety_checker במסמך: מאפשר דימוי בוגר לגיטימי שהאחרים חוסמים. 1023 ביצירה, 1036 בעריכה.',
    weak: 'Seedream 4.0 זול ממנו וטוב ממנו מעט ביצירה; 5.0 Pro טוב ממנו בהרבה.',
    jobs: ['loose', 'edit'], tips: ['disable_safety_checker: true רק לעבודה בוגרת לגיטימית (אימה, אלימות לסרט).'], hebrew: 'לא מובטח.',
    refs: { t2i: 'Seedream 4.5', edit: 'Seedream 4.5' }, sources: ['cf', 'aa-t2i'] },
  'bytedance/seedream-4.0': { fam: 'bytedance', tier: 'mid', released: '2025-09-08',
    lineage: 'Seedream 4.0 (ספטמבר 2025).', power: 'הזול ביותר מעל 1000 בארנה בין מודלי הצמרת: 1029 ביצירה ב-0.03$, מעל 4.5 ו-5.0 Lite.',
    weak: 'בעריכה 1013.', jobs: ['draft', 'hero'], hebrew: 'לא מובטח.', refs: { t2i: 'Seedream 4.0', edit: 'Seedream 4.0' }, sources: ['aa-t2i'] },

  /* ---------------- Black Forest Labs ---------------- */
  'black-forest-labs/flux-2-flex': { fam: 'bfl', tier: 'mid', released: '2025-11-25',
    lineage: 'FLUX.2 (נובמבר 2025): pro לפוטוריאליזם, flex לטיפוגרפיה ושליטה, max לאיכות ולעיגון בחיפוש.',
    power: 'הכי טוב מ-FLUX.2 בארנה (1028), מומחה לטקסט ולוגו, צבע מדויק לפי hex, עד 8 תמונות ייחוס, steps (1-50) ו-guidance בשליטה. safety_tolerance עד 5.',
    weak: '0.05$ לכל מגה-פיקסל, גם הנוספים: בתמונות גדולות max זול ממנו.', jobs: ['type', 'hero', 'loose'],
    tips: ['safety_tolerance 5 לתוכן בוגר לגיטימי (ברירת המחדל 2).', 'prompt_upsampling true כשהפרומפט קצר.'], hebrew: 'לא נתמך באמינות.',
    refs: { t2i: 'FLUX.2 [flex]', edit: 'FLUX.2 [flex]' }, sources: ['flux2', 'aa-t2i', 'cf'] },
  'black-forest-labs/flux-2-max': { fam: 'bfl', tier: 'mid', released: '2025-12-16',
    lineage: 'הדגל של FLUX.2.', power: 'עיגון בחיפוש ברשת (אירועים, מזג אוויר, מקומות אמיתיים), עד 8-10 ייחוסים, safety_tolerance עד 5. מעבר למגה-פיקסל הראשון רק 0.03$.',
    weak: 'בארנה מתחת ל-flex (1021 מול 1028) ובעריכה 996.', jobs: ['hero', 'loose'], tips: ['לתמונות גדולות (2-4 מגה-פיקסל) ולסצנות אמיתיות ועדכניות.'], hebrew: 'לא נתמך.',
    refs: { t2i: 'FLUX.2 [max]', edit: 'FLUX.2 [max]' }, sources: ['flux2', 'aa-t2i', 'cf'] },
  'black-forest-labs/flux-2-pro-preview': { fam: 'bfl', tier: 'mid', released: '2025-11-25',
    lineage: 'FLUX.2 pro.', power: 'פוטוריאליזם בלי כוונון, הזול של FLUX.2 (0.03$ למגה-פיקסל הראשון), safety_tolerance עד 5.',
    weak: '1004 ביצירה.', jobs: ['draft', 'loose'], hebrew: 'לא נתמך.', refs: { t2i: 'FLUX.2 [pro]', edit: 'FLUX.2 [pro]' }, sources: ['flux2', 'aa-t2i'] },
  'black-forest-labs/flux-1-kontext-max': { fam: 'bfl', junk: 'R1', instead: ['black-forest-labs/flux-2-max', 'black-forest-labs/flux-2-flex'], released: '2025-05-29',
    why: 'מודל העריכה של FLUX.1; FLUX.2 max עורך עם 8 ייחוסים, זול ממנו (0.07$ מול 0.08$) וטוב ממנו ב-87 נקודות. ה-tolerance שלו מגיע ל-6 במקום 5, הפרש קטן.', refs: { t2i: 'FLUX.1 Kontext [max]' }, sources: ['aa-t2i'] },
  'black-forest-labs/flux-1-kontext-pro': { fam: 'bfl', junk: 'R1', instead: ['black-forest-labs/flux-2-pro-preview'], released: '2025-05-20',
    why: 'FLUX.2 pro זול ממנו (0.03$ מול 0.04$) וטוב ממנו ב-95 נקודות ביצירה וב-94 בעריכה.', refs: { t2i: 'FLUX.1 Kontext [pro]', edit: 'FLUX.1 Kontext [pro]' }, sources: ['aa-t2i', 'aa-edit'] },

  /* ---------------- Krea ---------------- */
  'krea/krea-2-large': { fam: 'krea', tier: 'mid', released: '2026-05-26',
    lineage: 'Krea 2 (מאי 2026), מודל היסוד הראשון של Krea.', power: 'מראה גולמי בלי "ליטוש AI": גרעין פילם, תנועה, דינמיקה נמוכה, כרום, נצנצים, מאקרו. עד 10 הפניות סגנון עם משקלים (גם שליליים) ולוחות השראה. 1026 בארנה.',
    weak: 'פי ארבעה מ-Medium Turbo כמעט באותה איכות בארנה.', jobs: ['style', 'hero'], tips: ['image_style_references עם moodboard של המותג כדי לשמור שפה אחת בכל הקמפיין.'],
    hebrew: 'לא רלוונטי.', refs: { t2i: 'Krea 2 Large' }, sources: ['krea2', 'aa-t2i'] },
  'krea/krea-2-medium-turbo': { fam: 'krea', tier: 'mid', released: '2026-06-03',
    lineage: 'Krea 2 Medium מזוקק (8 צעדים).', power: '1020 בארנה ב-0.015$: הכי זול מעל 1000. אותה מערכת הפניות סגנון ומוד בורד.',
    weak: 'רזולוציה 1K במסמך.', jobs: ['style', 'draft'], hebrew: 'לא רלוונטי.', refs: { t2i: 'Krea 2 Medium Turbo' }, sources: ['krea2', 'aa-t2i'] },
  'krea/krea-2-medium': { fam: 'krea', junk: 'R2', instead: ['krea/krea-2-medium-turbo'], released: '2026-05-26',
    why: 'Medium Turbo בחצי המחיר (0.015$ מול 0.03$), אותם פרמטרים, וטוב ממנו בארנה (1020 מול 1012).', refs: { t2i: 'Krea 2 Medium' }, sources: ['aa-t2i'] },

  /* ---------------- Recraft ---------------- */
  'recraft/recraftv4-1-utility': { fam: 'recraft', tier: 'mid', released: '2026-05-14',
    lineage: 'V4.1 בגרסת Utility: תאורה שטוחה, קומפוזיציה חזיתית, צפוי.', power: '1023 בארנה ב-0.04$, טוב מ-V4.1 הרגיל. למוקאפים ולתמונות מוצר.',
    weak: 'בלי ביטוי אמנותי.', jobs: ['mockup'], hebrew: 'לא מובטח.', refs: { t2i: 'Recraft V4.1 Utility' }, sources: ['recraft-v41', 'aa-t2i'] },
  'recraft/recraftv4-1-utility-pro': { fam: 'recraft', tier: 'mid', released: '2026-05-14',
    lineage: 'Utility ב-2K.', power: '1018 בארנה, 2K לדפוס.', weak: '0.25$ לתמונה.', jobs: ['mockup'], hebrew: 'לא מובטח.', refs: { t2i: 'Recraft V4.1 Utility Pro' }, sources: ['recraft-v41', 'aa-t2i'] },
  'recraft/recraftv4-1': { fam: 'recraft', tier: 'low', released: '2026-05-14',
    lineage: 'V4.1 הרגיל ("אקספרסיבי").', power: 'מביא נקודת מבט: תאורה, מצב רוח וקומפוזיציה של מעצב; סגנונות ותתי-סגנונות.', weak: '990 בארנה.',
    jobs: ['style'], hebrew: 'לא מובטח.', refs: { t2i: 'Recraft V4.1' }, sources: ['recraft-v41', 'aa-t2i'] },
  'recraft/recraftv4-1-pro': { fam: 'recraft', tier: 'low', released: '2026-05-14',
    lineage: 'V4.1 ב-2K.', power: 'הגרסה האקספרסיבית לדפוס.', weak: '985 בארנה ב-0.25$.', jobs: ['style'], hebrew: 'לא מובטח.', refs: { t2i: 'Recraft V4.1 Pro' }, sources: ['recraft-v41', 'aa-t2i'] },
  'recraft/recraftv4-1-vector': { fam: 'recraft', tier: 'mid', released: '2026-05-14',
    lineage: 'V4.1 וקטור.', power: 'SVG אמיתי, נקי ומדרגי, ב-0.08$: לוגו, אייקון, איור. כמעט אין מתחרים.', weak: 'ללא ארנה.',
    jobs: ['vector'], tips: ['לסקיצת לוגו ואייקונים; ה-SVG נכנס ישר לאתר.'], hebrew: 'לא מובטח.', refs: {}, sources: ['recraft-v41'] },
  'recraft/recraftv4-1-pro-vector': { fam: 'recraft', tier: 'top', released: '2026-05-14',
    lineage: 'V4.1 וקטור מפורט.', power: 'SVG מפורט ברזולוציה גבוהה לדפוס ולשילוט.', weak: '0.30$.', jobs: ['vector'], hebrew: 'לא מובטח.', refs: {}, sources: ['recraft-v41'] },
  'recraft/recraftv4-1-utility-vector': { fam: 'recraft', tier: 'mid', released: '2026-05-14',
    lineage: 'V4.1 Utility וקטור.', power: 'SVG צפוי ושטוח לאייקונים ואינפוגרפיקה.', weak: 'ללא ארנה.', jobs: ['vector', 'mockup'], hebrew: 'לא מובטח.', refs: {}, sources: ['recraft-v41'] },
  'recraft/recraftv4-1-utility-pro-vector': { fam: 'recraft', tier: 'top', released: '2026-05-14',
    lineage: 'V4.1 Utility וקטור מפורט.', power: 'SVG מפורט וצפוי לדפוס.', weak: '0.30$.', jobs: ['vector'], hebrew: 'לא מובטח.', refs: {}, sources: ['recraft-v41'] },
  'recraft/recraftv4': { fam: 'recraft', junk: 'R1', instead: ['recraft/recraftv4-1', 'recraft/recraftv4-1-utility'], released: '2026-02-17',
    why: 'V4.1 באותו מחיר (0.04$) ומעט טוב ממנו (990 מול 983); V4.1 Utility טוב ממנו ב-40 נקודות.', refs: { t2i: 'Recraft V4' }, sources: ['aa-t2i'] },
  'recraft/recraftv4-pro': { fam: 'recraft', junk: 'R1', instead: ['recraft/recraftv4-1-pro', 'recraft/recraftv4-1-utility-pro'], released: '2026-02-17',
    why: 'V4.1 Pro באותו מחיר ובאותה איכות (985 מול 986, תיקו), ו-V4.1 Utility Pro טוב משניהם (1018).', refs: { t2i: 'Recraft V4 Pro' }, sources: ['aa-t2i'] },
  'recraft/recraftv4-vector': { fam: 'recraft', junk: 'R1', instead: ['recraft/recraftv4-1-vector'], released: '2026-02-17',
    why: 'V4.1 וקטור באותו מחיר, דור חדש יותר.', sources: ['recraft-v41'] },
  'recraft/recraftv4-pro-vector': { fam: 'recraft', junk: 'R1', instead: ['recraft/recraftv4-1-pro-vector'], released: '2026-02-17',
    why: 'V4.1 Pro וקטור באותו מחיר, דור חדש יותר.', sources: ['recraft-v41'] },
  'recraft/recraftv3': { fam: 'recraft', junk: 'R1', instead: ['recraft/recraftv4-1'], released: '2024-10-30',
    why: 'V4.1 באותו מחיר, עם אותם שדות סגנון ותת-סגנון, וטוב ממנו ב-122 נקודות (990 מול 868).', refs: { t2i: 'Recraft V3' }, sources: ['aa-t2i', 'cf'] },

  /* ---------------- Pruna ---------------- */
  'pruna/p-image': { fam: 'pruna', tier: 'low', released: '2025-12-02',
    lineage: 'P-Image (דצמבר 2025).', power: 'רצפת המחיר והמהירות: 0.005$, 0.6 שניות לתמונה, שיפור פרומפט אוטומטי. disable_safety_checker במסמך.',
    weak: '885 בארנה: לא לתמונה סופית.', jobs: ['draft', 'loose'], tips: ['מאות טיוטות לקומפוזיציה לפני מודל יקר.'], hebrew: 'לא רלוונטי.',
    refs: { t2i: 'P-Image' }, sources: ['pruna', 'aa-t2i', 'cf'] },
  'pruna/p-image-edit': { fam: 'pruna', tier: 'low', released: '2025-11-28',
    lineage: 'עריכה של Pruna.', power: 'עריכה לפי הוראה בשנייה-שתיים, עד 4 תמונות, 0.01$, disable_safety_checker.', weak: '980 בעריכה.',
    jobs: ['edit', 'draft', 'loose'], hebrew: 'לא רלוונטי.', refs: { edit: 'P-Image-Edit' }, sources: ['pruna', 'aa-edit', 'cf'] },
  'pruna/p-image-try-on': { fam: 'pruna', tier: 'low', released: null,
    lineage: 'הלבשה וירטואלית.', power: 'אדם אחד ועד 11 בגדים (אחד לכל קטגוריה); שומר תנוחה, פנים ורקע; פחות משתי שניות לבגד; 0.015$ לבגד הראשון.',
    weak: 'משימה צרה.', jobs: ['tryon'], tips: ['לחנויות אופנה: הלבשת פריט אמיתי על דוגמן (מוצר אמיתי, לא מומצא).'], hebrew: 'לא רלוונטי.', refs: {}, sources: ['pruna'] },
  'pruna/p-image-upscale': { fam: 'pruna', tier: 'low', released: null,
    lineage: 'הגדלה של Pruna.', power: 'הגדלה ל-1-128 מגה-פיקסל מ-0.005$, disable_safety_checker.', weak: 'משימה צרה.',
    jobs: ['upscale'], hebrew: 'לא רלוונטי.', refs: {}, sources: ['cf'] },

  /* ---------------- free (Workers AI) ---------------- */
  '@cf/black-forest-labs/flux-2-dev': { fam: 'bfl', tier: 'free', released: '2025-11-24',
    lineage: 'FLUX.2 dev, משקלים פתוחים.', power: 'החינמי הטוב ביותר: 1000 ביצירה ו-1000 בעריכה, רמה של FLUX.2 pro.',
    weak: 'יקר במכסה: כ-37.5 נוירונים למשבצת 512 לכל צעד, כלומר כ-3,000 נוירונים (שליש מהמכסה היומית) לתמונה של 1024 ב-20 צעדים.', jobs: ['hero', 'edit'],
    tips: ['רק לתמונה אחת שחשובה ביום; טיוטות ב-klein 4B.'], hebrew: 'לא נתמך.', refs: { t2i: 'FLUX.2 [dev]', edit: 'FLUX.2 [dev]' }, sources: ['wai-pricing', 'aa-t2i'] },
  '@cf/black-forest-labs/flux-2-klein-9b': { fam: 'bfl', tier: 'free', released: '2026-01-14',
    lineage: 'FLUX.2 klein 9B, מזוקק.', power: 'בעריכה 1013, מעל FLUX.2 pro, flex ו-max בתשלום. 941 ביצירה. 1,364 נוירונים למגה-פיקסל.',
    weak: 'יקר פי 13 מ-klein 4B במכסה.', jobs: ['edit'], hebrew: 'לא נתמך.', refs: { t2i: 'FLUX.2 [klein] 9B', edit: 'FLUX.2 [klein] 9B' }, sources: ['wai-pricing', 'aa-edit'] },
  '@cf/black-forest-labs/flux-2-klein-4b': { fam: 'bfl', tier: 'free', released: '2026-01-14',
    lineage: 'FLUX.2 klein 4B.', power: 'הכי משתלם במכסה: כ-105 נוירונים לתמונה של 1024 (כ-95 תמונות ביום). יצירה ועריכה. נמדד במעבדה על חמשת הקונספטים של עדן.',
    weak: '863 ביצירה: טיוטות, לא גרסה סופית; טקסטורות מלאכותיות מעט (ידיים בכפפות).', jobs: ['draft', 'edit'], hebrew: 'לא נתמך.',
    refs: { t2i: 'FLUX.2 [klein] 4B', edit: 'FLUX.2 [klein] 4B' }, sources: ['lab-bench', 'wai-pricing', 'aa-t2i'] },
  '@cf/leonardo/lucid-origin': { fam: 'leonardo', tier: 'free', released: '2025-08-25',
    lineage: 'Leonardo Lucid Origin (אוגוסט 2025).', power: 'אסתטיקה מוכנה מהקופסה, טקסט קריא, Full HD. 901-913 בארנה.',
    weak: 'יקר במכסה (636 נוירונים למשבצת 512 ועוד 12 לצעד: כ-2,700 לתמונה של 1024).', jobs: ['style', 'type'], hebrew: 'לא רלוונטי.',
    refs: { t2i: 'Lucid Origin Fast' }, sources: ['leonardo', 'wai-pricing', 'aa-t2i'] },
  '@cf/bytedance/stable-diffusion-xl-lightning': { fam: 'stability', tier: 'free', released: '2024-02-27', keepBy: 'K',
    lineage: 'SDXL מזוקק לכמה צעדים (ByteDance, 2024).', power: '0 נוירונים לצעד: התמונה היחידה שלא עולה כלום. מהיר מאוד.',
    weak: '719 בארנה: איכות של 2024.', jobs: ['draft'], tips: ['רק לבדיקת קומפוזיציה גסה כשהמכסה נגמרה.'], hebrew: 'לא נתמך.',
    refs: { t2i: 'SDXL Lightning' }, sources: ['wai-pricing', 'aa-t2i'] },
  '@cf/runwayml/stable-diffusion-v1-5-inpainting': { fam: 'stability', tier: 'free', released: '2024-02-27', keepBy: 'K',
    lineage: 'SD 1.5 Inpainting.', power: 'צביעה לפי מסכה: מחליף רק את האזור המסומן ומשאיר את השאר. 0 נוירונים.',
    weak: 'איכות של 2022.', jobs: ['inpaint', 'edit'], tips: ['תיקון אזור קטן בתמונה (להסיר חפץ, להשלים רקע); לעריכה גדולה Seedream 5 Pro או GPT Image.'], hebrew: 'לא נתמך.',
    refs: {}, sources: ['wai-pricing'] },
  '@cf/black-forest-labs/flux-1-schnell': { fam: 'bfl', junk: 'R2', instead: ['@cf/black-forest-labs/flux-2-klein-4b'], released: '2024-08-29',
    why: 'FLUX.2 klein 4B מאותו יצרן טוב ממנו ב-61 נקודות ועורך גם תמונות, בתוספת של כ-45 נוירונים (0.0005$) לתמונה.', refs: { t2i: 'FLUX.1 [schnell]' }, sources: ['aa-t2i', 'wai-pricing'] },
  '@cf/leonardo/phoenix-1.0': { fam: 'leonardo', junk: 'R2', instead: ['@cf/leonardo/lucid-origin'], released: '2025-08-25',
    why: 'Lucid Origin מאותו יצרן טוב ממנו בכ-70 נקודות (901-913 מול 823-843) בתוספת של כ-20%.', refs: { t2i: 'Phoenix 1.0 Fast' }, sources: ['aa-t2i', 'wai-pricing'] },
  '@cf/stabilityai/stable-diffusion-xl-base-1.0': { fam: 'stability', junk: 'R2', instead: ['@cf/bytedance/stable-diffusion-xl-lightning'], released: '2023-11-10',
    why: 'SDXL-Lightning הוא אותו SDXL מזוקק: אותם שדות (מסכה, img2img), אותו מחיר (0), מהיר יותר וגבוה ממנו בארנה (719 מול 678).', refs: { t2i: 'Stable Diffusion XL 1.0' }, sources: ['aa-t2i'] },
  '@cf/lykon/dreamshaper-8-lcm': { fam: 'stability', junk: 'R2', instead: ['@cf/bytedance/stable-diffusion-xl-lightning'], released: '2024-02-27',
    why: 'כוונון קהילתי של SD 1.5 (2023); SDXL-Lightning מאותה משפחה, גם הוא בחינם, ברזולוציה כפולה ובאיכות גבוהה ממנו.', sources: ['aa-t2i'] },
};
