// AILGEN Lab · the arsenal's curated knowledge, part 2: text models (paid through the gateway, paid on Workers AI, and free).
// refs map a model to the independent boards: aa = Artificial Analysis row name, cw = EQ-Bench creative-writing model, speech = SpeechMap
// model (the row with the same mode the lab uses; `speechAlt` is the other mode). Tiers for text: top = AA index 43+, mid = 25-43, low = under 25.

export const TEXT = {
  /* ---------------- OpenAI ---------------- */
  'openai/gpt-6-astra': { fam: 'openai', tier: 'top', released: '2026-09-03',
    lineage: 'הדגל הראשון של הדור השישי; לקח את המקום של GPT-5.6 Sol בראש השורה.',
    power: 'הכותב היצירתי מספר 1 בעולם ב-EQ-Bench (2173). סוכן מחשב: Terminal-Bench 4.0 57.9%, OSWorld 2.0 72.6%, ScreenSpot-Pro 92.7%, FrontierMath Tier 4 97.6%. שיעור הזיות 4.2% (מול 12.2% ב-5.6 Sol). כ-70% פחות טוקנים מ-Sol לאותה משימה. הקשר של 1.05M, פלט עד 128K, חמש דרגות חשיבה.',
    weak: 'יקר: 10$/50$ למיליון, ומעל 272K טוקני קלט המחיר כפול. אין גרסה קטנה. באינטליגנציה הכללית מעט מתחת ל-Opus 5.5 ו-Fable 5.1 (AA 52.7). חוסם עבודת סייבר התקפית.',
    jobs: ['write', 'think', 'agent', 'long', 'code', 'research'],
    tips: ['למשימות כתיבה ותסריט: reasoning_effort medium מספיק ברוב המקרים; xhigh/max רק לבעיות קשות באמת.', 'שמור את הבקשה מתחת ל-272K טוקני קלט כדי לא לשלם כפול.'],
    gotchas: ['ב-Chat Completions function calling עובד רק עם reasoning_effort none; לכלים עם חשיבה צריך את Responses API.', 'קלט: טקסט ותמונה בלבד, פלט טקסט בלבד.'],
    hebrew: 'טובה מאוד.', refs: { aa: 'GPT-6 Astra (Max)', cw: 'gpt-6-astra', speech: 'openai/gpt-6-astra' }, sources: ['openai-models', 'gpt6-astra', 'eqbench', 'aa-llm'] },
  'openai/gpt-6-sol': { fam: 'openai', tier: 'top', released: '2026-09-22',
    lineage: 'מחליף את GPT-5.6 Sol בחצי המחיר (2$/10$). כבר יש GPT-6.1 Sol אצל OpenAI, לא בקטלוג.',
    power: 'כותב יצירתי מספר 4 בעולם (EQ-Bench 2125, מעל Opus 5.5). חצי מהטעויות של 5.6 Sol; שיעור שגיאות עובדתיות 4.5%. בבדיקת DevOps עבר 9/9 כמו Opus 5.5 ב-31% מהעלות. AA 47.6.',
    weak: 'בקוד ארוך-טווח מעט מתחת ל-5.6 Sol (DeepSWE 68.8% מול 72.7%). פלטים קצרים מקודמיו: לבדוק שלמות במשימות שנמדדות לפי היקף.',
    jobs: ['write', 'copy-he', 'code', 'agent', 'plan-json', 'think'],
    tips: ['ברירת המחדל לכתיבה ולתכנון בזרימות: חכם, זול פי חמישה מ-Astra.', 'reasoning_effort none לפלט JSON מהיר בזרימה; medium כשצריך שיקול דעת.'],
    gotchas: ['function calling ב-Chat Completions רק עם reasoning_effort none.', 'מעל 272K טוקני קלט: קלט כפול ופלט ×1.5.'],
    hebrew: 'טובה מאוד.', refs: { aa: 'GPT-6 Sol (Max)', cw: 'gpt-6-sol', speech: 'openai/gpt-6-sol' }, sources: ['gpt6-sol-luna', 'openai-models', 'eqbench', 'aa-llm'] },
  'openai/gpt-6-luna': { fam: 'openai', tier: 'mid', released: '2026-09-22',
    lineage: 'מחליף את GPT-5.6 Luna: 0.10$/0.50$ במקום 0.20$/1.20$.',
    power: 'AA 38.1 בחשיבה מקסימלית, כמו GPT-5.5 (38.4) בחמישים מהמחיר. DeepSWE 66.6% ב-0.22$ למשימה. הקשר של 1.05M. הדבר הכי חזק לכל דולר בקטלוג.',
    weak: 'בבדיקת DevOps עבר את הבודק אבל קרס בהרצה (6/9): צריך לאמת בהרצה, לא רק בלינטר. הזיות ברמה בינונית (AA 0.23).',
    jobs: ['bulk', 'plan-json', 'see', 'code'],
    tips: ['הבחירה לכל שלב תיווך בזרימה: חילוץ, פירוק בריף לרשימת שוטים, תרגום פרומפטים.', 'reasoning_effort low או none לנפח; max רק כשהבעיה קשה.'],
    gotchas: ['function calling ב-Chat Completions רק עם reasoning_effort none.'],
    hebrew: 'טובה.', refs: { aa: 'GPT-6 Luna (Max)', speech: 'openai/gpt-6-luna' }, sources: ['gpt6-sol-luna', 'aa-llm'] },
  'openai/gpt-4o-mini': { fam: 'openai', tier: 'low', released: '2024-07-18', keepBy: 'K',
    lineage: 'הקטן של GPT-4o (2024).',
    power: 'הכי פתוח של OpenAI: עונה על 84.5% מבקשות הדיבור השנוי במחלוקת (SpeechMap), מול 63-68% בדור השישי. זול מאוד (0.075$/0.30$).',
    weak: 'חלש: AA 6.7, כתיבה יצירתית 873 ב-EQ-Bench. ישן.',
    jobs: ['loose', 'bulk'], tips: ['רק כשמודל של OpenAI מסרב לבקשה לגיטימית ונדרש ניסוח פתוח יותר; לכל השאר GPT-6 Luna.'],
    hebrew: 'בינונית.', refs: { aa: 'GPT-4o mini', cw: 'gpt-4o-mini', speech: 'openai/gpt-4o-mini-2024-07-18' }, sources: ['speechmap', 'aa-llm'] },
  'openai/gpt-5.5-pro': { fam: 'openai', junk: 'R2', instead: ['openai/gpt-6-astra'], released: '2026-04-23',
    why: 'פי שישה מ-Astra (30$/180$ מול 10$/50$) ו-OpenAI קוראת ל-Astra "המודל הכי מסוגל שלנו לעבודה התובענית ביותר". Astra בדרגת max עושה את עבודת ה-Pro.', refs: { aa: 'GPT-5.5 Pro (Xhigh)' }, sources: ['openai-models'] },
  'openai/gpt-5.4-pro': { fam: 'openai', junk: 'R1', instead: ['openai/gpt-6-astra'], released: '2026-03-05',
    why: 'אותו מחיר כמו 5.5 Pro ודור ישן יותר; Astra חזק ממנו ובשישית מהמחיר.', sources: ['openai-models'] },
  'openai/gpt-5.5': { fam: 'openai', junk: 'R2', instead: ['openai/gpt-6-sol', 'openai/gpt-6-luna'], released: '2026-04-23',
    why: 'GPT-6 Luna מגיע לאותו מדד (38.1 מול 38.4) בחמישים מהמחיר, ו-GPT-6 Sol חזק בהרבה (47.6) בשליש ממנו. גם בכתיבה Sol עוקף (2125 מול 1844).', refs: { aa: 'GPT-5.5 (Xhigh)', cw: 'gpt-5.5', speech: 'openai/gpt-5.5' }, sources: ['aa-llm', 'eqbench'] },
  'openai/gpt-5.6-sol': { fam: 'openai', junk: 'R1', instead: ['openai/gpt-6-sol'], released: '2026-07-09',
    why: 'GPT-6 Sol החליף אותו באותו מחיר בקטלוג, עם חצי מהטעויות וכתיבה טובה יותר (2125 מול 1972). הוא עדיין מעט טוב יותר ב-DeepSWE (72.7% מול 68.8%); לקוד ארוך כבד Astra מכסה.', refs: { aa: 'GPT-5.6 Sol (Max)', cw: 'gpt-5.6-sol', speech: 'openai/gpt-5.6-sol' }, sources: ['gpt6-sol-luna', 'eqbench'] },
  'openai/gpt-5.6-terra': { fam: 'openai', junk: 'R2', instead: ['openai/gpt-6-sol'], released: '2026-07-09',
    why: 'השכבה האמצעית של 5.6 (2$/12$). GPT-6 Sol זול ממנו (2$/10$), חכם ממנו (47.6 מול 42.1) וכותב טוב ממנו. לא יצא GPT-6 Terra.', refs: { aa: 'GPT-5.6 Terra (Max)', cw: 'gpt-5.6-terra', speech: 'openai/gpt-5.6-terra' }, sources: ['gpt56', 'aa-llm'] },
  'openai/gpt-5.6-luna': { fam: 'openai', junk: 'R1', instead: ['openai/gpt-6-luna'], released: '2026-07-09',
    why: 'GPT-6 Luna החליף אותו בחצי מחיר הקלט ופחות מחצי מחיר הפלט, ומעט חזק ממנו (38.1 מול 37.3).', refs: { aa: 'GPT-5.6 Luna (Max)', cw: 'gpt-5.6-luna', speech: 'openai/gpt-5.6-luna' }, sources: ['gpt6-sol-luna', 'aa-llm'] },
  'openai/gpt-5.4': { fam: 'openai', junk: 'R2', instead: ['openai/gpt-6-sol'], released: '2026-03-05',
    why: 'יקר מ-GPT-6 Sol (2.5$/15$ מול 2$/10$) וחלש ממנו (39.0 מול 47.6).', refs: { aa: 'GPT-5.4 (Xhigh)', cw: 'gpt-5.4', speech: 'openai/gpt-5.4' }, sources: ['aa-llm'] },
  'openai/gpt-5.4-mini': { fam: 'openai', junk: 'R2', instead: ['openai/gpt-6-luna'], released: '2026-03-17',
    why: 'פי שבעה עד תשעה מ-GPT-6 Luna וחלש ממנו (24.1 מול 38.1).', refs: { aa: 'GPT-5.4 mini (Xhigh)', speech: 'openai/gpt-5.4-mini' }, sources: ['aa-llm'] },
  'openai/gpt-5.4-nano': { fam: 'openai', junk: 'R2', instead: ['openai/gpt-6-luna'], released: '2026-03-17',
    why: 'יקר מ-GPT-6 Luna פי שניים וחצי וחלש ממנו (20.7 מול 38.1).', refs: { aa: 'GPT-5.4 nano (Xhigh)', speech: 'openai/gpt-5.4-nano' }, sources: ['aa-llm'] },
  'openai/gpt-5.1': { fam: 'openai', junk: 'R2', instead: ['openai/gpt-6-luna', 'openai/gpt-6-sol'], released: '2025-11-13',
    why: 'GPT-6 Luna חזק ממנו (38.1 מול 24.7) בשמינית מהמחיר; GPT-6 Sol באותו מחיר פלט וחזק בהרבה.', refs: { aa: 'GPT-5.1 (High)', speech: 'openai/gpt-5.1' }, sources: ['aa-llm'] },
  'openai/gpt-5': { fam: 'openai', junk: 'R2', instead: ['openai/gpt-6-luna', 'openai/gpt-6-sol'], released: '2025-08-07',
    why: 'כמו GPT-5.1: Luna חזק ממנו (38.1 מול 23.0) בשמינית מהמחיר.', refs: { aa: 'GPT-5 (High)', cw: 'gpt-5-2025-08-07', speech: 'openai/gpt-5' }, sources: ['aa-llm'] },
  'openai/gpt-5-mini': { fam: 'openai', junk: 'R2', instead: ['openai/gpt-6-luna'], released: '2025-08-07',
    why: 'יקר מ-Luna (0.25$/2$ מול 0.10$/0.50$) וחלש ממנו (20.6 מול 38.1).', refs: { aa: 'GPT-5 mini (Medium)', cw: 'gpt-5-mini-2025-08-07', speech: 'openai/gpt-5-mini' }, sources: ['aa-llm'] },
  'openai/gpt-5-nano': { fam: 'openai', junk: 'R2', instead: ['openai/gpt-6-luna'], released: '2025-08-07',
    why: 'זול מ-Luna בפחות מ-0.0003$ לעבודה טיפוסית, וחלש ממנו פי שלושה (13.0 מול 38.1); כתיבה 705 ב-EQ-Bench.', refs: { aa: 'GPT-5 nano (High)', cw: 'gpt-5-nano-2025-08-07', speech: 'openai/gpt-5-nano' }, sources: ['aa-llm', 'eqbench'] },
  'openai/gpt-4.1': { fam: 'openai', junk: 'R2', instead: ['openai/gpt-6-luna'], released: '2025-04-14',
    why: 'פי עשרים מ-Luna וחלש ממנו (12.7 מול 38.1). ההקשר של מיליון שהיה הייחוד שלו קיים גם ב-Luna.', refs: { aa: 'GPT-4.1', cw: 'gpt-4.1', speech: 'openai/gpt-4.1-2025-04-14' }, sources: ['aa-llm'] },
  'openai/gpt-4.1-mini': { fam: 'openai', junk: 'R2', instead: ['openai/gpt-6-luna'], released: '2025-04-14',
    why: 'יקר מ-Luna פי ארבעה וחלש ממנו (10.2 מול 38.1).', refs: { aa: 'GPT-4.1 mini', cw: 'gpt-4.1-mini', speech: 'openai/gpt-4.1-mini-2025-04-14' }, sources: ['aa-llm'] },
  'openai/gpt-4.1-nano': { fam: 'openai', junk: 'R2', instead: ['openai/gpt-6-luna'], released: '2025-04-14',
    why: 'אותו מחיר כמעט כמו Luna (0.10$/0.40$) וחלש ממנו פי חמישה (7.8 מול 38.1).', refs: { aa: 'GPT-4.1 nano', cw: 'gpt-4.1-nano', speech: 'openai/gpt-4.1-nano-2025-04-14' }, sources: ['aa-llm'] },
  'openai/gpt-4o': { fam: 'openai', junk: 'R2', instead: ['openai/gpt-6-luna'], released: '2024-11-20',
    why: 'פי עשרה מ-Luna וחלש ממנו (8.4 מול 38.1); בפתיחות המסנן הגרסה הנוכחית (60%) לא עולה על Luna (63%).', refs: { aa: "GPT-4o (Nov '24)", speech: 'openai/gpt-4o-2024-11-20' }, sources: ['aa-llm', 'speechmap'] },
  'openai/o3': { fam: 'openai', junk: 'R2', instead: ['openai/gpt-6-sol', 'openai/gpt-6-luna'], released: '2025-04-16',
    why: 'מודל החשיבה של 2025: AA 20.2 מול 38.1 של Luna בשש-עשרה מהמחיר. ידוע בשיעור הזיות גבוה.', refs: { aa: 'o3', cw: 'o3', speech: 'openai/o3-2025-04-16' }, sources: ['aa-llm'] },
  'openai/o3-mini': { fam: 'openai', junk: 'R2', instead: ['openai/gpt-6-luna'], released: '2025-01-31',
    why: 'יקר מ-Luna פי עשרה וחלש ממנו (11.0 מול 38.1).', refs: { aa: 'o3-mini (High)', speech: 'openai/o3-mini' }, sources: ['aa-llm'] },
  'openai/o4-mini': { fam: 'openai', junk: 'R2', instead: ['openai/gpt-6-luna'], released: '2025-04-16',
    why: 'יקר מ-Luna פי עשרה וחלש ממנו (16.7 מול 38.1).', refs: { aa: 'o4-mini (High)', speech: 'openai/o4-mini-2025-04-16' }, sources: ['aa-llm'] },

  /* ---------------- Anthropic ---------------- */
  'anthropic/claude-opus-5.5': { fam: 'anthropic', tier: 'top', released: '2026-09-22',
    lineage: 'Opus החמישי והחצי; Anthropic: "ברמה של Fable 5.1 ברוב העבודה" ב-40% מהמחיר.',
    power: 'מספר 1 במדד האינטליגנציה של Artificial Analysis (57.6). Terminal-Bench 4.0 66.4% (Fable 5.1: 55.8%), OSWorld 2.0 81.8%, GDPval 1846. כותב מהר ב-30% מ-Opus 5. הכי פתוח מבין מודלי הדגל: 83% ב-SpeechMap. הקשר של מיליון, פלט 128K.',
    weak: 'בכתיבה יצירתית רק 2050 ב-EQ-Bench, מתחת ל-Opus 5 (2133) ול-Fable 5.1 (2162). יקר מ-Sol פי שניים.',
    jobs: ['think', 'agent', 'code', 'long', 'copy-he', 'research', 'see', 'loose'],
    tips: ['המוח הראשי לזרימה מורכבת: בריף, אסטרטגיה, תסריט שדורש שיקול דעת.', 'effort medium הוא ברירת המחדל; xhigh/max רק כשהבעיה באמת קשה.', 'לקופי עם קול ספרותי חזק: Opus 5 או Fable 5.1.'],
    gotchas: ['חשיבה אדפטיבית תמיד פועלת; לא שולחים budget_tokens.'],
    hebrew: 'מצוינת, טבעית.', refs: { aa: 'Claude Opus 5.5 (Adaptive Reasoning, Max Effort, Default Fallback)', cw: 'claude-opus-5-5', speech: 'anthropic/claude-opus-5.5' }, sources: ['opus55-fable', 'aa-llm', 'speechmap', 'eqbench'] },
  'anthropic/claude-fable-5.1': { fam: 'anthropic', tier: 'top', released: '2026-09-01', keepBy: 'K',
    lineage: 'עדכון של Fable 5 (יוני 2026), הדגל היקר של Anthropic.',
    power: 'הכותב היצירתי מספר 2 בעולם (EQ-Bench 2162, רק 11 מתחת ל-Astra), עם ה"סלופ" הנמוך ביותר בצמרת (8.2). מוביל במדד הסוכנים של AA (58.0%) ובמחקר סוכני ארוך (Terminal-Bench-Science, CursorBench 3.2 73.4%).',
    weak: 'פי 2.5 מ-Opus 5.5, ש-Anthropic עצמה אומרת שהוא ברמתו ברוב העבודה וחכם ממנו במדד הכללי (57.6 מול 53.4). שמור לחריגים.',
    jobs: ['write', 'agent'],
    tips: ['רק לכתיבה שהיא המוצר עצמו (תסריט הסרט, טקסט הגיבור) או למשימת סוכן של שעות שבה Opus 5.5 ב-max נכשל.'],
    hebrew: 'מצוינת.', refs: { aa: 'Claude Fable 5.1 (Adaptive Reasoning, Max Effort, Default Fallback)', cw: 'claude-fable-5-1', speech: 'anthropic/claude-fable-5.1' }, sources: ['opus55-fable', 'eqbench', 'aa-llm'] },
  'anthropic/claude-opus-5': { fam: 'anthropic', tier: 'top', released: '2026-07-24', keepBy: 'K',
    lineage: 'Opus 5 (יולי 2026), הוחלף ב-Opus 5.5 ונשאר פעיל לפחות עד יולי 2027.',
    power: 'כותב יצירתי מספר 3 בעולם (EQ-Bench 2133) עם ה"סלופ" הנמוך ביותר בכל הלוח (6.6): כותב טוב מ-Opus 5.5 ב-83 נקודות.',
    weak: 'יקר מ-Opus 5.5 ב-25% וחלש ממנו בחשיבה (50.8 מול 57.6). קשוח יותר (59% ב-SpeechMap).',
    jobs: ['write', 'copy-he'],
    tips: ['הכותב של הסטודיו כשהטקסט חייב להישמע אנושי: מניפסט מותג, תסריט, סיפור. חצי מחיר של Fable באותה רמת כתיבה כמעט.'],
    hebrew: 'מצוינת.', refs: { aa: 'Claude Opus 5 (Adaptive Reasoning, Max Effort)', cw: 'claude-opus-5', speech: 'anthropic/claude-opus-5' }, sources: ['eqbench', 'aa-llm', 'speechmap'] },
  'anthropic/claude-sonnet-5': { fam: 'anthropic', tier: 'mid', released: '2026-06-30',
    lineage: 'Sonnet החמישי (יוני 2026). Sonnet 5.5 כבר יצא (ספטמבר) ועוד לא בקטלוג.',
    power: 'Claude בחמישית ממחיר Fable: AA 38.2, הוראות מדויקות, סגנון Claude.',
    weak: 'קשוח (41% ב-SpeechMap). כתיבה יצירתית 1794, מתחת ל-GPT-6 Sol באותו מחיר (2125). Opus 5.5 חזק בהרבה בתוספת של 0.014$ לעבודה.',
    jobs: ['code', 'plan-json', 'copy-he'],
    tips: ['כשרוצים את הסגנון והזהירות של Claude בנפח; לכתיבה יצירתית עדיף Sol או Opus.'],
    hebrew: 'טובה מאוד.', refs: { aa: 'Claude Sonnet 5 (Adaptive Reasoning, Max Effort)', cw: 'claude-sonnet-5', speech: 'anthropic/claude-sonnet-5' }, sources: ['aa-llm', 'eqbench', 'speechmap'] },
  'anthropic/claude-haiku-4.5': { fam: 'anthropic', tier: 'low', released: '2025-10-15',
    lineage: 'Haiku 4.5 (אוקטובר 2025); אין Haiku 5.',
    power: 'מהיר וזול יחסית ל-Claude; עמידות להזיות גבוהה (0.73 ב-AA, מהטובות בקטלוג).',
    weak: 'חלש (AA 16.9) והכי קשוח בקטלוג (21% ב-SpeechMap). GPT-6 Luna חזק ממנו פי שניים בעשירית מהמחיר.',
    jobs: ['bulk'], tips: ['לחילוץ עובדות שבו עדיף "לא יודע" על פני המצאה.'],
    hebrew: 'טובה.', refs: { aa: 'Claude 4.5 Haiku (Reasoning)', speech: 'anthropic/claude-haiku-4.5' }, sources: ['aa-llm', 'speechmap'] },
  'anthropic/claude-fable-5': { fam: 'anthropic', junk: 'R1', instead: ['anthropic/claude-fable-5.1', 'anthropic/claude-opus-5.5'], released: '2026-06-09',
    why: 'Fable 5.1 באותו מחיר עם מטמון זול פי ארבעה וכתיבה טובה יותר (2162 מול 1943).', refs: { aa: 'Claude Fable 5 (Adaptive Reasoning, Max Effort, Opus 4.8 Fallback)', cw: 'claude-fable-5', speech: 'anthropic/claude-fable-5' }, sources: ['eqbench', 'opus55-fable'] },
  'anthropic/claude-opus-4.8': { fam: 'anthropic', junk: 'R1', instead: ['anthropic/claude-opus-5.5'], released: '2026-05-28',
    why: 'Opus 5.5 זול ממנו (4$/20$ מול 5$/25$) וחזק ממנו בהרבה (57.6 מול 41.8).', refs: { aa: 'Claude Opus 4.8 (Adaptive Reasoning, Max Effort)', cw: 'claude-opus-4-8', speech: 'anthropic/claude-opus-4.8' }, sources: ['aa-llm'] },
  'anthropic/claude-opus-4.7': { fam: 'anthropic', junk: 'R1', instead: ['anthropic/claude-opus-5.5'], released: '2026-04-16',
    why: 'Opus 5.5 זול ממנו וחזק ממנו (57.6 מול 40.7).', refs: { aa: 'Claude Opus 4.7 (Adaptive Reasoning, Max Effort)', cw: 'claude-opus-4-7', speech: 'anthropic/claude-opus-4.7' }, sources: ['aa-llm'] },
  'anthropic/claude-opus-4.6': { fam: 'anthropic', junk: 'R1', instead: ['anthropic/claude-opus-5.5'], released: '2026-02-05',
    why: 'Opus 5.5 זול ממנו וחזק ממנו (57.6 מול 31.9).', refs: { aa: 'Claude Opus 4.6 (Adaptive Reasoning, Max Effort)', cw: 'claude-opus-4-6', speech: 'anthropic/claude-opus-4.6' }, sources: ['aa-llm'] },
  'anthropic/claude-opus-4.5': { fam: 'anthropic', junk: 'R1', instead: ['anthropic/claude-opus-5.5'], released: '2025-11-24',
    why: 'Opus 5.5 זול ממנו וחזק ממנו (57.6 מול 29.1).', refs: { aa: 'Claude Opus 4.5 (Reasoning)', cw: 'claude-opus-4-5-20251101', speech: 'anthropic/claude-opus-4.5' }, sources: ['aa-llm'] },
  'anthropic/claude-sonnet-4.6': { fam: 'anthropic', junk: 'R1', instead: ['anthropic/claude-sonnet-5'], released: '2026-02-18',
    why: 'Sonnet 5 זול ממנו (2$/10$ מול 3$/15$) וחזק ממנו (38.2 מול 30.1); בכתיבה הם שווים (1794 מול 1810, בתוך הרעש).', refs: { aa: 'Claude Sonnet 4.6 (Adaptive Reasoning, Max Effort)', cw: 'claude-sonnet-4-6', speech: 'anthropic/claude-sonnet-4.6' }, sources: ['aa-llm', 'eqbench'] },
  'anthropic/claude-sonnet-4.5': { fam: 'anthropic', junk: 'R1', instead: ['anthropic/claude-sonnet-5'], released: '2025-09-29',
    why: 'Sonnet 5 זול ממנו וחזק ממנו (38.2 מול 20.7), וכותב טוב ממנו (1794 מול 1678).', refs: { aa: 'Claude 4.5 Sonnet (Reasoning)', cw: 'claude-sonnet-4.5', speech: 'anthropic/claude-sonnet-4.5' }, sources: ['aa-llm', 'eqbench'] },

  /* ---------------- Google ---------------- */
  'google/gemini-3.8-flash': { fam: 'google', tier: 'mid', released: '2026-09-02',
    lineage: 'ה-Flash השלישי בשישה שבועות (3.6 ביולי, 3.7 באוגוסט). אותו מפרט כמו 3.7, איכות גבוהה בכל 14 המבחנים.',
    power: 'Gemini הכי חכם בקטלוג: AA 40.9, עוקף את 3.1 Pro (29.7) בשליש מהמחיר. DeepSWE 73.7% (Opus 5: 74.0%). פתוח: 86% ב-SpeechMap. קלט טקסט, תמונה, וידאו, שמע ו-PDF; הקשר של מיליון; 235 טוקנים לשנייה.',
    weak: 'בכתיבה יצירתית חלש (1748) וה"סלופ" גבוה (22.6): ניסוחים גנריים. ב-Terminal-bench 4.0 ובשימוש במחשב הרבה מתחת ל-Opus. המחיר יוכפל ב-1 בינואר 2027.',
    jobs: ['see', 'long', 'bulk', 'research', 'plan-json', 'loose'],
    tips: ['המודל לקריאת וידאו ושמע בזרימה: הוא היחיד בצמרת שמקבל אותם.', 'thinking low לנפח (0 טוקני חשיבה), medium ברירת מחדל, high רק לבעיות קשות: ב-high 92% מהחיוב הוא חשיבה.', 'safetySettings עם BLOCK_NONE לתוכן בוגר לגיטימי.'],
    gotchas: ['thinking "minimal" נדחה ב-3.8 (שגיאה 400).', 'המחיר הנוכחי בתוקף עד 31 בדצמבר 2026.'],
    hebrew: 'טובה.', refs: { aa: 'Gemini 3.8 Flash (High)', cw: 'gemini-3.8-flash', speech: 'google/gemini-3.8-flash' }, sources: ['gemini38', 'gemini38-decoder', 'aa-llm', 'eqbench', 'speechmap'] },
  'google/gemini-3.5-flash-lite': { fam: 'google', tier: 'low', released: '2026-07-21',
    lineage: 'ה-Lite של דור 3.5.',
    power: 'הכי מהיר בקטלוג (354 טוקנים לשנייה), עמיד להזיות (0.66), פתוח (85%), מקבל שמע, וידאו ו-PDF. AA 22.2.',
    weak: 'כתיבה יצירתית חלשה (1559) עם סלופ גבוה.',
    jobs: ['bulk', 'see'], tips: ['תמלול-אגב, תיוג וידאו, חילוץ מ-PDF בכמות.'],
    hebrew: 'סבירה.', refs: { aa: 'Gemini 3.5 Flash-Lite', cw: 'gemini-3.5-flash-lite', speech: 'google/gemini-3.5-flash-lite' }, sources: ['aa-llm', 'speechmap'] },
  'google/gemini-2.5-flash-lite': { fam: 'google', tier: 'low', released: '2025-07-22', keepBy: 'K',
    lineage: 'Lite של דור 2.5.',
    power: 'הדרך הזולה ביותר להכניס שמע או וידאו למודל שפה בקטלוג (0.10$/0.40$), חמישית ממחיר 3.5 Flash-Lite.',
    weak: 'חלש (AA 8.5).', jobs: ['bulk'], tips: ['רק לנפח של שמע/וידאו שבו המחיר קובע.'],
    hebrew: 'סבירה.', refs: { aa: 'Gemini 2.5 Flash-Lite (Reasoning)', speech: 'google/gemini-2.5-flash-lite' }, sources: ['aa-llm'] },
  'google/gemini-3.1-pro': { fam: 'google', junk: 'R2', instead: ['google/gemini-3.8-flash'], released: '2026-02-19',
    why: 'Gemini 3.8 Flash חזק ממנו (40.9 מול 29.7), כותב טוב ממנו (1748 מול 1491), פתוח ממנו (86% מול 60%), מקבל אותם קלטים, בשליש מהמחיר. Google לא שחררה Pro חדש מאז.', refs: { aa: 'Gemini 3.1 Pro Preview', cw: 'gemini-3.1-pro-preview', speech: 'google/gemini-3.1-pro-preview' }, sources: ['aa-llm', 'gemini38-decoder'] },
  'google/gemini-3.7-flash': { fam: 'google', junk: 'R1', instead: ['google/gemini-3.8-flash'], released: '2026-08-13',
    why: 'אותו מחיר ואותו מפרט כמו 3.8, ו-3.8 טוב ממנו בכל 14 המבחנים.', refs: { aa: 'Gemini 3.7 Flash (High)', cw: 'gemini-3.7-flash', speech: 'google/gemini-3.7-flash' }, sources: ['gemini38'] },
  'google/gemini-3.6-flash': { fam: 'google', junk: 'R1', instead: ['google/gemini-3.8-flash'], released: '2026-07-21',
    why: 'בקטלוג יקר מ-3.8 (1.5$/7.5$ מול 0.75$/3.75$) וחלש ממנו (34.0 מול 40.9).', refs: { aa: 'Gemini 3.6 Flash (High)', cw: 'gemini-3.6-flash', speech: 'google/gemini-3.6-flash' }, sources: ['aa-llm'] },
  'google/gemini-3.5-flash': { fam: 'google', junk: 'R1', instead: ['google/gemini-3.8-flash'], released: '2026-05-19',
    why: 'יקר מ-3.8 פי שניים (1.5$/9$) וחלש ממנו (32.6 מול 40.9).', refs: { aa: 'Gemini 3.5 Flash (High)', speech: 'google/gemini-3.5-flash' }, sources: ['aa-llm'] },
  'google/gemini-3-flash': { fam: 'google', junk: 'R2', instead: ['google/gemini-3.8-flash'], released: '2025-12-17',
    why: '3.8 Flash חזק ממנו (40.9 מול 26.3) בתוספת של 0.0013$ לעבודה; 3 Flash גם מזה הרבה (עמידות להזיות 0.07).', refs: { aa: 'Gemini 3 Flash Preview (Reasoning)', speech: 'google/gemini-3-flash-preview-thinking' }, sources: ['aa-llm'] },
  'google/gemini-3.1-flash-lite': { fam: 'google', junk: 'R2', instead: ['google/gemini-3.5-flash-lite'], released: '2026-05-08',
    why: '3.5 Flash-Lite חזק ממנו (22.2 מול 15.6) ועמיד להזיות פי ארבעה, בתוספת של 0.0011$ לעבודה.', refs: { aa: 'Gemini 3.1 Flash-Lite', speech: 'google/gemini-3.1-flash-lite' }, sources: ['aa-llm'] },
  'google/gemini-2.5-pro': { fam: 'google', junk: 'R2', instead: ['google/gemini-3.8-flash'], released: '2025-06-05',
    why: '3.8 Flash חזק ממנו (40.9 מול 16.1), כותב טוב ממנו (1748 מול 1421) ובחצי המחיר.', refs: { aa: 'Gemini 2.5 Pro', cw: 'gemini-2.5-pro-preview-06-05', speech: 'google/gemini-2.5-pro-preview-06-05' }, sources: ['aa-llm'] },
  'google/gemini-2.5-flash': { fam: 'google', junk: 'R1', instead: ['google/gemini-3.5-flash-lite'], released: '2025-06-17',
    why: '3.5 Flash-Lite באותו מחיר בדיוק (0.30$/2.50$) וחזק ממנו (22.2 מול 13.1).', refs: { aa: 'Gemini 2.5 Flash (Reasoning)', speech: 'google/gemini-2.5-flash-preview-09-2025' }, sources: ['aa-llm'] },

  /* ---------------- xAI ---------------- */
  'xai/grok-4.7': { fam: 'xai', tier: 'top', released: '2026-09-21',
    lineage: 'בסיס גדול יותר מ-4.6 וחיזוק ארוך יותר למשימות של שעות; אותו מחיר.',
    power: 'הדגל החכם הזול בצמרת: AA 46.4 ב-2$/6$. CursorBench 4.0 46.3%, Harvey Legal 19.6% (מעל 5.6 Sol ו-Fable), EEBench 64%. עמיד להזיות (0.71). כתיבה 2007. הקשר 500K.',
    weak: 'פחות פתוח מקודמיו: 64% ב-SpeechMap (4.6: 84%, 4.5: 93%).',
    jobs: ['think', 'code', 'research', 'write'],
    tips: ['כשצריך מודל צמרת בשליש ממחיר Sol בפלט.', 'לתוכן בוגר: Grok 4.5 או 4.20 reasoning.'],
    hebrew: 'סבירה.', refs: { aa: 'Grok 4.7 (Xhigh)', cw: 'grok-4.7', speech: 'x-ai/grok-4.7' }, sources: ['grok47', 'aa-llm', 'speechmap'] },
  'xai/grok-4.6': { fam: 'xai', tier: 'top', released: '2026-08-12', keepBy: 'K',
    lineage: 'הדגל הקודם של xAI.',
    power: 'כמעט חכם כמו 4.7 (44.3 מול 46.4) ופתוח ממנו בהרבה: 84% ב-SpeechMap מול 64%. עמיד להזיות (0.76).',
    weak: 'הוחלף; תחת חקירה של נציבות הבטיחות המקוונת באוסטרליה (על התמונות).',
    jobs: ['loose', 'think', 'write'], tips: ['כשצריך מוח של צמרת שלא מסרב לנושא שנוי במחלוקת.'],
    hebrew: 'סבירה.', refs: { aa: 'Grok 4.6 (High)', speech: 'x-ai/grok-4.6' }, sources: ['speechmap', 'aa-llm', 'grok-policy'] },
  'xai/grok-4.5': { fam: 'xai', tier: 'mid', released: '2026-07-08', keepBy: 'K',
    lineage: 'Grok 4.5 (יולי 2026).',
    power: 'המודל החכם הפתוח ביותר בקטלוג: 93% ב-SpeechMap עם AA 38.8. הקשר 500K.',
    weak: 'כתיבה יצירתית בינונית (1579). חכם פחות מ-4.6 ו-4.7.',
    jobs: ['loose', 'write'], tips: ['הבחירה הראשונה לכתיבה בוגרת: רצח, אלימות קשה, סאטירה פוליטית, הומור גס.'],
    hebrew: 'סבירה.', refs: { aa: 'Grok 4.5 (High)', cw: 'grok-4.5', speech: 'x-ai/grok-4.5' }, sources: ['speechmap', 'aa-llm', 'eqbench'] },
  'xai/grok-4.3': { fam: 'xai', tier: 'low', released: '2026-05-01',
    lineage: 'Grok 4.3 (מאי 2026), הזול של xAI.',
    power: 'חצי ממחיר שאר Grok (1.25$/2.50$), הקשר של מיליון, פתוח (88% בחשיבה), עמיד להזיות מאוד (0.83).',
    weak: 'AA 24.9.', jobs: ['bulk', 'loose'], tips: ['נפח זול של תוכן שמודלים אחרים מסרבים לו.'],
    hebrew: 'סבירה.', refs: { aa: 'Grok 4.3 (High)', speech: 'x-ai/grok-4.3-reasoning', speechAlt: 'x-ai/grok-4.3' }, sources: ['aa-llm', 'speechmap'] },
  'xai/grok-4.20-0309-reasoning': { fam: 'xai', tier: 'mid', released: '2026-03-09', keepBy: 'K',
    lineage: 'Grok 4.20 (מרץ 2026).',
    power: 'הכי פתוח שנמדד אי פעם ב-SpeechMap בקטלוג: 98.2% תשובות מלאות. הקשר של 2 מיליון טוקנים, הגדול בקטלוג.',
    weak: 'AA 25.2; כתיבה 1574.', jobs: ['loose', 'long'],
    tips: ['כשכל מודל אחר מסרב לבקשה לגיטימית, או כשצריך להכניס ספר שלם.'],
    hebrew: 'סבירה.', refs: { aa: 'Grok 4.20 0309 (Reasoning)', cw: 'grok-4.20-beta', speech: 'x-ai/grok-4.20-beta-reasoning' }, sources: ['speechmap', 'aa-llm'] },
  'xai/grok-4.20-multi-agent-0309': { fam: 'xai', tier: 'mid', released: '2026-03-09', keepBy: 'K',
    lineage: 'גרסת רב-הסוכנים של 4.20.',
    power: 'כמה סוכנים עובדים במקביל על מחקר עמוק ומחזירים תשובה אחת; הקשר של 2 מיליון; קריאת פונקציות ופלט מובנה. אין לזה מקבילה בקטלוג.',
    weak: 'לא נמדד באופן בלתי תלוי; עלות הטוקנים של כל הסוכנים נספרת.', jobs: ['research', 'long'],
    tips: ['למחקר שוק ומתחרים לפני בריף, עם תקרת מחיר.'], gotchas: ['זמן תגובה ארוך; להריץ ברקע בזרימה.'],
    hebrew: 'סבירה.', refs: {}, sources: ['cf'] },
  'xai/grok-4.20-0309-non-reasoning': { fam: 'xai', junk: 'R2', instead: ['xai/grok-4.3', 'xai/grok-4.20-0309-reasoning'], released: '2026-03-09',
    why: 'Grok 4.3 זול ממנו בחצי, חכם ממנו (24.9 מול 14.6) ופתוח ממנו (79-88% מול 63%).', refs: { aa: 'Grok 4.20 0309 (Non-reasoning)', speech: 'x-ai/grok-4.20-beta' }, sources: ['aa-llm', 'speechmap'] },

  /* ---------------- Moonshot ---------------- */
  'moonshotai/kimi-k3': { fam: 'moonshot', tier: 'top', released: '2026-07-16',
    lineage: 'אחרי K2 (2025) ו-K2.5/K2.6 (2026). המודל הפתוח הגדול ביותר שהוכרז.',
    power: '2.8 טריליון פרמטרים, הקשר של מיליון, ראייה ווידאו מובנים. ראשון ב-Frontend Code (1679), שלישי ב-GDPval. כותב יצירתי מספר 5 (2082). AA 43.6.',
    weak: 'איטי (33 טוקנים לשנייה). צנזורה פוליטית סינית (66% ב-SpeechMap).',
    jobs: ['code', 'write', 'think'], tips: ['לבניית אתר וממשק: מוביל ב-Frontend Code.'],
    hebrew: 'סבירה.', refs: { aa: 'Kimi K3 (Max)', cw: 'kimi-k3', speech: 'moonshotai/kimi-k3' }, sources: ['kimi-k3', 'aa-llm', 'eqbench'] },
  '@cf/moonshotai/kimi-k2.6': { fam: 'moonshot', tier: 'mid', released: '2026-04-20',
    lineage: 'K2.6 (אפריל 2026), מתארח ב-Workers AI.',
    power: 'K2 החזק במחיר נמוך (0.95$/4$), AA 27.0, עמיד להזיות (0.59). מתארח אצל Cloudflare.',
    weak: 'בלי חשיבה קשוח מאוד (33% ב-SpeechMap); עם חשיבה 62%.',
    jobs: ['code', 'agent'], tips: ['להפעיל חשיבה: גם חכם יותר וגם פתוח יותר.'], gotchas: ['דורש Workers Paid או קרדיטים; לא במכסה החינמית.'],
    hebrew: 'סבירה.', refs: { aa: 'Kimi K2.6 (Reasoning)', cw: 'moonshotai/Kimi-K2.6', speech: 'moonshotai/kimi-k2.6-thinking', speechAlt: 'moonshotai/kimi-k2.6' }, sources: ['aa-llm', 'speechmap', 'lab-bench'] },
  '@cf/moonshotai/kimi-k2.7-code': { fam: 'moonshot', tier: 'mid', released: null,
    lineage: 'גרסת קוד של K2.', power: 'מכוון לקוד ולסוכני קוד באותו מחיר כמו K2.6.', weak: 'AA 25.8, לא חזק מ-K2.6 במדד הכללי; עמידות להזיות נמוכה (0.18).',
    jobs: ['code'], tips: ['לעבודת קוד ארוכה במחיר נמוך.'], gotchas: ['דורש Workers Paid או קרדיטים.'],
    hebrew: 'סבירה.', refs: { aa: 'Kimi K2.7 Code' }, sources: ['aa-llm'] },

  /* ---------------- Alibaba (Qwen) ---------------- */
  'alibaba/qwen3.8-max': { fam: 'alibaba', tier: 'top', released: '2026-08-03',
    lineage: 'אחרי Qwen3.7 Max (מאי 2026). הראשון ממשפחת Max עם משקלים פתוחים.',
    power: '2.4 טריליון פרמטרים, 95B פעילים. עוקף את GPT-5.6 Sol ב-PaperBench, AndroidBench ו-QwenSWEBench. AA 45.4 (עדכון 0902), עמיד להזיות (0.71).',
    weak: 'איטי (38 טוקנים לשנייה); צנזורה פוליטית סינית (65%); כתיבה 1843.',
    jobs: ['think', 'agent', 'code'], tips: ['מודל צמרת זול (2$/6$) לחשיבה ולסוכנים.'],
    hebrew: 'סבירה.', refs: { aa: 'Qwen3.8 Max (0902)', cw: 'Qwen/Qwen3.8-2.4T-A95B', speech: 'qwen/qwen3.8-max-0902' }, sources: ['qwen38', 'aa-llm'] },
  'alibaba/qwen3.7-max': { fam: 'alibaba', tier: 'mid', released: '2026-05-21',
    lineage: 'הדגל הקודם של Qwen.', power: 'AA 29.5 עם עמידות גבוהה להזיות (0.74), מהיר מאוד (200 טוקנים לשנייה), בשני שלישים ממחיר 3.8 Max.',
    weak: 'קשוח (51%).', jobs: ['bulk', 'plan-json'], tips: ['נפח מהיר עם מעט המצאות.'],
    hebrew: 'סבירה.', refs: { aa: 'Qwen3.7 Max', speech: 'qwen/qwen3.7-max' }, sources: ['aa-llm'] },
  'alibaba/qwen3.7-plus': { fam: 'alibaba', tier: 'mid', released: '2026-06-02',
    lineage: 'הבינוני של 3.7.', power: 'AA 25.2 ב-0.32$/1.28$, עמיד להזיות (0.72).', weak: 'קשוח (41%).',
    jobs: ['bulk'], hebrew: 'סבירה.', refs: { aa: 'Qwen3.7 Plus', speech: 'qwen/qwen3.7-plus' }, sources: ['aa-llm'] },
  'alibaba/qwen3-max': { fam: 'alibaba', junk: 'R1', instead: ['alibaba/qwen3.7-max'], released: '2025-09-05',
    why: 'Qwen3.7 Max זול ממנו בפלט (3.75$ מול 6$) וחזק ממנו פי שניים (29.5 מול 15.6).', refs: { aa: 'Qwen3 Max', speech: 'qwen/qwen3-max' }, sources: ['aa-llm'] },
  'alibaba/qwen3.5-397b-a17b': { fam: 'alibaba', junk: 'R2', instead: ['alibaba/qwen3.7-plus'], released: '2026-02-16',
    why: 'Qwen3.7 Plus זול ממנו (0.32$/1.28$ מול 0.60$/3.60$), חזק ממנו (25.2 מול 21.4) ופתוח באותה מידה.', refs: { aa: 'Qwen3.5 397B A17B (Reasoning)', cw: 'Qwen/Qwen3.5-397B-A17B', speech: 'qwen/qwen3.5-397b-a17b' }, sources: ['aa-llm'] },

  /* ---------------- DeepSeek ---------------- */
  '@cf/deepseek-ai/deepseek-v4-pro-0813': { fam: 'deepseek', tier: 'mid', released: '2026-08-13',
    lineage: 'עדכון 0813 של V4 Pro, מתארח ב-Workers AI.', power: 'AA 36.0, הכי חזק של DeepSeek בקטלוג; מטמון זול מאוד (0.044$).',
    weak: 'הזיות גבוהות (0.05 עמידות); צנזורה פוליטית (58%, 72% בחשיבה); כתיבה 1553.',
    jobs: ['code', 'think'], tips: ['להפעיל חשיבה: חכם ופתוח יותר.'], gotchas: ['דורש Workers Paid או קרדיטים.'],
    hebrew: 'סבירה.', refs: { aa: 'DeepSeek V4 Pro 0813 (Max)', cw: 'deepseek-ai/DeepSeek-V4-Pro', speech: 'deepseek/deepseek-v4-pro-0813-reasoning', speechAlt: 'deepseek/deepseek-v4-pro-0813' }, sources: ['aa-llm', 'speechmap'] },
  '@cf/deepseek-ai/deepseek-v4-flash-0731': { fam: 'deepseek', tier: 'mid', released: '2026-07-31',
    lineage: 'V4-Flash הרשמי (284B, 13B פעילים, MIT).', power: 'AA 34.3 בשליש ממחיר ה-Pro; 204 טוקנים לשנייה; הקשר של מיליון.',
    weak: 'הזיות גבוהות; כתיבה 1441.', jobs: ['bulk', 'code'], gotchas: ['דורש Workers Paid או קרדיטים.'],
    hebrew: 'סבירה.', refs: { aa: 'DeepSeek V4 Flash 0731 (Max)', cw: 'deepseek-ai/DeepSeek-V4-Flash-0731', speech: 'deepseek/deepseek-v4-flash-0731-reasoning', speechAlt: 'deepseek/deepseek-v4-flash-0731' }, sources: ['deepseek-v4', 'aa-llm'] },
  'deepseek/deepseek-v4-pro': { fam: 'deepseek', junk: 'R1', instead: ['@cf/deepseek-ai/deepseek-v4-pro-0813'], released: '2026-04-24',
    why: 'מוגש דרך Fireworks עם הקשר של 131K; גרסת 0813 ב-Workers AI חדשה יותר, זולה יותר לעבודה טיפוסית (0.0066$ מול 0.0070$) עם מטמון זול פי שלושה.', refs: { speech: 'deepseek/deepseek-v4-pro' }, sources: ['cf', 'speechmap'] },

  /* ---------------- Z.ai ---------------- */
  '@cf/zai-org/glm-5.3': { fam: 'zai', tier: 'top', released: '2026-08-18',
    lineage: 'אחרי GLM-5.2 (יוני 2026).', power: 'AA 44.8, כותב יצירתי מספר 6 (2075) עם סלופ נמוך, עמיד להזיות (0.70), פתוח יחסית (72%).',
    weak: 'הקשר קטן מהמתחרים; צנזורה פוליטית סינית.', jobs: ['write', 'think', 'code'],
    tips: ['כותב צמרת זול (1.40$/4.40$): חלופה ל-Sol בכתיבה.'], gotchas: ['דורש Workers Paid או קרדיטים.'],
    hebrew: 'סבירה.', refs: { aa: 'GLM-5.3 (Max)', cw: 'GLM-5.3', speech: 'z-ai/glm-5.3' }, sources: ['glm53', 'aa-llm', 'eqbench'] },
  '@cf/zai-org/glm-5.3-flash': { fam: 'zai', tier: 'mid', released: '2026-08-26',
    lineage: 'MoE של 320B עם 18B פעילים, מולטימודלי, MIT.', power: 'AA 41.8 ב-0.15$/0.50$: כמעט כמו GLM-5.3 בעשירית מהמחיר. GDPval 1773 (מעל Opus 4.8). עמיד להזיות (0.72).',
    weak: 'איטי (47 טוקנים לשנייה).', jobs: ['bulk', 'plan-json', 'code', 'think'],
    tips: ['אחד הערכים הטובים בקטלוג: חכם כמו מודלי צמרת של יוני במחיר של Luna.'], gotchas: ['דורש Workers Paid או קרדיטים.'],
    hebrew: 'סבירה.', refs: { aa: 'GLM 5.3 Flash', speech: 'z-ai/glm-5.3-flash' }, sources: ['glm53', 'aa-llm'] },
  '@cf/zai-org/glm-5.2': { fam: 'zai', junk: 'R1', instead: ['@cf/zai-org/glm-5.3'], released: '2026-06-16',
    why: 'GLM-5.3 באותו מחיר בדיוק, חזק ממנו (44.8 מול 33.7) וכותב טוב ממנו (2075 מול 1757). פתוח ממנו ב-6 נקודות בלבד ב-SpeechMap.', refs: { aa: 'GLM-5.2 (Max)', cw: 'zai-org/GLM-5.2', speech: 'z-ai/glm-5.2' }, sources: ['aa-llm', 'eqbench'] },

  /* ---------------- MiniMax ---------------- */
  'minimax/m3': { fam: 'minimax', tier: 'mid', released: '2026-06-01',
    lineage: 'אחרי M2.x. משקלים פתוחים, הקשר של מיליון.', power: 'זול מאוד (0.30$/1.20$ עד 512K), עמיד להזיות מאוד (0.82), קלט טקסט, תמונה ווידאו. SWE-bench Pro 59%. AA 29.2.',
    weak: 'הכי קשוח במשפחות הסיניות (27%, 50% בחשיבה).', jobs: ['long', 'bulk', 'code'],
    tips: ['למסמכים ארוכים מאוד במחיר הכי נמוך; מעל 512K המחיר פי ארבעה.'], gotchas: ['mask_sensitive_info מסתיר מידע אישי בפלט.'],
    hebrew: 'סבירה.', refs: { aa: 'MiniMax-M3', speech: 'minimax/minimax-m3-reasoning', speechAlt: 'minimax/minimax-m3' }, sources: ['minimax-m3', 'aa-llm'] },
  'minimax/m2.7': { fam: 'minimax', junk: 'R1', instead: ['minimax/m3'], released: '2026-03-18',
    why: 'M3 באותו מחיר, חזק ממנו (29.2 מול 22.8), עם הקשר של מיליון.', refs: { aa: 'MiniMax-M2.7', speech: 'minimax/minimax-m2.7' }, sources: ['aa-llm'] },

  /* ---------------- Thinking Machines ---------------- */
  'thinkingmachines/inkling': { fam: 'thinkingmachines', tier: 'mid', released: '2026-07-15',
    lineage: 'המודל הראשון של המעבדה.', power: 'המודל הפתוח המוביל מארה״ב בהשקה. GPQA 87.9%, SWE-bench Verified 77.6%. מקבל גם שמע. 173 טוקנים לשנייה.',
    weak: 'בקטלוג רק 64K הקשר (המשקלים: מיליון). יקר יחסית לחוזקו (1.87$/4.68$, AA 25.0). קשוח (43%).',
    jobs: ['code', 'see'], gotchas: ['החשיבה מוחזרת כבלוקי thinking בתחילת התשובה; את המאמץ מכוונים ב-output_config.effort.'],
    hebrew: 'לא נבדקה.', refs: { aa: 'Inkling (Xhigh)', cw: 'thinkingmachines/Inkling', speech: 'thinkingmachines/inkling-64k-reasoning', speechAlt: 'thinkingmachines/inkling-64k' }, sources: ['inkling', 'aa-llm'] },
  'thinkingmachines/inkling-256k': { fam: 'thinkingmachines', junk: 'R3', instead: ['thinkingmachines/inkling', 'minimax/m3'], released: '2026-07-15',
    why: 'Cloudflare עצמה מציינת שהגרסה מיועדת "לבדיקות בנפח נמוך ולשימוש פנימי, לא לייצור". פי שניים מהמחיר.', sources: ['cf'] },

  /* ---------------- Unbiased, TypeSafe ---------------- */
  'unbiased/pareto': { fam: 'unbiased', tier: 'mid', released: '2026-09-16',
    lineage: 'הופיע כ-union-alpha; Pareto 26.9.', power: 'מריץ כמה מודלי חזית ופתוחים במקביל ובוחר את התשובה הטובה: חוות דעת שנייה מובנית. 262K הקשר. 67% ב-SpeechMap.',
    weak: 'אטום: לא יודעים איזה מודל ענה. לא נמדד ב-AA.', jobs: ['think', 'judge'],
    tips: ['לבדוק החלטה חשובה מול תשובת Opus או Sol.'], hebrew: 'לא נבדקה.', refs: { speech: 'stealth/union-alpha' }, sources: ['pareto', 'speechmap'] },
  'typesafe/jev': { fam: 'typesafe', tier: 'low', released: null,
    lineage: 'מודל System One ראשון.', power: 'שופט מכויל: מחזיר בחירה, ציון או כן/לא עם הסתברות שתואמת את הדיוק בפועל, ב-70-500 מילישניות, בלי שגיאת מבנה. כמעט בחינם (0.042$ למיליון קלט, 0 לפלט).',
    weak: 'לא כותב טקסט חופשי; 32K הקשר.', jobs: ['judge'],
    tips: ['שער איכות בזרימה: "האם התסריט עומד בבריף? 1-10", "האם הכותרת בעברית תקינה? כן/לא".'], hebrew: 'לא נבדקה.', refs: {}, sources: ['jev'] },

  /* ---------------- free (Workers AI) ---------------- */
  '@cf/openai/gpt-oss-120b': { fam: 'openai-open', tier: 'free', released: '2025-08-05',
    lineage: 'המשקלים הפתוחים של OpenAI.', power: 'החינמי הכי אמין במעבדה: ענה נכון בכל בדיקות לוטי, בתרגום ובעברית. 0.35$/0.75$ מעבר למכסה. AA 11.6.',
    weak: 'הכי קשוח מבין החינמיים (36% ב-SpeechMap); כתיבה יצירתית 961.', jobs: ['bulk', 'copy-he', 'plan-json'],
    tips: ['reasoning effort low: אותה תשובה נכונה בשליש מהזמן (המדידה של לוטי).'], gotchas: ['פלט בפורמט Responses (output[].content[].text).'],
    hebrew: 'טובה; נמדדה בלוטי.', refs: { aa: 'gpt-oss-120b (High)', cw: 'openai/gpt-oss-120b', speech: 'openai/gpt-oss-120b' }, sources: ['lab-bench', 'aa-llm', 'speechmap'] },
  '@cf/google/gemma-4-26b-a4b-it': { fam: 'google-open', tier: 'free', released: '2026-04-02',
    lineage: 'Gemma 4, MoE של 25B עם 3.8B פעילים.', power: 'הכי זול בין החינמיים החכמים (0.10$/0.30$), תמונה ווידאו פנימה, 256K הקשר, 140+ שפות, פתוח (76%, 87% בחשיבה).',
    weak: 'במעבדה לא ענה בזמן (30 שניות) בבדיקת לוטי; כתיבה 1305.', jobs: ['see', 'bulk'],
    gotchas: ['לתת max_tokens גדול ולצפות לזמן תגובה ארוך.'], hebrew: 'בין 140+ השפות; לא ענה בזמן במעבדה.',
    refs: { aa: 'Gemma 4 26B A4B (Reasoning)', cw: 'google/gemma-4-26B-A4B-it', speech: 'google/gemma-4-26b-a4b-it', speechAlt: 'google/gemma-4-26b-a4b-it-reasoning' }, sources: ['gemma4', 'lab-bench', 'speechmap'] },
  '@cf/qwen/qwen3.8-27b': { fam: 'qwen-open', tier: 'free', released: '2026-08-14',
    lineage: 'הצ׳קפוינט הפתוח הקטן של Qwen 3.8.', power: 'החינמי החכם ביותר בקטלוג בהפרש: AA 33.7, כתיבה 1671; ראייה; 262K הקשר.',
    weak: 'יקר במכסה (3.20$ למיליון פלט: עשירית מהמכסה היומית בכמה תשובות); קשוח (39%); במעבדה לא ענה בזמן.', jobs: ['think', 'code', 'see'],
    hebrew: 'סבירה.', refs: { aa: 'Qwen3.8 27B (Xhigh)', cw: 'Qwen/Qwen3.8-27B', speech: 'qwen/qwen3.8-27b', speechAlt: 'qwen/qwen3.8-27b-reasoning' }, sources: ['aa-llm', 'lab-bench'] },
  '@cf/qwen/qwen3-30b-a3b-fp8': { fam: 'qwen-open', tier: 'free', released: '2025-04-28', keepBy: 'K',
    lineage: 'Qwen3 30B-A3B (אפריל 2025).', power: 'זול מאוד (0.05$/0.34$) ופתוח מאוד: 87% ב-SpeechMap, מול 39% של Qwen3.8 27B.',
    weak: 'הקשר 32K; חלש (AA 7.6).', jobs: ['loose', 'bulk'], hebrew: 'סבירה.',
    refs: { aa: 'Qwen3 30B A3B (Reasoning)', speech: 'qwen/qwen3-30b-a3b' }, sources: ['speechmap'] },
  '@cf/zai-org/glm-4.7-flash': { fam: 'zai', tier: 'free', released: '2026-01-19',
    lineage: 'GLM-4.7 Flash (ינואר 2026).', power: 'זול (0.06$/0.40$), 131K הקשר, כלים, חשיבה, פתוח (86%).',
    weak: 'במעבדה לא ענה בזמן; הזיות גבוהות.', jobs: ['loose', 'bulk'], hebrew: 'סבירה.',
    refs: { aa: 'GLM-4.7-Flash (Reasoning)', cw: 'zai-org/GLM-4.7-Flash', speech: 'z-ai/glm-4.7-flash' }, sources: ['speechmap', 'lab-bench'] },
  '@cf/nvidia/nemotron-3-120b-a12b': { fam: 'nvidia', tier: 'free', released: '2026-03-11',
    lineage: 'Nemotron 3 Super.', power: 'היברידי Mamba-MoE, 256K הקשר בקטלוג, כלים, בנוי לסוכנים ולנפח.',
    weak: 'במעבדה לא ענה על לוטי (14 שניות, 322 נוירונים); קשוח (43%).', jobs: ['agent', 'bulk'], hebrew: 'לא נבדקה.',
    refs: { aa: 'Nemotron 3 Super 120B A12B (Reasoning)', speech: 'nvidia/nemotron-3-super-120b-a12b' }, sources: ['nemotron3', 'lab-bench'] },
  '@cf/ibm-granite/granite-4.0-h-micro': { fam: 'ibm', tier: 'free', released: '2025-10-07',
    lineage: 'Granite 4.0 Micro (3B היברידי).', power: 'הכי זול בקטלוג (0.017$/0.112$): רצפת המחיר של הטקסט. כלים, 131K הקשר.',
    weak: 'קטן מאוד.', jobs: ['bulk'], tips: ['סיווג וחילוץ בנפח עצום מתוך המכסה החינמית.'], hebrew: 'חלשה.',
    refs: { aa: 'Granite 4.0 Micro' }, sources: ['wai-pricing'] },
  '@cf/mistralai/mistral-small-3.1-24b-instruct': { fam: 'mistral', tier: 'free', released: '2025-03-17',
    lineage: 'Mistral Small 3.1 (2503).', power: 'החינמי הפתוח ביותר: 90% ב-SpeechMap. קרא נכון כל שורה של אריזה במעבדה.',
    weak: 'שגה בבדיקת לוטי; כתיבה יצירתית 761.', jobs: ['loose', 'see'], hebrew: 'בינונית.',
    refs: { aa: 'Mistral Small 3.1', cw: 'mistralai/mistral-small-3.1-24b-instruct-2503', speech: 'mistralai/mistral-small-2503' }, sources: ['speechmap', 'lab-bench'] },
  '@cf/meta/llama-4-scout-17b-16e-instruct': { fam: 'meta', tier: 'free', released: '2025-04-05',
    lineage: 'Llama 4 Scout (MoE, 16 מומחים).', power: 'מהיר (1.7 שניות בלוטי), ראייה, 131K הקשר, כלים, פתוח (70%). ענה נכון על לוטי.',
    weak: 'עברית עם שגיאות; כתיבה 783.', jobs: ['see', 'bulk'], hebrew: 'עם שגיאות (נמדד).',
    refs: { aa: 'Llama 4 Scout', cw: 'meta-llama/Llama-4-Scout-17B-16E-Instruct', speech: 'meta-llama/llama-4-scout' }, sources: ['lab-bench', 'speechmap'] },
  '@cf/meta/llama-guard-3-8b': { fam: 'meta', tier: 'free', released: '2024-07-23', keepBy: 'K',
    lineage: 'Llama Guard 3.', power: 'מסווג בטיחות: מחזיר safe/unsafe וקטגוריה (S1-S14). כמעט בחינם בפלט.', weak: 'לא כותב.',
    jobs: ['judge', 'guard'], tips: ['לבדוק פרומפט או טקסט לפני פרסום, ולהבין למה מודל אחר מסרב.'], hebrew: 'חלשה.', refs: {}, sources: ['cf'] },
  '@cf/swiss-ai/apertus-v1.5-8b': { fam: 'swiss-ai', tier: 'free', released: '2026-07-24',
    lineage: 'Apertus 1.5.', power: 'פתוח לגמרי (גם נתוני האימון), 1,811 שפות, ראייה, 262K הקשר.', weak: 'קטן (8B); Cloudflare דורשת טופס גישה.',
    jobs: ['bulk'], hebrew: 'בין השפות; לא נבדקה.', refs: { aa: 'Apertus 8B Instruct' }, sources: ['apertus15', 'cf'] },
  '@cf/utter-project/eurollm-9b-it': { fam: 'utter', junk: 'R4', instead: ['@cf/openai/gpt-oss-120b'], released: null,
    why: 'מודל ל-35 שפות אירופיות ואחרות, בלי עברית.', sources: ['eurollm'] },
  '@cf/openai/gpt-oss-20b': { fam: 'openai-open', junk: 'R2', instead: ['@cf/openai/gpt-oss-120b'], released: '2025-08-05',
    why: 'gpt-oss-120b חזק ממנו וכותב טוב ממנו (961 מול 666) בתוספת של 0.0008$ לעבודה, ופתוח יותר (36% מול 27%).', refs: { aa: 'gpt-oss-20b (Low)', cw: 'openai/gpt-oss-20b', speech: 'openai/gpt-oss-20b' }, sources: ['aa-llm', 'eqbench'] },
  '@cf/meta/llama-3.3-70b-instruct-fp8-fast': { fam: 'meta', junk: 'R2', instead: ['@cf/meta/llama-4-scout-17b-16e-instruct'], released: '2024-12-06',
    why: 'Llama 4 Scout זול ממנו (0.85$ מול 2.25$ לפלט), מהיר ממנו פי שבעה בלוטי, פתוח ממנו (70% מול 61%), עם ראייה. שניהם עונים נכון; ל-3.3 שגיאות עברית.', refs: { aa: 'Llama 3.3 Instruct 70B', speech: 'meta-llama/llama-3.3-70b-instruct' }, sources: ['lab-bench', 'speechmap'] },
  '@cf/meta/llama-3.2-11b-vision-instruct': { fam: 'meta', junk: 'R2', instead: ['@cf/meta/llama-4-scout-17b-16e-instruct'], released: '2024-09-25',
    why: 'Scout רואה טוב ממנו בתוספת זניחה ופתוח פי ארבעה (70% מול 19%).', refs: { aa: 'Llama 3.2 Instruct 11B (Vision)', speech: 'meta-llama/llama-3.2-11b-vision-instruct' }, sources: ['speechmap'] },
  '@cf/meta/llama-3.2-3b-instruct': { fam: 'meta', junk: 'R2', instead: ['@cf/meta/llama-4-scout-17b-16e-instruct', '@cf/ibm-granite/granite-4.0-h-micro'], released: '2024-09-25',
    why: 'Scout בתוספת של 0.001$ לעבודה וחזק ממנו בהרבה; Granite Micro זול ממנו.', refs: { aa: 'Llama 3.2 Instruct 3B', cw: 'meta-llama/llama-3.2-3b-instruct' }, sources: ['aa-llm'] },
  '@cf/meta/llama-3.2-1b-instruct': { fam: 'meta', junk: 'R2', instead: ['@cf/ibm-granite/granite-4.0-h-micro'], released: '2024-09-25',
    why: 'Granite Micro זול ממנו וטוב ממנו; כתיבה 200 ב-EQ-Bench, האחרון בלוח.', refs: { aa: 'Llama 3.2 Instruct 1B', cw: 'meta-llama/llama-3.2-1b-instruct' }, sources: ['eqbench'] },
  '@cf/meta/llama-3.1-8b-instruct-fp8': { fam: 'meta', junk: 'R2', instead: ['@cf/meta/llama-4-scout-17b-16e-instruct'], released: '2024-07-23',
    why: 'Scout בתוספת של 0.0008$ לעבודה, חזק ממנו ופתוח פי ארבעה (70% מול 16%).', refs: { aa: 'Llama 3.1 Instruct 8B', cw: 'meta-llama/llama-3.1-8b-instruct', speech: 'meta-llama/llama-3.1-8b-instruct' }, sources: ['speechmap'] },
  '@cf/deepseek-ai/deepseek-r1-distill-qwen-32b': { fam: 'qwen-open', junk: 'R2', instead: ['@cf/qwen/qwen3.8-27b'], released: '2025-01-20',
    why: 'Qwen 2.5 שזוקק מ-DeepSeek-R1: Qwen3.8 27B מאותה משפחה זול ממנו בעבודה (4.88$ מול 3.20$ למיליון פלט) וחזק ממנו פי ארבעה (33.7 מול 8.4).', refs: { aa: 'DeepSeek R1 Distill Qwen 32B' }, sources: ['aa-llm'] },
  '@cf/qwen/qwq-32b': { fam: 'qwen-open', junk: 'R2', instead: ['@cf/qwen/qwen3.8-27b', '@cf/qwen/qwen3-30b-a3b-fp8'], released: '2025-03-05',
    why: 'Qwen3.8 27B חזק ממנו פי שלושה וחצי בתוספת של 0.0018$ לעבודה; Qwen3 30B זול ממנו ופתוח באותה מידה (87% מול 84%).', refs: { aa: 'QwQ 32B', cw: 'qwen/qwq-32b', speech: 'qwen/qwq-32b' }, sources: ['aa-llm', 'speechmap'] },
  '@cf/qwen/qwen2.5-coder-32b-instruct': { fam: 'qwen-open', junk: 'R2', instead: ['@cf/qwen/qwen3.8-27b'], released: '2024-11-12',
    why: 'Qwen3.8 27B כותב קוד טוב בהרבה בתוספת של 0.0018$ לעבודה, עם 262K הקשר במקום 32K.', sources: ['aa-llm'] },
  '@cf/aisingapore/gemma-sea-lion-v4-27b-it': { fam: 'google-open', junk: 'R4', instead: ['@cf/google/gemma-4-26b-a4b-it'], released: '2025-09-23',
    why: 'Gemma 3 מכוונן לשפות דרום-מזרח אסיה; Gemma 4 זול ממנו וחזק ממנו.', sources: ['cf'] },
  '@cf/google/gemma-2b-it-lora': { fam: 'google-open', junk: 'R3', instead: ['@cf/google/gemma-4-26b-a4b-it'], released: '2024-04-02',
    why: 'בסיס ל-LoRA: בלי מתאם שמאמנים ומעלים לבד אין לו תפקיד, והוא מ-2024.', sources: ['cf'] },
  '@cf/google/gemma-7b-it-lora': { fam: 'google-open', junk: 'R3', instead: ['@cf/google/gemma-4-26b-a4b-it'], released: '2024-04-02',
    why: 'בסיס ל-LoRA מ-2024 עם 3,500 טוקני הקשר.', sources: ['cf'] },
  '@cf/meta-llama/llama-2-7b-chat-hf-lora': { fam: 'meta', junk: 'R3', instead: ['@cf/meta/llama-4-scout-17b-16e-instruct'], released: '2024-04-02',
    why: 'בסיס ל-LoRA של Llama 2 (2023).', sources: ['cf'] },
  '@cf/mistral/mistral-7b-instruct-v0.2-lora': { fam: 'mistral', junk: 'R3', instead: ['@cf/mistralai/mistral-small-3.1-24b-instruct'], released: '2024-04-01',
    why: 'בסיס ל-LoRA של Mistral 7B (2023).', sources: ['cf'] },
};
