// AILGEN Lab · the arsenal's curated knowledge, part 6: the free helpers on Workers AI (embeddings, reranking, vision, classification,
// translation). They are not "creative" engines; they make the others usable: search a catalog by meaning, read a package, check a text.

export const UTILITY = {
  '@cf/baai/bge-m3': { fam: 'baai', tier: 'free', released: '2024-05-22',
    lineage: 'BGE M3 (BAAI).', power: 'חיפוש לפי משמעות ביותר מ-100 שפות כולל עברית; נמדד במעבדה על 71 המוצרים של עדן. 0.012$ למיליון טוקנים.',
    weak: 'שלושת ה-embeddings לא הושוו זה מול זה מעבר לחיפוש של עדן.', jobs: ['embed'], hebrew: 'כן (נמדד).', refs: {}, sources: ['lab-bench', 'wai-pricing'] },
  '@cf/qwen/qwen3-embedding-0.6b': { fam: 'qwen-open', tier: 'free', released: '2025-06-18',
    lineage: 'Qwen3 Embedding.', power: 'embeddings רב-לשוניים, 8K הקשר, אותו מחיר כמו bge-m3; נמדד באותו חיפוש.', weak: 'הקשר 8K בלבד.',
    jobs: ['embed'], hebrew: 'כן (נמדד).', refs: {}, sources: ['lab-bench'] },
  '@cf/google/embeddinggemma-300m': { fam: 'google-open', tier: 'free', released: '2025-09-04',
    lineage: 'EmbeddingGemma 300M.', power: 'הקטן החזק לגודלו, 100+ שפות; נמדד באותו חיפוש.', weak: 'קטן (300M): פחות דיוק בטקסט ארוך.', jobs: ['embed'], hebrew: 'כן (נמדד).', refs: {}, sources: ['lab-bench'] },
  '@cf/baai/bge-reranker-base': { fam: 'baai', tier: 'free', released: '2025-02-14',
    lineage: 'BGE reranker.', power: 'מקבל שאלה ומסמך ומחזיר ציון רלוונטיות: מסדר מחדש את תוצאות החיפוש. כמעט בחינם.', weak: 'אנגלית-סינית בעיקר.',
    jobs: ['rerank'], hebrew: 'חלשה.', refs: {}, sources: ['wai-pricing'] },
  '@cf/moondream/moondream3.1-9B-A2B': { fam: 'moondream', tier: 'free', released: '2026-07-07',
    lineage: 'Moondream 3 (2025) → 3.1.', power: 'ראייה מהירה וזולה (0.30$/1$): תיאור, שאלה על תמונה, הצבעה על אובייקט, זיהוי, OCR, פלט מובנה.', weak: 'אנגלית.',
    jobs: ['see'], tips: ['לבדיקת איכות של תמונה שנוצרה: "האם יש טקסט? איפה המוצר?".'], hebrew: 'לא.', refs: {}, sources: ['moondream3', 'cf'] },
  '@cf/baai/bge-base-en-v1.5': { fam: 'baai', junk: 'R2', instead: ['@cf/baai/bge-m3'], released: '2023-09-25',
    why: 'אנגלית בלבד ויקר פי חמישה מ-bge-m3 של אותו יצרן, שמכסה גם עברית.', sources: ['wai-pricing'] },
  '@cf/baai/bge-large-en-v1.5': { fam: 'baai', junk: 'R2', instead: ['@cf/baai/bge-m3'], released: '2023-11-07',
    why: 'אנגלית בלבד ויקר פי 17 מ-bge-m3.', sources: ['wai-pricing'] },
  '@cf/baai/bge-small-en-v1.5': { fam: 'baai', junk: 'R2', instead: ['@cf/baai/bge-m3'], released: '2023-11-07',
    why: 'אנגלית בלבד ויקר מ-bge-m3 (0.020$ מול 0.012$).', sources: ['wai-pricing'] },
  '@cf/pfnet/plamo-embedding-1b': { fam: 'misc', junk: 'R4', instead: ['@cf/baai/bge-m3'], released: '2025-09-24',
    why: 'embeddings ליפנית.', sources: ['cf'] },
  '@cf/huggingface/distilbert-sst-2-int8': { fam: 'misc', junk: 'R4', instead: ['@cf/ibm-granite/granite-4.0-h-micro'], released: '2023-09-25',
    why: 'סנטימנט חיובי/שלילי באנגלית בלבד; כל מודל שפה שנשאר עושה זאת בעברית.', sources: ['cf'] },
  '@cf/microsoft/resnet-50': { fam: 'misc', junk: 'R4', instead: ['@cf/moondream/moondream3.1-9B-A2B'], released: '2023-09-25',
    why: 'מסווג תמונה ל-1,000 תוויות ImageNet; Moondream מתאר, מזהה ומצביע.', sources: ['cf'] },
  '@cf/llava-hf/llava-1.5-7b-hf': { fam: 'misc', junk: 'R4', instead: ['@cf/moondream/moondream3.1-9B-A2B', '@cf/meta/llama-4-scout-17b-16e-instruct'], released: '2024-05-01',
    why: 'מודל ראייה מ-2023; Moondream 3.1 ו-Llama 4 Scout רואים טוב ממנו (Scout קרא אריזה במעבדה).', sources: ['lab-bench'] },
  '@cf/meta/m2m100-1.2b': { fam: 'meta', junk: 'R4', instead: ['@cf/openai/gpt-oss-120b'], released: '2023-09-25',
    why: 'מתרגם ייעודי מ-2020; gpt-oss-120b תרגם נכון במעבדה ומבין הקשר שיווקי.', sources: ['lab-bench'] },
  '@cf/ai4bharat/indictrans2-en-indic-1B': { fam: 'misc', junk: 'R4', instead: ['@cf/openai/gpt-oss-120b'], released: '2025-09-23',
    why: 'תרגום מאנגלית לשפות הודיות בלבד.', sources: ['cf'] },
};
