// AILGEN Lab · the arsenal's curated knowledge, part 4: video models. refs: t2v / i2v / vedit = Artificial Analysis arena rows.
// Tiers for video: top = text-to-video Elo 1100+ (or image-to-video 1200+ for a model the board only measures from an image),
// mid = 1000-1100 (i2v 1080-1200), low = under that, or a draft tool or utility. The i2v board keeps older models in its pool,
// so its numbers run higher than the text-to-video board: compare models inside one board, never across boards.

export const VIDEO = {
  /* ---------------- Alibaba ---------------- */
  'alibaba/wan-3.0': { fam: 'alibaba', tier: 'top', released: '2026-08-03',
    lineage: 'Wan 2.5 (2025) → 2.6 → 2.7 (אפריל 2026) → 3.0 (אוגוסט 2026).',
    power: 'מספר 1 בעולם גם בטקסט לווידאו (1157) וגם בעריכת וידאו (1188). עד 15 שניות במסמך של Cloudflare, 480p/720p/1080p, יחס אדפטיבי. זול לשנייה (0.10$ ב-720p).',
    weak: 'אצל Cloudflare רק טקסט לווידאו (ספקים אחרים נותנים גם תמונה, וידאו ושמע כקלט). בלי סאונד במסמך. איטי (כ-200 שניות לקליפ של 5 שניות).',
    jobs: ['film', 'draft'], tips: ['השוט הראשון לכל סרט: האיכות הגבוהה בעולם במחיר בינוני.', '480p (0.05$ לשנייה) לטיוטה, 1080p לגרסה הסופית.'],
    gotchas: ['להריץ ברקע: 3-4 דקות לקליפ.'], hebrew: 'לא רלוונטי.', filter: { n: null, conf: 'low', why: 'בדיקת תוכן של Alibaba Cloud; לא נמדד.' },
    refs: { t2v: 'Wan 3.0', i2v: 'Wan 3.0', vedit: 'Wan 3.0' }, sources: ['wan30', 'aa-t2v', 'aa-vedit'] },
  'alibaba/wan-3.0-prime': { fam: 'alibaba', tier: 'top', released: '2026-08-24', keepBy: 'K',
    lineage: 'Wan 3.0 מואץ.', power: 'אותו מודל ואותם פרמטרים כמו Wan 3.0, כמעט פי שניים מהר (108 שניות מול 200).', weak: 'פי 1.4 מהמחיר.',
    jobs: ['film'], tips: ['כשהזמן קובע (תצוגה ללקוח עכשיו); אחרת Wan 3.0.'], hebrew: 'לא רלוונטי.', filter: { n: null, conf: 'low', why: 'כמו Wan 3.0.' },
    refs: {}, sources: ['wan30'] },
  'alibaba/hh1.1-t2v': { fam: 'alibaba', tier: 'mid', released: '2026-06-22',
    lineage: 'HappyHorse 1.0 (אפריל 2026) → 1.1 (יוני).', power: 'תנועה דינמית ועקיבות טובה מ-1.0; 3-15 שניות; 1045 בארנה.', weak: '0.14$ לשנייה ב-720p, יותר מ-Wan 3.0 שטוב ממנו ב-110 נקודות.',
    jobs: ['film'], hebrew: 'לא רלוונטי.', filter: { n: null, conf: 'low', why: 'Alibaba Cloud; לא נמדד.' }, refs: { t2v: 'HappyHorse-1.1', i2v: 'HappyHorse-1.1' }, sources: ['aa-t2v'] },
  'alibaba/hh1.1-i2v': { fam: 'alibaba', tier: 'mid', released: '2026-06-22',
    lineage: 'HappyHorse 1.1 מתמונה.', power: 'הנפשת סטילס; 1104 בארנה של תמונה לווידאו.', weak: 'Hailuo 2.3 Fast טוב ממנו בארנה הזו וזול ממנו.',
    jobs: ['i2v'], hebrew: 'לא רלוונטי.', filter: { n: null, conf: 'low', why: 'לא נמדד.' }, refs: { i2v: 'HappyHorse-1.1' }, sources: ['aa-i2v'] },
  'alibaba/hh1.1-r2v': { fam: 'alibaba', tier: 'mid', released: '2026-06-22',
    lineage: 'HappyHorse 1.1 מייחוסים.', power: '1-9 תמונות ייחוס של דמויות וסצנות מתוזמרות לווידאו אחד, כל דמות שומרת על זהותה; 720p/1080p, 3-15 שניות.', weak: 'לא נמדד בארנה.',
    jobs: ['refs'], tips: ['כשכמה דמויות או מוצרים חייבים להופיע יחד בשוט אחד.'], hebrew: 'לא רלוונטי.', filter: { n: null, conf: 'low', why: 'לא נמדד.' }, refs: {}, sources: ['cf'] },
  'alibaba/wan-2.7-i2v': { fam: 'alibaba', tier: 'low', released: '2026-04-25',
    lineage: 'Wan 2.7 מתמונה.', power: 'הדרך של Wan להנפיש תמונה בקטלוג (Wan 3.0 כאן רק מטקסט), עם negative_prompt ו-seed; 2-15 שניות.', weak: '1077 בארנה של תמונה לווידאו.',
    jobs: ['i2v'], hebrew: 'לא רלוונטי.', filter: { n: null, conf: 'low', why: 'לא נמדד.' }, refs: { i2v: 'Wan 2.7', vedit: 'Wan 2.7' }, sources: ['aa-i2v'] },
  'alibaba/hh1-t2v': { fam: 'alibaba', junk: 'R1', instead: ['alibaba/hh1.1-t2v'], released: '2026-04-07',
    why: 'HappyHorse 1.1 באותו מחיר ב-720p, זול ממנו ב-1080p (0.18$ מול 0.28$ לשנייה) וטוב ממנו (1045 מול 1026).', refs: { t2v: 'HappyHorse-1.0' }, sources: ['aa-t2v'] },
  'alibaba/hh1-i2v': { fam: 'alibaba', junk: 'R1', instead: ['alibaba/hh1.1-i2v'], released: '2026-04-07',
    why: 'HappyHorse 1.1 באותו מחיר ב-720p, זול ממנו ב-1080p וטוב ממנו (1104 מול 1083).', refs: { i2v: 'HappyHorse-1.0' }, sources: ['aa-i2v'] },

  /* ---------------- ByteDance ---------------- */
  'bytedance/seedance-2.5': { fam: 'bytedance', tier: 'top', released: '2026-07-31',
    lineage: 'Seedance 1.0 (2025) → 2.0 (מרץ 2026) → 2.5.',
    power: 'מספר 3 בעולם (1144). ארכיטקטורת ייחוס אחת: טקסט, עד 30 תמונות, 10 סרטונים ו-10 קטעי שמע כייחוס (גם שמע בלבד), פריים ראשון ואחרון, עריכה והמשך, משך ויחס אוטומטיים.',
    weak: 'Cloudflare לא מפרסמת מחיר: אצל ספקים אחרים 0.10-0.97$ לשנייה לפי רזולוציה ווידאו בקלט. חוסם פנים של אנשים אמיתיים בייחוס.',
    jobs: ['film', 'refs', 'sound', 'edit', 'extend'], tips: ['לסרט עם הרבה חומר ייחוס (מוצר, דמות, מוזיקה) בבת אחת.'],
    gotchas: ['להריץ רק עם --max-usd: המחיר יתברר אחרי הריצה.', 'ייחוס עם פנים אמיתיות נדחה: להשתמש באיור, מוצר או דמות שנוצרה.'],
    hebrew: 'לא רלוונטי.', filter: { n: 0, conf: 'medium', why: 'ByteDance חוסמת פנים אמיתיות בייחוס ומסננת תוכן; אין מתג.' },
    refs: { t2v: 'Dreamina Seedance 2.5' }, sources: ['cf', 'seedance25', 'aa-t2v'] },
  'bytedance/seedance-2.0': { fam: 'bytedance', tier: 'top', released: '2026-03-18',
    lineage: 'Seedance 2.0.', power: '1117 בארנה; רב-שוט קולנועי עם סאונד מובנה (מוזיקה, דיאלוג, אווירה) בבת אחת; עד 9 תמונות, 3 סרטונים ו-3 קטעי שמע כייחוס. 1080p.',
    weak: '0.15$ לשנייה (ויותר עם וידאו בקלט). חוסם פנים אמיתיות.', jobs: ['film', 'sound', 'refs'], tips: ['לשוט גיבור עם סאונד כשאין זמן לפסקול נפרד.'],
    hebrew: 'לא רלוונטי.', filter: { n: 0, conf: 'medium', why: 'כמו 2.5.' }, refs: { t2v: 'Dreamina Seedance 2.0', i2v: 'Dreamina Seedance 2.0 720p', vedit: 'Dreamina Seedance 2.0 720p' }, sources: ['seedance2', 'aa-t2v'] },
  'bytedance/seedance-2.0-fast': { fam: 'bytedance', tier: 'mid', released: '2026-03-18',
    lineage: 'Seedance 2.0 מהיר.', power: 'מהיר מהסטנדרט עם מעט פחות איכות; 480p/720p.', weak: 'Mini מהיר ממנו פי שניים וזול ממנו באיכות קרובה.',
    jobs: ['draft', 'sound'], hebrew: 'לא רלוונטי.', filter: { n: 0, conf: 'medium', why: 'כמו 2.0.' }, refs: {}, sources: ['seedance-mini'] },
  'bytedance/seedance-2.0-mini': { fam: 'bytedance', tier: 'low', released: null,
    lineage: 'Seedance 2.0 Mini.', power: 'בערך חצי ממחיר הסטנדרט (0.09$ לשנייה ב-720p), פי שניים מהר מ-Fast באיכות קרובה; 4-15 שניות.', weak: '480p/720p בלבד.',
    jobs: ['draft'], tips: ['טיוטות ותוכן קצר בנפח; את שוט הגיבור לסיים ב-2.0 או 2.5.'], hebrew: 'לא רלוונטי.', filter: { n: 0, conf: 'medium', why: 'כמו 2.0.' }, refs: {}, sources: ['seedance-mini'] },

  /* ---------------- MiniMax ---------------- */
  'minimax/h3': { fam: 'minimax', tier: 'top', released: '2026-07-31',
    lineage: 'Hailuo 02 → 2.3 → H3 (ידוע גם כ-Hailuo 3), משקלים פתוחים מ-3 באוגוסט.',
    power: 'מספר 4 בעולם (1139) ושני בעריכת וידאו (1132). 2K מקורי, סאונד סטריאו, עד 12 ייחוסים (9 תמונות, 3 סרטונים, 3 קטעי שמע), 5-15 שניות. ב-2K פחות משליש מהמחיר המקובל.',
    weak: 'חדש ופחות מתועד; ב-2K המחיר עולה ל-0.13$ לשנייה.', jobs: ['film', 'refs', 'sound', 'edit'], tips: ['768p לטיוטה (0.08$ לשנייה), 2K לגרסה הסופית (0.13$).'],
    hebrew: 'לא רלוונטי.', filter: { n: null, conf: 'low', why: 'לא נמדד.' }, refs: { t2v: 'MiniMax H3 (768p)', i2v: 'MiniMax H3', vedit: 'MiniMax H3' }, sources: ['minimax-h3', 'aa-t2v', 'aa-vedit'] },
  'minimax/h3-max': { fam: 'minimax', tier: 'top', released: '2026-08-26',
    lineage: 'H3 המהיר.', power: '1134 בארנה (כמעט כמו H3) ו-1195 בתמונה לווידאו, מעל H3. 480p ב-0.05$ לשנייה.', weak: 'עד 768p.',
    jobs: ['i2v', 'draft', 'film'], tips: ['הטיוטה הכי טובה לכל דולר: 480p באיכות של צמרת.'], hebrew: 'לא רלוונטי.', filter: { n: null, conf: 'low', why: 'לא נמדד.' },
    refs: { t2v: 'MiniMax H3 Max (based on MiniMax H3)', i2v: 'MiniMax H3 Max (based on MiniMax H3)' }, sources: ['aa-t2v', 'aa-i2v'] },
  'minimax/hailuo-2.3': { fam: 'minimax', tier: 'top', released: '2025-10-28',
    lineage: 'Hailuo 02 (יוני 2025) → 2.3.', power: 'בארנה של תמונה לווידאו 1255, מעל H3 (1181) ו-Wan 3.0 (1164). מטקסט או מפריים ראשון, 6-10 שניות, 768p/1080p, 0.28$ לקליפ של 6 שניות.',
    weak: 'בלי סאונד; בלי ייחוסים מרובים.', jobs: ['i2v', 'film'], tips: ['להנפשת סטילס של מותג: תנועה טבעית במחיר נמוך.'],
    hebrew: 'לא רלוונטי.', filter: { n: null, conf: 'low', why: 'לא נמדד.' }, refs: { i2v: 'Hailuo 2.3' }, sources: ['aa-i2v'] },
  'minimax/hailuo-2.3-fast': { fam: 'minimax', tier: 'top', released: '2025-10-28',
    lineage: 'Hailuo 2.3 מהיר.', power: 'אותה איכות בתמונה לווידאו (1257) בשני שלישים מהמחיר (0.19$ ל-6 שניות).', weak: 'מתחיל מתמונה בלבד.',
    jobs: ['i2v', 'draft'], tips: ['ברירת המחדל להנפשת תמונה בזרימה.'], hebrew: 'לא רלוונטי.', filter: { n: null, conf: 'low', why: 'לא נמדד.' }, refs: { i2v: 'Hailuo 2.3 Fast' }, sources: ['aa-i2v'] },

  /* ---------------- Black Forest Labs ---------------- */
  'black-forest-labs/flux-3-video': { fam: 'bfl', tier: 'top', released: '2026-07-23',
    lineage: 'FLUX 3: עמוד שדרה אחד לתמונה, וידאו עם סאונד ופעולות רובוט.', power: '1127 בארנה. טקסט, תמונה (אחת או יותר) או המשך קליפ; סאונד מסונכרן (דיאלוג רב-לשוני, אפקטים, מוזיקה) מאותו מודל; 5-20 שניות; עד FHD; מצב טיוטה (0.06$ ל-HD).',
    weak: 'safety_tolerance רק עד 4, עם תקרה למיניות (3) ולשנאה (2).', jobs: ['film', 'sound', 'extend', 'draft', 'loose'],
    tips: ['טיוטת hd draft לפני הגרסה המלאה.', 'safety_tolerance 4 לסצנות קשות לגיטימיות.'], hebrew: 'לא רלוונטי.',
    refs: { t2v: 'FLUX 3' }, sources: ['flux3', 'aa-t2v', 'cf'] },
  'black-forest-labs/flux-video-upscale': { fam: 'bfl', tier: 'low', released: null,
    lineage: 'הגדלת וידאו של BFL.', power: 'שני מצבים: מדויק (0.07$ למגה-פיקסל-שנייה) ויצירתי (0.10$). safety_tolerance עד 4.', weak: 'משימה צרה.',
    jobs: ['upscale'], hebrew: 'לא רלוונטי.', refs: {}, sources: ['cf'] },

  /* ---------------- Google ---------------- */
  'google/gemini-omni-1.1-flash': { fam: 'google', tier: 'top', released: '2026-08-27',
    lineage: 'Gemini Omni Flash (מאי 2026) → 1.1.', power: '1117 בארנה, שלישי בעריכה. יצירה ועריכה בשיחה, סאונד מובנה, המשך סצנה ב-10 שניות עד 40, אינטרפולציה בין פריים ראשון לאחרון, טיוטות 360p (שליש מהמחיר, 60% מהר), עד 4K.',
    weak: 'מחיר לפי טוקנים: המחיר לשנייה לא ידוע מראש. מדיניות Google קשוחה.', jobs: ['film', 'edit', 'extend', 'sound', 'draft'],
    tips: ['360p לטיוטה, אחר כך אותו פרומפט ב-720p או 4K.'], gotchas: ['להריץ עם --max-usd: העלות ידועה רק אחרי הריצה.'],
    hebrew: 'לא רלוונטי.', filter: { n: 0, conf: 'medium', why: 'Google קשוחה בווידאו; אין מתג.' }, refs: { t2v: 'Gemini Omni Flash 1.1' }, sources: ['omni11', 'aa-t2v'] },
  'google/veo-3.1': { fam: 'google', tier: 'low', released: '2026-01-30',
    lineage: 'Veo 2 (2024) → 3 (2025) → 3.1 (ינואר 2026).', power: 'סאונד ודיאלוג מובנים, עד 4K, פריים ראשון ואחרון, עד 3 תמונות ייחוס. מחיר ידוע מראש לפי רזולוציה וסאונד.',
    weak: 'הכי יקר (0.40$ לשנייה עם סאונד) ונמוך בארנה (968, מתחת ל-Omni 1.1 של Google עצמה ב-150 נקודות).', jobs: ['sound', 'film'],
    tips: ['רק כשצריך מחיר ידוע מראש לסרט עם דיאלוג, או 4K עם סאונד.', 'Omni 1.1 מאותו יצרן חזק ממנו; כשהעלות שלו לשנייה תימדד, Veo 3.1 עשוי לעבור למאגר הפסולת.'],
    gotchas: ['image_input דורש base64: הזרימה ממירה קישור לקובץ לבד.'], hebrew: 'מדבב עברית בשמע? לא נבדק.', filter: { n: 0, conf: 'medium', why: 'Google קשוחה; אין מתג.' },
    refs: { t2v: 'Veo 3.1', i2v: 'Veo 3.1' }, sources: ['aa-t2v', 'cf'] },
  'google/veo-3.1-fast': { fam: 'google', tier: 'low', released: '2026-01-30',
    lineage: 'Veo 3.1 מהיר.', power: 'כמעט אותה איכות (961) ב-0.08$ לשנייה ב-720p בלי סאונד; זו טיוטת ה-Veo.', weak: 'נמוך בארנה.',
    jobs: ['draft', 'sound'], tips: ['720p בלי סאונד לטיוטה (הכלל בזרימות).'], hebrew: 'לא נבדק.', filter: { n: 0, conf: 'medium', why: 'כמו Veo 3.1.' },
    refs: { t2v: 'Veo 3.1 Fast', i2v: 'Veo 3.1 Fast' }, sources: ['aa-t2v'] },
  'google/gemini-omni-flash': { fam: 'google', junk: 'R1', instead: ['google/gemini-omni-1.1-flash'], released: '2026-05-19',
    why: '1.1 באותו מחיר טוקנים, עם המשך סצנה, אינטרפולציה, טיוטות 360p ו-4K.', refs: { i2v: 'Gemini Omni Flash', vedit: 'Gemini Omni Flash' }, sources: ['omni11'] },

  /* ---------------- xAI ---------------- */
  'xai/grok-imagine-video-1.5-preview': { fam: 'xai', tier: 'mid', released: '2026-05-30',
    lineage: 'Grok Imagine Video (ינואר 2026) → 1.5 תצוגה מקדימה.', power: 'מתמונה לווידאו עם סאונד מסונכרן, 6-15 שניות, 480p/720p; 1046 בארנה.', weak: '0.14$ לשנייה ב-720p.',
    jobs: ['i2v', 'sound'], hebrew: 'לא רלוונטי.', filter: { n: 1, conf: 'low', why: 'xAI הידקה ב-2026 אבל עדיין נחשבת פחות שמרנית; לא נמדד.' },
    refs: { t2v: 'grok-imagine-video-1.5', i2v: 'grok-imagine-video-1.5' }, sources: ['grok-imagine', 'aa-t2v'] },
  'xai/grok-imagine-video': { fam: 'xai', tier: 'low', released: '2026-01-27',
    lineage: 'הגרסה הראשונה.', power: 'זול (0.05$ לשנייה ב-480p).', weak: '1072 בתמונה לווידאו.', jobs: ['draft', 'i2v'], hebrew: 'לא רלוונטי.',
    filter: { n: 1, conf: 'low', why: 'כמו 1.5.' }, refs: { i2v: 'grok-imagine-video' }, sources: ['aa-i2v'] },

  /* ---------------- Runway ---------------- */
  'runwayml/aleph-2': { fam: 'runway', tier: 'mid', released: '2026-05-21',
    lineage: 'Aleph (2025) → 2.0.', power: 'עורכים פריים אחד והשינוי מתפשט על כל הקליפ: צבע מוצר, שיער, לבוש, רקע, סגנון; משאיר את מה שלא ביקשו לשנות. עד 30 שניות ב-1080p, עד 10 חתכים, עד 5 פריימים מנחים.',
    weak: 'יקר (0.336$ לשנייה); בארנת העריכה 1012, מתחת ל-Wan 3.0, H3 ו-Omni.', jobs: ['edit'], tips: ['לתיקון קליפ קיים של לקוח (לא ליצירה מאפס).'],
    hebrew: 'לא רלוונטי.', filter: { n: 0, conf: 'medium', why: 'Runway קשוחה; content_moderation רק מנמיך את סף הדמויות הציבוריות.' }, refs: { vedit: 'Aleph 2.0' }, sources: ['aleph2', 'aa-vedit'] },
  'runwayml/gen-4.5': { fam: 'runway', tier: 'low', released: '2025-12-01',
    lineage: 'Gen-3 → Gen-4 (2025) → Gen-4.5 (דצמבר 2025).', power: 'חזק בהנפשת תמונה (1265 בלוח של תמונה לווידאו), מגיב להוראות, פיזיקה טובה.',
    weak: 'בטקסט לווידאו 920. סיבתיות (דלת נפתחת לפני שנוגעים בידית), עצמים נעלמים, "הטיית הצלחה".', jobs: ['i2v'],
    hebrew: 'לא רלוונטי.', filter: { n: 0, conf: 'medium', why: 'כמו Aleph.' }, refs: { t2v: 'Runway Gen-4.5 (720p)' }, sources: ['gen45', 'aa-t2v'] },

  /* ---------------- others ---------------- */
  'lightricks/ltx-2-5-fast': { fam: 'lightricks', tier: 'low', released: '2026-08-11',
    lineage: 'LTX-2 → 2.3 (מרץ 2026) → 2.5 (אוגוסט), 22B משקלים פתוחים.', power: 'סאונד מסונכרן, מולטי-שוט, משך אוטומטי, עד 4K (0.37$ לשנייה) ו-2K; 950 בארנה.',
    weak: 'נמוך בארנה ביחס למחיר (0.09$ ב-720p).', jobs: ['sound', 'draft'], hebrew: 'לא רלוונטי.', filter: { n: null, conf: 'low', why: 'לא מתועד.' },
    refs: { t2v: 'LTX-2.5 Fast' }, sources: ['ltx25', 'aa-t2v'] },
  'vidu/q3-pro': { fam: 'vidu', tier: 'low', released: '2026-01-30',
    lineage: 'Vidu Q2 → Q3.', power: 'סאונד ודיאלוג מסונכרן עם כמה דוברים, עד 16 שניות, פריים ראשון ואחרון, 1080p.', weak: '941 בארנה.',
    jobs: ['sound', 'extend'], hebrew: 'לא רלוונטי.', filter: { n: null, conf: 'low', why: 'לא מתועד.' }, refs: { t2v: 'Vidu Q3 Pro', i2v: 'Vidu Q3 Pro' }, sources: ['vidu-q3', 'aa-t2v'] },
  'vidu/q3-turbo': { fam: 'vidu', tier: 'low', released: '2026-02-09',
    lineage: 'Q3 מהיר.', power: 'אותן יכולות סאונד, 0.04$ לשנייה ב-540p.', weak: '913 בארנה.', jobs: ['draft'], hebrew: 'לא רלוונטי.',
    filter: { n: null, conf: 'low', why: 'לא מתועד.' }, refs: { t2v: 'Vidu Q3 Turbo' }, sources: ['vidu-q3', 'aa-t2v'] },
  'pixverse/v6': { fam: 'pixverse', tier: 'low', released: '2026-03-23',
    lineage: 'V5 → V5.5 → V5.6 → V6.', power: '1-15 שניות, סאונד, מ-0.025$ לשנייה ב-360p; 1070 בתמונה לווידאו.', weak: '987 בטקסט לווידאו.',
    jobs: ['draft', 'i2v'], hebrew: 'לא רלוונטי.', filter: { n: null, conf: 'low', why: 'לא מתועד.' }, refs: { t2v: 'PixVerse V6', i2v: 'PixVerse V6' }, sources: ['aa-t2v'] },
  'pixverse/v5.6': { fam: 'pixverse', junk: 'R1', instead: ['pixverse/v6'], released: '2026-02-25',
    why: 'V6 זול ממנו או שווה בכל רזולוציה ומשך (למשל 5 שניות ב-360p: 0.125$ מול 0.175$), גמיש במשך (1-15), וטוב ממנו בתמונה לווידאו (1070 מול 963).', refs: { i2v: 'PixVerse V5.6' }, sources: ['aa-i2v', 'cf'] },

  /* ---------------- Pruna ---------------- */
  'pruna/p-video': { fam: 'pruna', tier: 'low', released: '2026-02-26',
    lineage: 'P-Video (פברואר 2026).', power: 'רצפת המחיר: מטקסט, מתמונה ומשמע, עד 1080p ב-24/48fps, עד 20 שניות; טיוטה של 5 שניות ב-720p תוך 2.5 שניות ב-0.005$ לשנייה. המסנן כבוי כברירת מחדל.',
    weak: '818 בארנה: לא לגרסה סופית.', jobs: ['draft', 'loose', 'i2v'], tips: ['עשרות וריאציות של תנועה ותזמון לפני שמשלמים על שוט צמרת.'], hebrew: 'לא רלוונטי.',
    refs: { t2v: 'P-Video', i2v: 'P-Video' }, sources: ['pruna', 'cf', 'aa-t2v'] },
  'pruna/p-video-avatar': { fam: 'pruna', tier: 'low', released: null,
    lineage: 'אווטאר של Pruna.', power: 'דמות מדברת מתמונת פורטרט אחת ותסריט או קובץ שמע, כמה קולות ושפות, 0.025$ לשנייה. המסנן כבוי כברירת מחדל.', weak: 'עברית לא אומתה.',
    jobs: ['avatar', 'loose'], tips: ['להזין קובץ שמע מקול אחר (Eleven v3, Inworld TTS-2) כדי לקבל עברית.'], hebrew: 'לא אומתה; דרך קובץ שמע.', refs: {}, sources: ['cf'] },
  'pruna/p-video-animate': { fam: 'pruna', tier: 'low', released: null,
    lineage: 'הנפשה של Pruna.', power: 'הנפשת דמות לפי וידאו תנועה, 0.03$ לשנייה, disable_safety_checker.', weak: 'לא נמדד.', jobs: ['i2v', 'loose'], hebrew: 'לא רלוונטי.', refs: {}, sources: ['cf'] },
  'pruna/p-video-replace': { fam: 'pruna', tier: 'low', released: null,
    lineage: 'החלפה של Pruna.', power: 'החלפת דמות בווידאו קיים, 0.03$ לשנייה, disable_safety_checker.', weak: 'לא נמדד.', jobs: ['edit', 'loose'], hebrew: 'לא רלוונטי.', refs: {}, sources: ['cf'] },
};
